<template>
	<aside class="af-inspector">
		<template v-if="draft">
			<div class="af-inspector__head"><strong>节点属性</strong><el-button text type="danger" size="small" @click="$emit('delete',draft.nodeId)">删除</el-button></div>
			<label>名称</label><el-input v-model="draft.name" size="small" @change="commit" />
			<label>类型</label><el-input :model-value="draft.type" size="small" disabled />
			<label>Actor</label><el-select v-model="draft.actorObjectId" clearable filterable size="small" @change="commit"><el-option v-for="item in manifest.objects" :key="item.objectId" :label="item.name" :value="item.objectId" /></el-select>
			<div class="af-inspector__field-head"><label>节点联锁</label><el-button text type="primary" size="small" @click="$emit('create-interlock')">新增</el-button></div><el-select :model-value="interlockIds" multiple clearable filterable size="small" @change="setInterlocks"><el-option v-for="item in manifest.interlocks||[]" :key="item.interlockId" :label="item.name" :value="item.interlockId" /></el-select>
			<template v-if="needsWorkPoint"><label>WorkPoint</label><el-select :model-value="configString('workPointId')" clearable filterable size="small" @change="setConfig('workPointId',$event)"><el-option v-for="item in manifest.workPoints||[]" :key="item.workPointId" :label="item.name" :value="item.workPointId" /></el-select></template>
			<template v-if="draft.type==='MovePose'"><label>Pose</label><el-select :model-value="configString('poseId')" clearable filterable size="small" @change="setConfig('poseId',$event)"><el-option v-for="item in manifest.poses||[]" :key="item.poseId" :label="item.name" :value="item.poseId" /></el-select></template>
			<template v-if="needsActuator"><label>Actuator</label><el-select :model-value="configString('actuatorId')" clearable filterable size="small" @change="setConfig('actuatorId',$event)"><el-option v-for="item in manifest.actuators||[]" :key="item.actuatorId" :label="item.name" :value="item.actuatorId" /></el-select></template>
			<template v-if="needsSlot"><div class="af-inspector__field-head"><label>MaterialSlot</label><el-button text type="primary" size="small" @click="$emit('create-material-slot',slotKey)">新增</el-button></div><el-select :model-value="configString(slotKey)" clearable filterable size="small" @change="setConfig(slotKey,$event)"><el-option v-for="item in manifest.materialSlots||[]" :key="item.slotId" :label="item.name" :value="item.slotId" /></el-select></template>
			<template v-if="needsBinding"><label>Binding</label><el-select :model-value="configString('bindingId')" clearable filterable size="small" @change="setConfig('bindingId',$event)"><el-option v-for="item in manifest.bindings" :key="item.bindingId" :label="item.source.key||item.bindingId" :value="item.bindingId" /></el-select></template>
			<template v-if="needsRoute"><label>Route</label><el-select :model-value="configString('routeId')" clearable filterable size="small" @change="setConfig('routeId',$event)"><el-option v-for="item in manifest.routes" :key="item.routeId" :label="item.name" :value="item.routeId" /></el-select><label>Section / Edge</label><el-input :model-value="configString('sectionId')" size="small" @change="setConfig('sectionId',$event)" /></template>
			<template v-if="draft.type==='Delay'"><label>延时秒数</label><el-input-number :model-value="Number(draft.config.durationSeconds||0)" :min="0" :step="0.1" size="small" @change="setConfig('durationSeconds',$event)" /></template>
			<template v-if="['WaitStation','CompleteStation'].includes(draft.type)"><label>工位完成组</label><el-select :model-value="configString('completionGroup')" aria-label="工位完成组" size="small" @change="setConfig('completionGroup',$event)"><el-option v-for="group in completionGroups" :key="group" :label="group" :value="group" /></el-select></template>
			<template v-if="draft.type==='WaitInterlock'"><label>等待联锁</label><el-select :model-value="configString('interlockId')" aria-label="等待联锁" size="small" filterable @change="setConfig('interlockId',$event)"><el-option v-for="lock in manifest.interlocks||[]" :key="lock.interlockId" :label="lock.name" :value="lock.interlockId" /></el-select></template>
			<template v-if="draft.type==='SetState'"><label>写入范围</label><el-select :model-value="configString('scope')||'semantic'" aria-label="状态写入范围" size="small" @change="setConfig('scope',$event)"><el-option label="工艺共享状态" value="semantic"/><el-option label="当前流程变量" value="variable"/></el-select><el-input :model-value="configString('ref')" aria-label="状态键或变量名" size="small" @change="setConfig('ref',$event)"/><label>值（JSON）</label><el-input :model-value="JSON.stringify(draft.config.value??null)" aria-label="状态值 JSON" size="small" @change="setJsonValue('value',$event)" /></template>
			<template v-if="draft.type==='MarkMaterial'"><label>物料工艺阶段</label><el-input :model-value="configString('stage')" aria-label="物料工艺阶段" size="small" @change="setConfig('stage',$event)" /></template>
			<template v-if="draft.type==='Loop'"><label>最大批次数</label><el-input-number :model-value="Number(draft.config.maxIterations||1000)" aria-label="最大批次数" :min="1" :max="100000" size="small" @change="setConfig('maxIterations',$event)" /></template>
			<template v-if="draft.type==='SelectRoute'"><label>岔口</label><el-select :model-value="configString('junctionPointId')" aria-label="目标岔口" size="small" filterable @change="setConfig('junctionPointId',$event)"><el-option v-for="point in selectedRoute?.points||[]" :key="point.pointId" :label="point.name" :value="point.pointId" /></el-select><label>出边</label><el-select :model-value="configString('edgeId')" aria-label="岔口出边" size="small" filterable @change="setConfig('edgeId',$event)"><el-option v-for="edge in selectedRoute?.edges.filter(e=>e.fromPointId===configString('junctionPointId'))||[]" :key="edge.edgeId" :label="edge.name||edge.edgeId" :value="edge.edgeId" /></el-select></template>
			<template v-if="['MoveTo','Pick','Place','Attach','Detach'].includes(draft.type)"><label>工具 TCP</label><el-select :model-value="configString('toolFrameId')" aria-label="工具 TCP" size="small" clearable @change="setConfig('toolFrameId',$event)"><el-option v-for="frame in manifest.toolFrames?.filter(f=>f.objectId===draft?.actorObjectId)||[]" :key="frame.toolFrameId" :label="frame.name" :value="frame.toolFrameId" /></el-select></template>
			<template v-if="['Attach','Pick','MoveTo'].includes(draft.type)"><label>抓取数量</label><el-input-number :model-value="Number(draft.config.payloadCount||1)" aria-label="抓取数量" :min="1" :max="12" size="small" @change="setConfig('payloadCount',$event)" /></template>
			<template v-if="['MoveTo','Place','Pick'].includes(draft.type)"><label>接近偏移 XYZ（米）</label><div class="af-inspector__grid"><el-input-number v-for="axis in [0,1,2]" :key="axis" :model-value="Number((draft.config.approachOffset as number[]|undefined)?.[axis]||0)" :aria-label="`接近偏移 ${['X','Y','Z'][axis]}`" :step="0.1" size="small" @change="setOffset(axis,$event)" /></div></template>
			<template v-if="['MoveTo','MovePose','JointMove','AxisMove','Home','Place','Pick'].includes(draft.type)"><label>动作速度倍率</label><el-input-number :model-value="Number(draft.config.speedRatio||1)" aria-label="动作速度倍率" :min="0.1" :max="2" :step="0.1" size="small" @change="setConfig('speedRatio',$event)" /></template>
			<template v-if="['JointMove','AxisMove'].includes(draft.type)"><label>目标轴值</label><el-input-number :model-value="Number(draft.config.targetValue||0)" aria-label="目标轴值" :step="0.1" size="small" @change="setConfig('targetValue',$event)" /></template>
			<MaterialConditionEditor v-if="draft.type==='Condition'" :predicate="draft.config.predicate" :manifest="manifest" :variables="flow.variables" @update="setConfig('predicate',$event)"/>
			<small v-if="flow.policies.executionTarget==='scene' && ['Attach','Pick','Place','Detach'].includes(draft.type)">取料必须有真实库存、空闲工具、夹紧确认和接触到位。Place/Detach 在目标有容量且接触时完成交接并松爪；不能用 GripOpen 在空中释放物料。</small>
			<div class="af-inspector__toggle"><strong>有限超时</strong><el-switch :model-value="Boolean(draft.timeoutPolicy)" @change="toggleTimeout(Boolean($event))" /></div>
			<div v-if="draft.timeoutPolicy" class="af-inspector__grid"><el-input-number v-model="draft.timeoutPolicy.seconds" :min="0.1" :step="1" size="small" @change="commit" /><el-select v-model="draft.timeoutPolicy.onTimeout" size="small" @change="commit"><el-option v-for="x in ['fault','retry','compensate','manualConfirm','skip']" :key="x" :label="x" :value="x" /></el-select></div>
			<div class="af-inspector__toggle"><strong>重试策略</strong><el-switch :model-value="Boolean(draft.retryPolicy)" @change="toggleRetry(Boolean($event))" /></div>
			<div v-if="draft.retryPolicy" class="af-inspector__grid"><el-input-number v-model="draft.retryPolicy.maxAttempts" :min="1" :step="1" size="small" @change="commit" /><el-input-number v-model="draft.retryPolicy.backoffSeconds" :min="0" :step="0.5" size="small" @change="commit" /></div>
			<label>补偿节点</label><el-select v-model="draft.compensationNodeId" clearable size="small" @change="commit"><el-option v-for="item in flow.nodes.filter(n=>n.nodeId!==draft?.nodeId)" :key="item.nodeId" :label="item.name" :value="item.nodeId" /></el-select>
			<label>受控 Config JSON</label><el-input v-model="configText" type="textarea" :rows="8" @change="commitConfigText" /><small>仅允许 JSON；编译器会拒绝脚本、凭据、外部 URL 和无效引用。</small>
			<div class="af-inspector__actions"><el-button size="small" @click="$emit('focus-actor',draft.actorObjectId)">3D 定位 Actor</el-button><el-button v-if="flow.policies.executionTarget!=='scene'" size="small" :type="breakpoint?'danger':'default'" @click="$emit('breakpoint',draft.nodeId,!breakpoint)">{{ breakpoint?'取消断点':'设置断点' }}</el-button></div>
		</template>
		<el-empty v-else :image-size="48" description="选择流程节点查看属性" />
	</aside>
</template>
<script setup lang="ts">
import MaterialConditionEditor from './MaterialConditionEditor.vue';
import { computed, ref, toRaw, watch } from 'vue';import { ElMessage } from 'element-plus';import type { TwinSceneManifest } from '../../contracts';import type { TwinActionFlowDefinitionV2,TwinActionFlowNode } from '../contracts/action-flow-v2';
const props=defineProps<{node?:TwinActionFlowNode;flow:TwinActionFlowDefinitionV2;manifest:TwinSceneManifest;breakpoint?:boolean}>();const emit=defineEmits<{(e:'update',node:TwinActionFlowNode):void;(e:'delete',id:string):void;(e:'focus-actor',id?:string):void;(e:'breakpoint',id:string,enabled:boolean):void;(e:'create-interlock'):void;(e:'create-material-slot',configKey:string):void}>();
const cloneNode=(value:TwinActionFlowNode)=>structuredClone(toRaw(value));
const draft=ref<TwinActionFlowNode>();const configText=ref('{}');watch(()=>props.node,(value)=>{draft.value=value?cloneNode(value):undefined;configText.value=JSON.stringify(value?.config||{},null,2);},{immediate:true,deep:true});
const needsWorkPoint=computed(()=>['MoveTo','Pick','Place'].includes(draft.value?.type||''));const needsActuator=computed(()=>['JointMove','AxisMove','GripOpen','GripClose'].includes(draft.value?.type||''));const needsBinding=computed(()=>['WaitSignal','WriteCommand','WaitAck'].includes(draft.value?.type||''));const needsRoute=computed(()=>['ReserveSection','EnterSection','LeaveSection','SelectRoute'].includes(draft.value?.type||''));const needsSlot=computed(()=>['PrepareSlot','ReserveSlot','ReleaseSlot','Attach','Detach','Pick','Place'].includes(draft.value?.type||''));const slotKey=computed(()=>['Attach','Pick'].includes(draft.value?.type||'')?'sourceSlotId':['Detach','Place'].includes(draft.value?.type||'')?'targetSlotId':'slotId');const interlockIds=computed(()=>Array.isArray(draft.value?.config.interlockIds)?draft.value!.config.interlockIds as string[]:[]);
const configString=(key:string)=>String(draft.value?.config?.[key]||'');const commit=()=>draft.value&&emit('update',cloneNode(draft.value));const setConfig=(key:string,value:unknown)=>{if(!draft.value)return;draft.value.config[key]=value??'';configText.value=JSON.stringify(draft.value.config,null,2);commit();};const setInterlocks=(value:unknown)=>setConfig('interlockIds',Array.isArray(value)?value:[]);
const completionGroups=computed(()=>[...new Set(props.manifest.routes.flatMap(r=>r.points.filter(p=>p.componentObjectId===draft.value?.actorObjectId).flatMap(p=>[...(p.process?.behaviorCompletionGroups||[]),...Object.keys(p.process?.behaviorCompletionRequirements||{})])))]);
const selectedRoute=computed(()=>props.manifest.routes.find(r=>r.routeId===configString('routeId')));
const simplePredicate=computed(()=>{const p=draft.value?.config.predicate as any;return draft.value?.type==='Condition'&&p?.items?.length===1&&!p.items[0].logic?p.items[0]:undefined;});
const setPredicate=(key:string,value:unknown)=>{if(!simplePredicate.value)return;setConfig('predicate',{logic:'and',items:[{...simplePredicate.value,[key]:value}]});};
const setPredicateValue=(value:string)=>{try{setPredicate('value',JSON.parse(value));}catch{ElMessage.error('比较值必须是 JSON，例如 true、0 或双引号包裹的文本');}};
const setJsonValue=(key:string,value:string)=>{try{setConfig(key,JSON.parse(value));}catch{ElMessage.error('请输入合法 JSON 值');}};
const setOffset=(axis:number,value:unknown)=>{const offset=[...((draft.value?.config.approachOffset as number[])||[0,0,0])];offset[axis]=Number(value||0);setConfig('approachOffset',offset);};
const toggleTimeout=(enabled:boolean)=>{if(!draft.value)return;draft.value.timeoutPolicy=enabled?draft.value.timeoutPolicy||{seconds:300,onTimeout:'fault'}:undefined;commit();};const toggleRetry=(enabled:boolean)=>{if(!draft.value)return;draft.value.retryPolicy=enabled?draft.value.retryPolicy||{maxAttempts:3,backoffSeconds:1,backoffMultiplier:2}:undefined;commit();};
const commitConfigText=()=>{if(!draft.value)return;try{const parsed=JSON.parse(configText.value||'{}');if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('Config 必须是 JSON 对象');draft.value.config=parsed;commit();}catch(e){ElMessage.error(e instanceof Error?e.message:'Config JSON 无效');configText.value=JSON.stringify(draft.value.config,null,2);}};
</script>
<style scoped>
.af-inspector{width:280px;min-width:260px;padding:10px;border-left:1px solid var(--el-border-color);overflow:auto;background:var(--el-bg-color);display:flex;flex-direction:column;gap:7px}.af-inspector label,.af-inspector small{font-size:11px;color:var(--el-text-color-secondary)}.af-inspector__head,.af-inspector__toggle,.af-inspector__actions{display:flex;align-items:center;justify-content:space-between;gap:8px}.af-inspector__grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.af-inspector__actions{margin-top:8px}
.af-inspector__field-head{display:flex;min-height:24px;align-items:center;justify-content:space-between;gap:8px}
</style>
