<template>
	<aside class="af-inspector">
		<template v-if="draft">
			<div class="af-inspector__head"><strong>节点属性</strong><el-button text type="danger" size="small" @click="$emit('delete',draft.nodeId)">删除</el-button></div>
			<label>名称</label><el-input v-model="draft.name" size="small" @change="commit" />
			<label>类型</label><el-input :model-value="draft.type" size="small" disabled />
			<label>Actor</label><el-select v-model="draft.actorObjectId" clearable filterable size="small" @change="commit"><el-option v-for="item in manifest.objects" :key="item.objectId" :label="item.name" :value="item.objectId" /></el-select>
			<div class="af-inspector__field-head"><label>节点联锁</label><el-button text type="primary" size="small" @click="$emit('create-interlock')">新增</el-button></div><el-select :model-value="interlockIds" multiple clearable filterable size="small" @change="setInterlocks"><el-option v-for="item in manifest.interlocks||[]" :key="item.interlockId" :label="item.name" :value="item.interlockId" /></el-select>
			<template v-if="needsWorkPoint"><label>WorkPoint</label><el-select :model-value="configString('workPointId')" clearable filterable size="small" @change="setConfig('workPointId',$event)"><el-option v-for="item in manifest.workPoints||[]" :key="item.workPointId" :label="item.name" :value="item.workPointId" /></el-select></template>
			<template v-if="draft.type==='MovePose'"><label>Pose</label><el-select :model-value="configString('poseId')" clearable filterable size="small" @change="setConfig('poseId',$event)"><el-option v-for="item in manifest.poses||[]" :key="item.poseId" :label="item.name" :value="item.poseId" /></el-select></template>
			<template v-if="needsActuator"><label>Actuator</label><el-select :model-value="configString('actuatorId')" clearable filterable size="small" @change="setConfig('actuatorId',$event)"><el-option v-for="item in manifest.actuators||[]" :key="item.actuatorId" :label="item.name" :value="item.actuatorId" /></el-select></template>
			<template v-if="needsSlot"><div class="af-inspector__field-head"><label>MaterialSlot</label><el-button text type="primary" size="small" @click="$emit('create-material-slot',slotKey)">新增</el-button></div><el-select :model-value="configString(slotKey)" clearable filterable size="small" @change="setConfig(slotKey,$event)"><el-option v-for="item in manifest.materialSlots||[]" :key="item.slotId" :label="item.name" :value="item.slotId" /></el-select></template>
			<template v-if="needsBinding"><label>Binding</label><el-select :model-value="configString('bindingId')" clearable filterable size="small" @change="setConfig('bindingId',$event)"><el-option v-for="item in manifest.bindings" :key="item.bindingId" :label="item.source.key||item.bindingId" :value="item.bindingId" /></el-select></template>
			<template v-if="needsRoute"><label>Route</label><el-select :model-value="configString('routeId')" clearable filterable size="small" @change="setConfig('routeId',$event)"><el-option v-for="item in manifest.routes" :key="item.routeId" :label="item.name" :value="item.routeId" /></el-select><label>Section / Edge</label><el-input :model-value="configString('sectionId')" size="small" @change="setConfig('sectionId',$event)" /></template>
			<template v-if="draft.type==='Delay'"><label>延时秒数</label><el-input-number :model-value="Number(draft.config.durationSeconds||0)" :min="0" :step="0.1" size="small" @change="setConfig('durationSeconds',$event)" /></template>
			<div class="af-inspector__toggle"><strong>有限超时</strong><el-switch :model-value="Boolean(draft.timeoutPolicy)" @change="toggleTimeout(Boolean($event))" /></div>
			<div v-if="draft.timeoutPolicy" class="af-inspector__grid"><el-input-number v-model="draft.timeoutPolicy.seconds" :min="0.1" :step="1" size="small" @change="commit" /><el-select v-model="draft.timeoutPolicy.onTimeout" size="small" @change="commit"><el-option v-for="x in ['fault','retry','compensate','manualConfirm','skip']" :key="x" :label="x" :value="x" /></el-select></div>
			<div class="af-inspector__toggle"><strong>重试策略</strong><el-switch :model-value="Boolean(draft.retryPolicy)" @change="toggleRetry(Boolean($event))" /></div>
			<div v-if="draft.retryPolicy" class="af-inspector__grid"><el-input-number v-model="draft.retryPolicy.maxAttempts" :min="1" :step="1" size="small" @change="commit" /><el-input-number v-model="draft.retryPolicy.backoffSeconds" :min="0" :step="0.5" size="small" @change="commit" /></div>
			<label>补偿节点</label><el-select v-model="draft.compensationNodeId" clearable size="small" @change="commit"><el-option v-for="item in flow.nodes.filter(n=>n.nodeId!==draft?.nodeId)" :key="item.nodeId" :label="item.name" :value="item.nodeId" /></el-select>
			<label>受控 Config JSON</label><el-input v-model="configText" type="textarea" :rows="8" @change="commitConfigText" /><small>仅允许 JSON；编译器会拒绝脚本、凭据、外部 URL 和无效引用。</small>
			<div class="af-inspector__actions"><el-button size="small" @click="$emit('focus-actor',draft.actorObjectId)">3D 定位 Actor</el-button><el-button size="small" :type="breakpoint?'danger':'default'" @click="$emit('breakpoint',draft.nodeId,!breakpoint)">{{ breakpoint?'取消断点':'设置断点' }}</el-button></div>
		</template>
		<el-empty v-else :image-size="48" description="选择流程节点查看属性" />
	</aside>
</template>
<script setup lang="ts">
import { computed, ref, toRaw, watch } from 'vue';import { ElMessage } from 'element-plus';import type { TwinSceneManifest } from '../../contracts';import type { TwinActionFlowDefinitionV2,TwinActionFlowNode } from '../contracts/action-flow-v2';
const props=defineProps<{node?:TwinActionFlowNode;flow:TwinActionFlowDefinitionV2;manifest:TwinSceneManifest;breakpoint?:boolean}>();const emit=defineEmits<{(e:'update',node:TwinActionFlowNode):void;(e:'delete',id:string):void;(e:'focus-actor',id?:string):void;(e:'breakpoint',id:string,enabled:boolean):void;(e:'create-interlock'):void;(e:'create-material-slot',configKey:string):void}>();
const cloneNode=(value:TwinActionFlowNode)=>structuredClone(toRaw(value));
const draft=ref<TwinActionFlowNode>();const configText=ref('{}');watch(()=>props.node,(value)=>{draft.value=value?cloneNode(value):undefined;configText.value=JSON.stringify(value?.config||{},null,2);},{immediate:true,deep:true});
const needsWorkPoint=computed(()=>['MoveTo'].includes(draft.value?.type||''));const needsActuator=computed(()=>['JointMove','AxisMove','GripOpen','GripClose'].includes(draft.value?.type||''));const needsBinding=computed(()=>['WaitSignal','WriteCommand','WaitAck'].includes(draft.value?.type||''));const needsRoute=computed(()=>['ReserveSection','EnterSection','LeaveSection','SelectRoute'].includes(draft.value?.type||''));const needsSlot=computed(()=>['PrepareSlot','ReserveSlot','ReleaseSlot','Attach','Detach'].includes(draft.value?.type||''));const slotKey=computed(()=>draft.value?.type==='Attach'?'sourceSlotId':draft.value?.type==='Detach'?'targetSlotId':'slotId');const interlockIds=computed(()=>Array.isArray(draft.value?.config.interlockIds)?draft.value!.config.interlockIds as string[]:[]);
const configString=(key:string)=>String(draft.value?.config?.[key]||'');const commit=()=>draft.value&&emit('update',cloneNode(draft.value));const setConfig=(key:string,value:unknown)=>{if(!draft.value)return;draft.value.config[key]=value??'';configText.value=JSON.stringify(draft.value.config,null,2);commit();};const setInterlocks=(value:unknown)=>setConfig('interlockIds',Array.isArray(value)?value:[]);
const toggleTimeout=(enabled:boolean)=>{if(!draft.value)return;draft.value.timeoutPolicy=enabled?draft.value.timeoutPolicy||{seconds:300,onTimeout:'fault'}:undefined;commit();};const toggleRetry=(enabled:boolean)=>{if(!draft.value)return;draft.value.retryPolicy=enabled?draft.value.retryPolicy||{maxAttempts:3,backoffSeconds:1,backoffMultiplier:2}:undefined;commit();};
const commitConfigText=()=>{if(!draft.value)return;try{const parsed=JSON.parse(configText.value||'{}');if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('Config 必须是 JSON 对象');draft.value.config=parsed;commit();}catch(e){ElMessage.error(e instanceof Error?e.message:'Config JSON 无效');configText.value=JSON.stringify(draft.value.config,null,2);}};
</script>
<style scoped>
.af-inspector{width:280px;min-width:260px;padding:10px;border-left:1px solid var(--el-border-color);overflow:auto;background:var(--el-bg-color);display:flex;flex-direction:column;gap:7px}.af-inspector label,.af-inspector small{font-size:11px;color:var(--el-text-color-secondary)}.af-inspector__head,.af-inspector__toggle,.af-inspector__actions{display:flex;align-items:center;justify-content:space-between;gap:8px}.af-inspector__grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.af-inspector__actions{margin-top:8px}
.af-inspector__field-head{display:flex;min-height:24px;align-items:center;justify-content:space-between;gap:8px}
</style>
