<template>
	<section ref="designerRoot" class="af-designer" :class="{ 'is-fullscreen': isFullscreen }">
		<header class="af-toolbar">
			<div class="af-toolbar__left"><strong>Action Flow V2</strong><el-select v-model="selectedFlowId" size="small" style="width:240px" placeholder="选择流程"><el-option v-for="flow in localFlows" :key="flow.flowId" :label="`${flow.name} · r${flow.revision}`" :value="flow.flowId" /></el-select><el-button size="small" @click="addBlankFlow">新建</el-button><el-dropdown trigger="click" @command="addTemplate"><el-button size="small">模板</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-for="item in actionFlowTemplates" :key="item.kind" :command="item.kind">{{ item.name }}</el-dropdown-item></el-dropdown-menu></template></el-dropdown><el-dropdown v-if="manifest.behaviors?.length" trigger="click" @command="migrateBehavior"><el-button size="small" type="primary" plain>V1 一键转换</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="__all">转换全部未迁移 Behavior</el-dropdown-item><el-dropdown-item divided v-for="behavior in manifest.behaviors" :key="behavior.behaviorId" :command="behavior.behaviorId">{{ behavior.name }}</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div>
			<div class="af-toolbar__right"><el-tag v-if="currentFlow?.graphHash" size="small" type="info">{{ currentFlow.graphHash }}</el-tag><el-button size="small" @click="toggleFullscreen">{{ isFullscreen ? '退出全屏' : '全屏' }}</el-button><el-button size="small" :disabled="!currentFlow" @click="compileCurrent">校验并编译</el-button><el-button size="small" type="danger" plain :disabled="!currentFlow" @click="removeCurrentFlow">删除流程</el-button></div>
		</header>
		<div v-if="currentFlow" class="af-main">
			<ActionNodePalette @add="addNode($event)" />
			<div class="af-center">
				<div class="af-flow-meta"><el-input v-model="currentFlow.name" size="small" @change="commitFlows"/><el-input v-model="currentFlow.key" size="small" @change="commitFlows"/><el-input-number v-model="currentFlow.policies.defaultTimeoutSeconds" :min="0.1" :step="10" size="small" controls-position="right" @change="commitFlows"/><el-input-number v-model="currentFlow.policies.maxLoopIterations" :min="1" :step="1" size="small" controls-position="right" @change="commitFlows"/><el-switch v-model="currentFlow.enabled" active-text="启用" @change="commitFlows"/></div>
				<ActionFlowCanvas :flow="currentFlow" :manifest="manifest" :selected-node-id="selectedNodeId" :focused-object-id="focusObjectId" :node-states="runtimeSnapshot?.nodeStates" :active-node-ids="runtimeSnapshot?.activeNodeIds" :breakpoints="breakpoints" @select="selectedNodeId=$event" @move-node="moveNode" @add-node="addNode" @connect="connectNodes" @focus-actor="$emit('focus-object',$event)" />
			</div>
			<ActionNodeInspector :node="selectedNode" :flow="currentFlow" :manifest="manifest" :breakpoint="Boolean(selectedNode&&breakpoints.includes(selectedNode.nodeId))" @update="updateNode" @delete="deleteNode" @focus-actor="$emit('focus-object',$event)" @breakpoint="setBreakpoint" @create-interlock="createNodeInterlock" @create-material-slot="createNodeMaterialSlot" />
		</div>
		<el-empty v-else class="af-empty" description="当前场景还没有 Action Flow V2。可新建、套用工业模板或从 Behavior V1 一键转换。" />
		<ActionFlowDiagnostics v-if="currentFlow" :diagnostics="diagnostics" @locate="locateDiagnostic" />
		<ActionFlowDebugger v-if="currentFlow" :snapshot="runtimeSnapshot" :mode="runtimeMode" :connection-state="liveConnectionState" :manual-steps="manualConfirmSteps" :failed-steps="failedSteps" @mode="setRuntimeMode" @start="startRuntime" @pause="pauseRuntime" @resume="resumeRuntime" @step="stepSimulation" @stop="stopRuntime" @speed="setSimulationSpeed" @signal="injectSignal" @manual-confirm="manualConfirmLive" @retry="retryLiveStep" />
	</section>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, toRaw, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import type { TwinActionFlowRun, TwinPersistedActionFlow } from '/@/api/digital-twin';
import type { TwinInterlockDefinition, TwinMaterialSlotDefinition, TwinSceneManifest } from '../../contracts';
import { createOrchestrationId } from '../../orchestration/TwinOrchestrationDesigner';
import { blockingActionFlowNodeTypes, type TwinActionFlowDefinitionV2, type TwinActionFlowDiagnostic, type TwinActionFlowNode, type TwinActionFlowNodeType } from '../contracts/action-flow-v2';
import { compileActionFlow, ActionFlowCompileError } from '../compiler/ActionFlowCompiler';
import { migrateBehaviorV1 } from '../migration/BehaviorV1Migrator';
import { SimulationFlowRuntime, type SimulationFlowRuntimeSnapshot } from '../runtime/SimulationFlowRuntime';
import { LiveFlowRuntimeClient, type LiveFlowRuntimeSnapshot } from '../runtime/LiveFlowRuntimeClient';
import { actionFlowTemplates, createActionFlowTemplate, type ActionFlowTemplateKind } from '../templates';
import { validateActionFlow } from '../validation/ActionFlowValidator';
import ActionNodePalette from './ActionNodePalette.vue';
import ActionFlowCanvas from './ActionFlowCanvas.vue';
import ActionNodeInspector from './ActionNodeInspector.vue';
import ActionFlowDiagnostics from './ActionFlowDiagnostics.vue';
import ActionFlowDebugger from './ActionFlowDebugger.vue';

type RuntimeMode = 'simulation' | 'live';
const props=defineProps<{flows:TwinActionFlowDefinitionV2[];manifest:TwinSceneManifest;focusObjectId?:string;persistedFlows?:TwinPersistedActionFlow[];sceneId?:string;publishedVersionId?:string;sceneRevision?:number;publishedSourceRevision?:number}>();
const emit=defineEmits<{(e:'update:flows',flows:TwinActionFlowDefinitionV2[]):void;(e:'focus-object',objectId?:string):void;(e:'changed'):void;(e:'create-interlock',definition:TwinInterlockDefinition):void;(e:'create-material-slot',definition:TwinMaterialSlotDefinition):void}>();
const designerRoot=ref<HTMLElement>();
const isFullscreen=ref(false);
const syncFullscreenState=()=>{isFullscreen.value=document.fullscreenElement===designerRoot.value;};
const toggleFullscreen=async()=>{try{if(document.fullscreenElement===designerRoot.value){await document.exitFullscreen();return;}if(document.fullscreenElement)await document.exitFullscreen();if(!designerRoot.value?.requestFullscreen){ElMessage.warning('当前浏览器不支持元素全屏');return;}await designerRoot.value.requestFullscreen();}catch(error){ElMessage.error(error instanceof Error?error.message:'进入全屏失败');}};
document.addEventListener('fullscreenchange',syncFullscreenState);
const clonePlain=<T,>(value:T):T=>structuredClone(toRaw(value));
const cloneFlows=(value:TwinActionFlowDefinitionV2[]|undefined)=>clonePlain(value||[]);
const localFlows=ref<TwinActionFlowDefinitionV2[]>(cloneFlows(props.flows));const selectedFlowId=ref(localFlows.value[0]?.flowId||'');const selectedNodeId=ref('');const breakpoints=ref<string[]>([]);let runtime:SimulationFlowRuntime|undefined;let liveRuntime:LiveFlowRuntimeClient|undefined;let runtimeTimer:number|undefined;const runtimeMode=ref<RuntimeMode>('simulation');const runtimeSnapshot=ref<SimulationFlowRuntimeSnapshot|LiveFlowRuntimeSnapshot>();const liveRunDetail=ref<TwinActionFlowRun>();
watch(()=>props.flows,(value)=>{const incoming=JSON.stringify(value||[]),current=JSON.stringify(localFlows.value);if(incoming!==current){localFlows.value=cloneFlows(value);if(!localFlows.value.some(x=>x.flowId===selectedFlowId.value))selectedFlowId.value=localFlows.value[0]?.flowId||'';}},{deep:true});
const nodeTargetsObject=(node:TwinActionFlowNode,objectId:string)=>{if(node.actorObjectId===objectId)return true;const workPointId=String(node.config?.workPointId||'');return Boolean(workPointId&&(props.manifest.workPoints||[]).some(point=>point.workPointId===workPointId&&point.objectId===objectId));};
watch(()=>props.focusObjectId,(objectId)=>{if(!objectId)return;const flow=localFlows.value.find(item=>item.nodes.some(node=>nodeTargetsObject(node,objectId)));if(!flow)return;selectedFlowId.value=flow.flowId;const node=flow.nodes.find(item=>nodeTargetsObject(item,objectId));if(node)selectedNodeId.value=node.nodeId;},{immediate:true});
const currentFlow=computed(()=>localFlows.value.find(x=>x.flowId===selectedFlowId.value));const selectedNode=computed(()=>currentFlow.value?.nodes.find(x=>x.nodeId===selectedNodeId.value));const diagnostics=computed(()=>currentFlow.value?validateActionFlow(currentFlow.value,props.manifest,localFlows.value):[]);
const persistedCurrentFlow=computed(()=>{const key=currentFlow.value?.key;return key?(props.persistedFlows||[]).find(item=>item.flowKey===key):undefined;});
const liveConnectionState=computed(()=>runtimeMode.value==='live'&&runtimeSnapshot.value&&'connectionState' in runtimeSnapshot.value?runtimeSnapshot.value.connectionState:'disconnected');
const manualConfirmSteps=computed(()=>{const flow=currentFlow.value;return (liveRunDetail.value?.steps||[]).filter(step=>step.status==='Waiting'&&flow?.nodes.some(node=>node.nodeId===step.nodeId&&node.type==='ManualConfirm')).map(step=>({stepInstanceId:step.stepInstanceId,nodeId:step.nodeId,label:`${flow?.nodes.find(node=>node.nodeId===step.nodeId)?.name||step.nodeId} · #${step.attempt}`}));});
const failedSteps=computed(()=>{const flow=currentFlow.value;return (liveRunDetail.value?.steps||[]).filter(step=>step.status==='Failed').map(step=>({stepInstanceId:step.stepInstanceId,nodeId:step.nodeId,label:`${flow?.nodes.find(node=>node.nodeId===step.nodeId)?.name||step.nodeId} · #${step.attempt}`}));});
const id=(p:string)=>`${p}-${globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}`;
const commitFlows=()=>{emit('update:flows',cloneFlows(localFlows.value));emit('changed');};
const blankFlow=():TwinActionFlowDefinitionV2=>{const start=id('start'),end=id('end');return{flowId:id('flow'),key:`flow-${Date.now().toString(36)}`,name:'新 Action Flow',contractVersion:'2.0',actorObjectIds:[],variables:[],nodes:[{nodeId:start,type:'Start',name:'开始',config:{},editor:{x:80,y:160}},{nodeId:end,type:'End',name:'结束',config:{},editor:{x:420,y:160}}],edges:[{edgeId:id('edge'),sourceNodeId:start,sourcePort:'success',targetNodeId:end}],policies:{defaultTimeoutSeconds:300,maxLoopIterations:100,requireInterlockForCommands:true},enabled:true,revision:1,status:'Draft'};};
const addBlankFlow=()=>{const f=blankFlow();localFlows.value.push(f);selectedFlowId.value=f.flowId;selectedNodeId.value=f.nodes[0].nodeId;commitFlows();};
const addTemplate=(kind:ActionFlowTemplateKind)=>{const f=createActionFlowTemplate(kind);localFlows.value.push(f);selectedFlowId.value=f.flowId;selectedNodeId.value=f.nodes[0]?.nodeId||'';commitFlows();};
const migrateBehavior=(command:string)=>{const ids=command==='__all'?(props.manifest.behaviors||[]).filter(b=>!localFlows.value.some(f=>f.legacyBehaviorId===b.behaviorId)).map(b=>b.behaviorId):[command];let count=0;for(const behaviorId of ids){const b=(props.manifest.behaviors||[]).find(x=>x.behaviorId===behaviorId);if(!b||localFlows.value.some(f=>f.legacyBehaviorId===b.behaviorId))continue;const f=migrateBehaviorV1(clonePlain(b));localFlows.value.push(f);selectedFlowId.value=f.flowId;count++;}if(count){commitFlows();ElMessage.success(`已转换 ${count} 个 Behavior V1，原定义继续保留兼容读取。`);}else ElMessage.info('没有需要转换的 Behavior。');};
const removeCurrentFlow=async()=>{const f=currentFlow.value;if(!f)return;await ElMessageBox.confirm(`删除 Action Flow「${f.name}」？Behavior V1 不受影响。`,'删除流程',{type:'warning'});localFlows.value=localFlows.value.filter(x=>x.flowId!==f.flowId);selectedFlowId.value=localFlows.value[0]?.flowId||'';selectedNodeId.value='';commitFlows();};
const defaultConfig=(type:TwinActionFlowNodeType)=>{if(type==='Condition')return{predicate:{logic:'and',items:[]}};if(type==='ParallelJoin')return{strategy:'all'};if(type==='Delay')return{durationSeconds:1};if(type==='WriteCommand')return{bindingId:'',interlockIds:[],payload:{}};if(['MoveTo','MovePose','JointMove','AxisMove','Home','GripOpen','GripClose'].includes(type))return{interlockIds:[]};return{};};
const addNode=(type:TwinActionFlowNodeType|string,x=220,y=220)=>{const f=currentFlow.value;if(!f)return;const t=type as TwinActionFlowNodeType;const n:TwinActionFlowNode={nodeId:id(t.toLowerCase()),type:t,name:t,config:defaultConfig(t),editor:{x,y}};if(blockingActionFlowNodeTypes.has(t))n.timeoutPolicy={seconds:Number(f.policies.defaultTimeoutSeconds||300),onTimeout:'fault'};f.nodes.push(n);selectedNodeId.value=n.nodeId;f.revision+=1;commitFlows();};
const moveNode=(nodeId:string,x:number,y:number)=>{const n=currentFlow.value?.nodes.find(i=>i.nodeId===nodeId);if(!n)return;n.editor={...(n.editor||{x:0,y:0}),x:Math.round(x),y:Math.round(y)};commitFlows();};
const connectNodes=(source:string,target:string)=>{const f=currentFlow.value;if(!f||f.edges.some(e=>e.sourceNodeId===source&&e.targetNodeId===target))return;const s=f.nodes.find(n=>n.nodeId===source);let port='success';if(s?.type==='Condition'){const used=new Set(f.edges.filter(e=>e.sourceNodeId===source).map(e=>e.sourcePort));port=!used.has('true')?'true':'false';}f.edges.push({edgeId:id('edge'),sourceNodeId:source,sourcePort:port,targetNodeId:target});f.revision+=1;commitFlows();};
const updateNode=(node:TwinActionFlowNode)=>{const f=currentFlow.value;if(!f)return;const i=f.nodes.findIndex(x=>x.nodeId===node.nodeId);if(i>=0){f.nodes.splice(i,1,clonePlain(node));f.revision+=1;commitFlows();}};
const createNodeInterlock=()=>{const node=selectedNode.value;if(!node)return;const definition:TwinInterlockDefinition={interlockId:createOrchestrationId('interlock'),name:`${node.name||node.type} 联锁`,mode:'all',conditions:node.actorObjectId?[{source:`${node.actorObjectId}.ready`,operator:'truthy'}]:[]};node.config.interlockIds=[...new Set([...(Array.isArray(node.config.interlockIds)?node.config.interlockIds.map(String):[]),definition.interlockId])];currentFlow.value!.revision+=1;emit('create-interlock',clonePlain(definition));commitFlows();ElMessage.success('已新增节点联锁并自动关联当前节点。');};
const createNodeMaterialSlot=(configKey:string)=>{const node=selectedNode.value;if(!node)return;if(!node.actorObjectId){ElMessage.warning('请先为当前节点选择 Actor，再新增 MaterialSlot。');return;}const role=configKey==='sourceSlotId'?'source':configKey==='targetSlotId'?'target':'buffer';const definition:TwinMaterialSlotDefinition={slotId:createOrchestrationId('material-slot'),name:`${node.name||node.type} ${role==='source'?'来源':role==='target'?'目标':'缓存'}槽位`,objectId:node.actorObjectId,role,localPosition:[0,0,0],capacity:1};node.config[configKey]=definition.slotId;currentFlow.value!.revision+=1;emit('create-material-slot',clonePlain(definition));commitFlows();ElMessage.success('已新增 MaterialSlot 并自动关联当前节点。');};
const deleteNode=(nodeId:string)=>{const f=currentFlow.value;if(!f)return;f.nodes=f.nodes.filter(x=>x.nodeId!==nodeId);f.edges=f.edges.filter(e=>e.sourceNodeId!==nodeId&&e.targetNodeId!==nodeId);if(selectedNodeId.value===nodeId)selectedNodeId.value='';f.revision+=1;commitFlows();};
const setBreakpoint=(nodeId:string,enabled:boolean)=>{breakpoints.value=enabled?[...new Set([...breakpoints.value,nodeId])]:breakpoints.value.filter(x=>x!==nodeId);runtime?.setBreakpoint(nodeId,enabled);};
const locateDiagnostic=(d:TwinActionFlowDiagnostic)=>{if(d.nodeId)selectedNodeId.value=d.nodeId;};
const compileCurrent=()=>{const f=currentFlow.value;if(!f)return;try{const plan=compileActionFlow(clonePlain(f),{...props.manifest,actionFlows:localFlows.value});f.graphHash=plan.graphHash;f.compiledPlanHash=plan.compiledPlanHash;f.status='Validated';commitFlows();ElMessage.success('Action Flow V2 校验/编译通过，执行计划 Hash 已生成。');return plan;}catch(e){if(e instanceof ActionFlowCompileError)ElMessage.error(`流程存在 ${e.diagnostics.filter(x=>x.severity==='error').length} 个错误，请先处理诊断。`);else ElMessage.error(e instanceof Error?e.message:'编译失败');return undefined;}};
const refreshSnapshot=()=>{runtimeSnapshot.value=runtime?.getSnapshot();if(runtimeSnapshot.value&&['Completed','Faulted','Cancelled'].includes(runtimeSnapshot.value.state))stopTimer();};const startTimer=()=>{stopTimer();runtimeTimer=window.setInterval(()=>{runtime?.tick(.05);refreshSnapshot();},50);};const stopTimer=()=>{if(runtimeTimer!==undefined)window.clearInterval(runtimeTimer);runtimeTimer=undefined;};
const startSimulation=()=>{const plan=compileCurrent();if(!plan)return;runtime=new SimulationFlowRuntime(plan);for(const b of breakpoints.value)runtime.setBreakpoint(b,true);runtime.start();refreshSnapshot();startTimer();};const pauseSimulation=()=>{runtime?.pause();refreshSnapshot();};const resumeSimulation=()=>{runtime?.resume();refreshSnapshot();startTimer();};const stepSimulation=()=>{if(!runtime){startSimulation();runtime?.pause();}stopTimer();runtime?.step(.1);refreshSnapshot();};const stopSimulation=()=>{runtime?.cancel();refreshSnapshot();stopTimer();};const setSimulationSpeed=(v:number)=>{runtime?.setSpeed(v);refreshSnapshot();};const injectSignal=(key:string,value:unknown)=>{runtime?.setSignal(key,value);refreshSnapshot();};
const syncLiveDetail=()=>{liveRunDetail.value=liveRuntime?.getRunDetail();};
const disposeLiveClient=async()=>{const client=liveRuntime;liveRuntime=undefined;if(client)await client.dispose();liveRunDetail.value=undefined;};
const startLive=async()=>{const flow=currentFlow.value;if(!flow){return;}if(!props.sceneId||!props.publishedVersionId){ElMessage.error('Live 只能运行已经发布的数据库场景。');return;}if(props.publishedSourceRevision&&props.sceneRevision&&props.publishedSourceRevision!==props.sceneRevision){ElMessage.error('当前草稿在上次发布后已经修改，请先保存并重新发布，再启动 Live Run。');return;}const persisted=persistedCurrentFlow.value;if(!persisted){ElMessage.error('当前流程尚未保存到数据库，请先保存草稿并发布。');return;}const plan=compileCurrent();if(!plan)return;if(persisted.graphHash&&persisted.graphHash!==plan.graphHash){ElMessage.error('当前流程存在未保存修改，请先保存草稿并重新发布。');return;}await disposeLiveClient();liveRuntime=new LiveFlowRuntimeClient({persistedFlowId:persisted.id,semanticFlowId:flow.flowId,onChanged:(snapshot)=>{runtimeSnapshot.value=snapshot;syncLiveDetail();},onError:(error)=>ElMessage.error(error instanceof Error?error.message:'Live Run 实时连接失败')});try{await liveRuntime.start();runtimeSnapshot.value=liveRuntime.getSnapshot();syncLiveDetail();ElMessage.success('Live Run 已由服务端启动；设备命令和运行状态由服务端编排。');}catch(error){await disposeLiveClient();runtimeSnapshot.value=undefined;ElMessage.error(error instanceof Error?error.message:'Live Run 启动失败');}};
const setRuntimeMode=async(mode:RuntimeMode)=>{if(mode===runtimeMode.value)return;stopTimer();runtime=undefined;runtimeSnapshot.value=undefined;if(liveRuntime)await disposeLiveClient();runtimeMode.value=mode;};
const startRuntime=()=>runtimeMode.value==='live'?void startLive():startSimulation();
const pauseRuntime=async()=>{if(runtimeMode.value==='simulation'){pauseSimulation();return;}if(!liveRuntime)return;await liveRuntime.pause();runtimeSnapshot.value=liveRuntime.getSnapshot();syncLiveDetail();};
const resumeRuntime=async()=>{if(runtimeMode.value==='simulation'){resumeSimulation();return;}if(!liveRuntime)return;await liveRuntime.resume();runtimeSnapshot.value=liveRuntime.getSnapshot();syncLiveDetail();};
const stopRuntime=async()=>{if(runtimeMode.value==='simulation'){stopSimulation();return;}if(!liveRuntime)return;await liveRuntime.cancel('设计器操作员取消 Live Run');runtimeSnapshot.value=liveRuntime.getSnapshot();syncLiveDetail();};
const manualConfirmLive=async(stepInstanceId:string,reason:string)=>{if(!liveRuntime)return;await liveRuntime.manualConfirm(stepInstanceId,reason);runtimeSnapshot.value=liveRuntime.getSnapshot();syncLiveDetail();};
const retryLiveStep=async(stepInstanceId:string,reason:string)=>{if(!liveRuntime)return;await liveRuntime.retry(stepInstanceId,reason||'设计器人工重试');runtimeSnapshot.value=liveRuntime.getSnapshot();syncLiveDetail();};
watch(selectedFlowId,()=>{stopTimer();runtime=undefined;runtimeSnapshot.value=undefined;if(liveRuntime)void disposeLiveClient();});
onBeforeUnmount(()=>{document.removeEventListener('fullscreenchange',syncFullscreenState);stopTimer();void disposeLiveClient();});
</script>
<style scoped>
.af-designer{display:flex;flex-direction:column;min-height:0;height:100%;background:var(--el-bg-color-page);border:1px solid var(--el-border-color);border-radius:8px;overflow:hidden}.af-designer:fullscreen,.af-designer.is-fullscreen{width:100vw;height:100vh;max-width:none;max-height:none;border-radius:0}.af-toolbar{display:flex;flex:0 0 auto;align-items:center;justify-content:space-between;gap:10px;padding:8px 10px;border-bottom:1px solid var(--el-border-color);background:var(--el-bg-color)}.af-toolbar__left,.af-toolbar__right{display:flex;align-items:center;gap:6px;min-width:0}.af-main{display:flex;min-height:0;flex:1 1 auto;overflow:hidden}.af-center{display:flex;flex-direction:column;min-width:0;min-height:0;flex:1;overflow:hidden}.af-flow-meta{display:grid;flex:0 0 auto;grid-template-columns:1.5fr 1.2fr 140px 120px auto;gap:6px;padding:7px;background:var(--el-bg-color);border-bottom:1px solid var(--el-border-color)}.af-empty{flex:1;min-height:0}.af-designer :deep(.af-diagnostics),.af-designer :deep(.af-debugger){position:relative;z-index:2;flex:0 0 auto}.af-designer :deep(.af-diagnostics){max-height:150px;overflow:auto}.af-designer :deep(.af-debugger){max-height:210px;overflow:auto}@media(max-width:1300px){.af-flow-meta{grid-template-columns:1fr 1fr}.af-toolbar{align-items:flex-start;flex-direction:column}}
</style>
