import { booleanProperty, numberProperty, selectProperty, type TwinComponentBindingSlot, type TwinComponentTemplate } from './types';

const unitOptions = [
	{ label: '小托盘', value: 'plastic-pallet' },
	{ label: '木托盘', value: 'wooden-pallet' },
	{ label: '纸箱', value: 'carton' },
];

const smallUnitOptions = [
	{ label: '小托盘', value: 'plastic-pallet' },
];

const largeUnitOptions = [
	{ label: '木托盘', value: 'wooden-pallet' },
	{ label: '纸箱', value: 'carton' },
];

const occupancyOptions = [
	{ label: '计算', value: 'calculated' },
	{ label: '仿真', value: 'simulation' },
	{ label: '实时', value: 'live' },
];

const inputSlot = (
	slotId: string,
	name: string,
	dataType: TwinComponentBindingSlot['dataType'],
	semantic: TwinComponentBindingSlot['semantic'],
	description?: string,
): TwinComponentBindingSlot => ({ slotId, name, direction: 'input', dataType, semantic, description });

const externalInspectionSlots: TwinComponentBindingSlot[] = [
	inputSlot('ready', '设备就绪', 'bool', 'ready'),
	inputSlot('busy', '检测中', 'bool', 'busy'),
	inputSlot('complete', '检测完成', 'bool', 'complete'),
	inputSlot('result', '检测结果', 'string', 'result'),
	inputSlot('fault', '设备故障', 'bool', 'fault'),
	inputSlot('heartbeat', '设备心跳', 'bool', 'custom', '可选心跳信号'),
];
const baggingSlots: TwinComponentBindingSlot[] = [
	inputSlot('ready', '设备就绪', 'bool', 'ready'),
	inputSlot('busy', '套袋中', 'bool', 'busy'),
	inputSlot('complete', '套袋完成', 'bool', 'complete'),
	inputSlot('fault', '设备故障', 'bool', 'fault'),
	inputSlot('bagPresent', '包装袋到位', 'bool', 'sensor'),
];
const diverterSlots: TwinComponentBindingSlot[] = [
	inputSlot('routeCode', '目标路线码', 'string', 'route-code'),
	inputSlot('commandPosition', '命令位置', 'int', 'target-position'),
	inputSlot('actualPosition', '实际位置', 'int', 'actual-position'),
	inputSlot('inPosition', '执行器到位', 'bool', 'in-position'),
	inputSlot('fault', '设备故障', 'bool', 'fault'),
];
const liftSlots: TwinComponentBindingSlot[] = [
	inputSlot('ready', '设备就绪', 'bool', 'ready'),
	inputSlot('busy', '运行中', 'bool', 'busy'),
	inputSlot('targetFloor', '目标楼层', 'int', 'target-position'),
	inputSlot('currentFloor', '当前楼层', 'int', 'actual-position'),
	inputSlot('inPosition', '提升到位', 'bool', 'in-position'),
	inputSlot('fault', '设备故障', 'bool', 'fault'),
];
const turntableSlots: TwinComponentBindingSlot[] = [
	inputSlot('ready', '设备就绪', 'bool', 'ready'),
	inputSlot('busy', '旋转中', 'bool', 'busy'),
	inputSlot('commandAngle', '命令角度', 'float', 'target-position'),
	inputSlot('actualAngle', '实际角度', 'float', 'actual-position'),
	inputSlot('inPosition', '旋转到位', 'bool', 'in-position'),
	inputSlot('fault', '设备故障', 'bool', 'fault'),
];

const straightSchema = (sizeClass: 'small' | 'large') => [
	numberProperty('length', '长度', sizeClass === 'large' ? 4 : 3, 'geometry', { min: 0.5, max: 100, step: 0.1, unit: 'm' }),
	numberProperty('width', '宽度', sizeClass === 'large' ? 2.4 : 1.6, 'geometry', { min: 0.5, max: 8, step: 0.1, unit: 'm' }),
	numberProperty('height', '辊面高度', sizeClass === 'large' ? 0.82 : 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
	numberProperty('rollerDiameter', '滚筒直径', sizeClass === 'large' ? 0.18 : 0.14, 'geometry', { min: 0.05, max: 0.6, step: 0.01, unit: 'm' }),
	numberProperty('rollerPitch', '滚筒间距', sizeClass === 'large' ? 0.6 : 0.55, 'geometry', { min: 0.1, max: 2, step: 0.01, unit: 'm' }),
	numberProperty('supportSpacing', '支腿间距', 2, 'geometry', { min: 0.8, max: 8, step: 0.1, unit: 'm' }),
	numberProperty('capacity', '容量', sizeClass === 'large' ? 1 : 2, 'runtime', { min: 1, max: 999, step: 1 }),
	numberProperty('speedLimit', '速度上限', 1.2, 'runtime', { min: 0.01, max: 10, step: 0.05, unit: 'm/s' }),
	selectProperty('transportUnitType', '输送对象', sizeClass === 'large' ? 'wooden-pallet' : 'plastic-pallet', 'runtime', sizeClass === 'large' ? largeUnitOptions : smallUnitOptions),
	selectProperty('occupancyMode', '占用模式', 'simulation', 'runtime', occupancyOptions),
];

export const builtInComponentTemplates: TwinComponentTemplate[] = [
	{
		resourceKey: 'builtin-small-pallet',
		name: '小托盘',
		resourceType: 'procedural-component',
		componentType: 'pallet',
		generator: 'small-pallet-v1',
		generatorVersion: 1,
		category: 'transport-unit',
		tags: ['托盘', '小托盘', '绿色托盘', '丝锭托盘', '小辊道', '物流单元'],
		capabilities: ['transport-unit'],
		defaultProperties: { diameter: 1.48, baseHeight: 0.12, columnHeight: 0.92, columnDiameter: 0.48, routeManagedExternally: true },
		propertySchema: [
			numberProperty('diameter', '托盘直径', 1.48, 'geometry', { min: 0.8, max: 2.4, step: 0.02, unit: 'm' }),
			numberProperty('baseHeight', '底盘高度', 0.12, 'geometry', { min: 0.06, max: 0.3, step: 0.01, unit: 'm' }),
			numberProperty('columnHeight', '中心柱高度', 0.92, 'geometry', { min: 0.3, max: 1.5, step: 0.02, unit: 'm' }),
			numberProperty('columnDiameter', '中心柱直径', 0.48, 'geometry', { min: 0.18, max: 0.8, step: 0.02, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-plastic-pallet',
		name: '塑料母托盘',
		resourceType: 'procedural-component',
		componentType: 'pallet',
		generator: 'pallet-v1',
		generatorVersion: 1,
		category: 'transport-unit',
		tags: ['托盘', '塑料母托盘', '塑料托盘', '载具', '物流单元'],
		capabilities: ['transport-unit'],
		defaultProperties: { palletType: 'plastic-pallet', length: 1.2, width: 1.0, height: 0.16, routeManagedExternally: true },
		propertySchema: [
			numberProperty('length', '长度', 1.2, 'geometry', { min: 0.4, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('width', '宽度', 1.0, 'geometry', { min: 0.4, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('height', '高度', 0.16, 'geometry', { min: 0.06, max: 0.8, step: 0.01, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-carton',
		name: '纸箱',
		resourceType: 'procedural-component',
		componentType: 'carton',
		generator: 'carton-v1',
		generatorVersion: 1,
		category: 'transport-unit',
		tags: ['纸箱', '纸盒', '包装箱', '载具', '物流单元', '大辊道'],
		capabilities: ['transport-unit'],
		defaultProperties: { length: 1.2, width: 0.9, height: 0.8, routeManagedExternally: true },
		propertySchema: [
			numberProperty('length', '箱体长度', 1.2, 'geometry', { min: 0.2, max: 6, step: 0.05, unit: 'm' }),
			numberProperty('width', '箱体宽度', 0.9, 'geometry', { min: 0.2, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('height', '箱体高度', 0.8, 'geometry', { min: 0.15, max: 4, step: 0.05, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-wooden-pallet',
		name: '木托盘',
		resourceType: 'procedural-component',
		componentType: 'pallet',
		generator: 'pallet-v1',
		generatorVersion: 1,
		category: 'transport-unit',
		tags: ['托盘', '木托盘', '载具', '物流单元'],
		capabilities: ['transport-unit'],
		defaultProperties: { palletType: 'wooden-pallet', length: 1.2, width: 1.0, height: 0.16, routeManagedExternally: true },
		propertySchema: [
			numberProperty('length', '长度', 1.2, 'geometry', { min: 0.4, max: 8, step: 0.05, unit: 'm' }),
			numberProperty('width', '宽度', 1.0, 'geometry', { min: 0.4, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('height', '高度', 0.16, 'geometry', { min: 0.06, max: 0.8, step: 0.01, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-small-roller-conveyor',
		name: '标准小辊道',
		resourceType: 'procedural-component',
		componentType: 'roller-conveyor',
		generator: 'roller-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '小辊道', '小托盘', '塑料托盘'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: {
			length: 3,
			width: 1.6,
			height: 0.9,
			rollerDiameter: 0.14,
			rollerPitch: 0.55,
			frameHeight: 0.16,
			frameThickness: 0.1,
			supportSpacing: 2,
			conveyorSizeClass: 'small',
			transportUnitType: 'plastic-pallet',
			capacity: 2,
			speedLimit: 1.2,
			occupancyMode: 'simulation',
		},
		propertySchema: straightSchema('small'),
	},
	{
		resourceKey: 'builtin-chain-conveyor',
		name: '链式输送机',
		resourceType: 'procedural-component',
		componentType: 'chain-conveyor',
		generator: 'chain-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['链式输送机', '链条输送', '旋转台', '托盘输送'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: { length: 4, width: 1.6, height: 0.9, chainSpacing: 0.9, conveyorSizeClass: 'small', transportUnitType: 'plastic-pallet', capacity: 2, speedLimit: 1, occupancyMode: 'simulation' },
		propertySchema: [
			numberProperty('length', '长度', 4, 'geometry', { min: 0.8, max: 60, step: 0.1, unit: 'm' }),
			numberProperty('width', '宽度', 1.6, 'geometry', { min: 0.6, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('height', '链面高度', 0.9, 'geometry', { min: 0.25, max: 2.5, step: 0.05, unit: 'm' }),
			numberProperty('chainSpacing', '链条中心距', 0.9, 'geometry', { min: 0.25, max: 3, step: 0.05, unit: 'm' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 20, step: 1 }),
			numberProperty('speedLimit', '输送速度', 1, 'runtime', { min: 0.05, max: 5, step: 0.05, unit: 'm/s' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
			selectProperty('occupancyMode', '占用模式', 'simulation', 'runtime', occupancyOptions),
		],
	},
	{
		resourceKey: 'builtin-rgv-single',
		name: '单工位 RGV',
		resourceType: 'smart-model',
		componentType: 'rgv',
		generator: 'rgv-v1',
		generatorVersion: 1,
		category: 'transfer',
		tags: ['RGV', '单工位RGV', '轨道车', '移载'],
		capabilities: ['material-flow', 'plc-binding'],
		defaultProperties: { stationCount: 1, trackLength: 9, deckLength: 2.4, deckWidth: 1.6, height: 0.72, stationGap: 0.35, conveyorSizeClass: 'small', transportUnitType: 'plastic-pallet', travelSpeed: 2, transferSpeed: 0.8 },
		propertySchema: [
			numberProperty('trackLength', '轨道长度', 9, 'geometry', { min: 3, max: 40, step: 0.1, unit: 'm' }),
			numberProperty('deckLength', '载台长度', 2.4, 'geometry', { min: 1, max: 5, step: 0.05, unit: 'm' }),
			numberProperty('deckWidth', '载台宽度', 1.6, 'geometry', { min: 0.7, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('height', '载台高度', 0.72, 'geometry', { min: 0.25, max: 1.8, step: 0.05, unit: 'm' }),
			numberProperty('travelSpeed', '行走速度', 2, 'runtime', { min: 0.1, max: 8, step: 0.1, unit: 'm/s' }),
			numberProperty('transferSpeed', '载台输送速度', 0.8, 'runtime', { min: 0.05, max: 3, step: 0.05, unit: 'm/s' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-rgv-double',
		name: '双工位 RGV',
		resourceType: 'smart-model',
		componentType: 'rgv',
		generator: 'rgv-v1',
		generatorVersion: 1,
		category: 'transfer',
		tags: ['RGV', '双工位RGV', '双载台', '轨道车', '移载'],
		capabilities: ['material-flow', 'plc-binding'],
		defaultProperties: { stationCount: 2, trackLength: 11, deckLength: 2.4, deckWidth: 1.6, height: 0.72, stationGap: 0.35, conveyorSizeClass: 'small', transportUnitType: 'plastic-pallet', travelSpeed: 2, transferSpeed: 0.8 },
		propertySchema: [
			numberProperty('trackLength', '轨道长度', 11, 'geometry', { min: 4, max: 40, step: 0.1, unit: 'm' }),
			numberProperty('deckLength', '单工位长度', 2.4, 'geometry', { min: 1, max: 5, step: 0.05, unit: 'm' }),
			numberProperty('deckWidth', '载台宽度', 1.6, 'geometry', { min: 0.7, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('stationGap', '双工位间距', 0.35, 'geometry', { min: 0.1, max: 1.5, step: 0.05, unit: 'm' }),
			numberProperty('travelSpeed', '行走速度', 2, 'runtime', { min: 0.1, max: 8, step: 0.1, unit: 'm/s' }),
			numberProperty('transferSpeed', '载台输送速度', 0.8, 'runtime', { min: 0.05, max: 3, step: 0.05, unit: 'm/s' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-double-small-roller-conveyor',
		name: '双排小辊道',
		resourceType: 'procedural-component',
		componentType: 'double-small-roller-conveyor',
		generator: 'double-small-roller-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '小辊道', '双排小辊道', '双线', '并行输送', '塑料托盘'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: {
			length: 8,
			laneWidth: 1.6,
			laneSpacing: 1.9,
			height: 0.9,
			rollerDiameter: 0.14,
			rollerPitch: 0.55,
			frameHeight: 0.16,
			frameThickness: 0.1,
			supportSpacing: 2,
			capacityPerLane: 4,
			conveyorSizeClass: 'small',
			transportUnitType: 'plastic-pallet',
			speedLimit: 1.2,
			occupancyMode: 'simulation',
		},
		propertySchema: [
			numberProperty('length', '总长度', 8, 'geometry', { min: 0.5, max: 100, step: 0.1, unit: 'm' }),
			numberProperty('laneWidth', '单排宽度', 1.6, 'geometry', { min: 0.5, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('laneSpacing', '两排中心距', 1.9, 'geometry', { min: 0.6, max: 8, step: 0.05, unit: 'm', description: '小于单排宽度时会自动夹紧到不碰撞的最小中心距' }),
			numberProperty('height', '辊面高度', 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
			numberProperty('rollerDiameter', '滚筒直径', 0.14, 'geometry', { min: 0.05, max: 0.6, step: 0.01, unit: 'm' }),
			numberProperty('rollerPitch', '滚筒间距', 0.55, 'geometry', { min: 0.1, max: 2, step: 0.01, unit: 'm' }),
			numberProperty('supportSpacing', '支腿间距', 2, 'geometry', { min: 0.8, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('capacityPerLane', '每排容量', 4, 'runtime', { min: 1, max: 999, step: 1 }),
			numberProperty('speedLimit', '速度上限', 1.2, 'runtime', { min: 0.01, max: 10, step: 0.05, unit: 'm/s' }),
			selectProperty('occupancyMode', '占用模式', 'simulation', 'runtime', occupancyOptions),
		],
	},
	{
		resourceKey: 'builtin-large-roller-conveyor',
		name: '标准大辊道',
		resourceType: 'procedural-component',
		componentType: 'roller-conveyor',
		generator: 'roller-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '大辊道', '木托盘', '纸箱'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: {
			length: 4,
			width: 2.4,
			height: 0.82,
			rollerDiameter: 0.18,
			rollerPitch: 0.6,
			frameHeight: 0.18,
			frameThickness: 0.12,
			supportSpacing: 2.4,
			conveyorSizeClass: 'large',
			transportUnitType: 'wooden-pallet',
			capacity: 1,
			speedLimit: 0.8,
			occupancyMode: 'simulation',
		},
		propertySchema: straightSchema('large'),
	},
	{
		resourceKey: 'builtin-turn-conveyor-90',
		name: '90°转弯辊道',
		resourceType: 'procedural-component',
		componentType: 'turn-conveyor-90',
		generator: 'turn-conveyor-90-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '转弯', '90度'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: { radius: 2.2, width: 1.6, height: 0.9, rollerDiameter: 0.14, rollerPitch: 0.45, turnDirection: 'left', transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('radius', '转弯半径', 2.2, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('width', '宽度', 1.6, 'geometry', { min: 0.5, max: 6, step: 0.1, unit: 'm' }),
			numberProperty('height', '辊面高度', 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
			selectProperty('turnDirection', '转弯方向', 'left', 'geometry', [{ label: '左转', value: 'left' }, { label: '右转', value: 'right' }]),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
		],
	},
	{
		resourceKey: 'builtin-diverter-conveyor',
		name: '分流辊道',
		resourceType: 'smart-model',
		componentType: 'diverter-conveyor',
		generator: 'diverter-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '分流', '岔口', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'junction', 'plc-binding'],
		bindingSlots: diverterSlots,
		defaultProperties: { width: 1.6, height: 0.9, inputLength: 2.2, outputLength: 2.5, branchAngle: 35, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('inputLength', '入口长度', 2.2, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('outputLength', '出口长度', 2.5, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('branchAngle', '分流角度', 35, 'geometry', { min: 10, max: 80, step: 1, unit: '°' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-merger-conveyor',
		name: '汇流辊道',
		resourceType: 'smart-model',
		componentType: 'merger-conveyor',
		generator: 'merger-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '汇流'],
		capabilities: ['material-flow', 'capacity', 'merger'],
		defaultProperties: { width: 1.6, height: 0.9, inputLength: 2.5, outputLength: 2.2, branchAngle: 35, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('inputLength', '入口长度', 2.5, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('outputLength', '出口长度', 2.2, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('branchAngle', '汇流角度', 35, 'geometry', { min: 10, max: 80, step: 1, unit: '°' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-single-to-double-conveyor',
		name: '一分二小辊道',
		resourceType: 'smart-model',
		componentType: 'diverter-conveyor',
		generator: 'single-to-double-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '小辊道', '一分二', '单排转双排', '双排小辊道', '分流'],
		capabilities: ['material-flow', 'capacity', 'junction', 'plc-binding'],
		bindingSlots: diverterSlots,
		defaultProperties: { laneWidth: 1.6, laneSpacing: 1.9, height: 0.9, transitionLength: 2.8, singleStubLength: 1.6, doubleStubLength: 1.4, rollerDiameter: 0.14, rollerPitch: 0.45, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('laneWidth', '小辊道宽度', 1.6, 'geometry', { min: 0.5, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('laneSpacing', '双排中心距', 1.9, 'geometry', { min: 0.6, max: 8, step: 0.05, unit: 'm', description: '必须与目标双排小辊道 laneSpacing 一致；分流角度由该中心距自动计算。' }),
			numberProperty('transitionLength', '分流过渡长度', 2.8, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm', description: '与双排中心距共同决定分流角度。' }),
			numberProperty('singleStubLength', '单排直线段长度', 1.6, 'geometry', { min: 0.5, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('doubleStubLength', '双排对接直线段长度', 1.4, 'geometry', { min: 0.5, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('height', '辊面高度', 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', smallUnitOptions),
		],
	},
	{
		resourceKey: 'builtin-double-to-single-conveyor',
		name: '二合一小辊道',
		resourceType: 'smart-model',
		componentType: 'merger-conveyor',
		generator: 'double-to-single-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '小辊道', '二合一', '双排转单排', '双排小辊道', '汇流', '中心汇流'],
		capabilities: ['material-flow', 'capacity', 'merger'],
		defaultProperties: { laneWidth: 1.6, laneSpacing: 1.9, height: 0.9, transitionLength: 2.8, singleStubLength: 1.6, doubleStubLength: 1.4, rollerDiameter: 0.14, rollerPitch: 0.45, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('laneWidth', '小辊道宽度', 1.6, 'geometry', { min: 0.5, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('laneSpacing', '双排中心距', 1.9, 'geometry', { min: 0.6, max: 8, step: 0.05, unit: 'm', description: '必须与来源双排小辊道 laneSpacing 一致；两路会关于中心线对称汇流。' }),
			numberProperty('transitionLength', '汇流过渡长度', 2.8, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm', description: '与双排中心距共同决定汇流角度。' }),
			numberProperty('singleStubLength', '单排直线段长度', 1.6, 'geometry', { min: 0.5, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('doubleStubLength', '双排对接直线段长度', 1.4, 'geometry', { min: 0.5, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('height', '辊面高度', 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', smallUnitOptions),
		],
	},
	{
		resourceKey: 'builtin-right-angle-single-to-double-conveyor',
		name: '直角一分二小辊道',
		resourceType: 'smart-model',
		componentType: 'diverter-conveyor',
		generator: 'right-angle-single-to-double-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '小辊道', '直角', '一分二', '单排转双排', '双排小辊道', '分流'],
		capabilities: ['material-flow', 'capacity', 'junction', 'plc-binding'],
		bindingSlots: diverterSlots,
		defaultProperties: { laneWidth: 1.6, laneSpacing: 1.9, height: 0.9, inputStubLength: 2.2, outputStubLength: 2.6, rollerDiameter: 0.14, rollerPitch: 0.45, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('laneWidth', '小辊道宽度', 1.6, 'geometry', { min: 0.5, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('laneSpacing', '双排中心距', 1.9, 'geometry', { min: 0.6, max: 8, step: 0.05, unit: 'm', description: '右侧两个出口中心距，必须与目标双排小辊道 laneSpacing 一致。' }),
			numberProperty('inputStubLength', '上方单排入口段长度', 2.2, 'geometry', { min: 0.6, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('outputStubLength', '右侧双排出口段长度', 2.6, 'geometry', { min: 0.6, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('height', '辊面高度', 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', smallUnitOptions),
		],
	},
	{
		resourceKey: 'builtin-right-angle-double-to-single-conveyor',
		name: '直角二合一小辊道',
		resourceType: 'smart-model',
		componentType: 'merger-conveyor',
		generator: 'right-angle-double-to-single-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '小辊道', '直角', '二合一', '双排转单排', '双排小辊道', '汇流'],
		capabilities: ['material-flow', 'capacity', 'merger'],
		defaultProperties: { laneWidth: 1.6, laneSpacing: 1.9, height: 0.9, inputStubLength: 2.2, outputStubLength: 2.6, rollerDiameter: 0.14, rollerPitch: 0.45, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('laneWidth', '小辊道宽度', 1.6, 'geometry', { min: 0.5, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('laneSpacing', '双排中心距', 1.9, 'geometry', { min: 0.6, max: 8, step: 0.05, unit: 'm', description: '左侧两个入口中心距，必须与来源双排小辊道 laneSpacing 一致。' }),
			numberProperty('inputStubLength', '左侧双排入口段长度', 2.2, 'geometry', { min: 0.6, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('outputStubLength', '上方单排出口段长度', 2.6, 'geometry', { min: 0.6, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('height', '辊面高度', 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', smallUnitOptions),
		],
	},
	{
		resourceKey: 'builtin-lift',
		name: '标准提升机',
		resourceType: 'smart-model',
		componentType: 'lift',
		generator: 'lift-v1',
		generatorVersion: 1,
		category: 'transfer',
		tags: ['提升机', '垂直输送', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'vertical-transfer', 'plc-binding'],
		bindingSlots: liftSlots,
		defaultProperties: { platformLength: 2.2, width: 1.8, baseHeight: 0.9, liftHeight: 4, transportUnitType: 'plastic-pallet', capacity: 1 },
		propertySchema: [
			numberProperty('platformLength', '平台长度', 2.2, 'geometry', { min: 0.8, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('width', '平台宽度', 1.8, 'geometry', { min: 0.6, max: 6, step: 0.1, unit: 'm' }),
			numberProperty('liftHeight', '提升高度', 4, 'geometry', { min: 0.5, max: 30, step: 0.1, unit: 'm' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
			numberProperty('capacity', '容量', 1, 'runtime', { min: 1, max: 10, step: 1 }),
		],
	},
	{
		resourceKey: 'builtin-turntable',
		name: '标准旋转台',
		resourceType: 'smart-model',
		componentType: 'turntable',
		generator: 'turntable-v1',
		generatorVersion: 1,
		category: 'transfer',
		tags: ['旋转台', '转台', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'rotation', 'plc-binding'],
		bindingSlots: turntableSlots,
		defaultProperties: { deckLength: 2.4, width: 1.8, height: 0.9, baseRadius: 1.55, transportUnitType: 'plastic-pallet', capacity: 1, rotationDegrees: 180, withSilkCart: false, silkCartLoaded: true },
		propertySchema: [
			numberProperty('deckLength', '辊道长度', 2.4, 'geometry', { min: 0.8, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('width', '辊道宽度', 1.8, 'geometry', { min: 0.6, max: 6, step: 0.1, unit: 'm' }),
			numberProperty('rotationDegrees', '旋转角度', 180, 'runtime', { min: 0, max: 360, step: 1, unit: '°' }),
			booleanProperty('withSilkCart', '带双面丝车', false, 'geometry'),
			booleanProperty('silkCartLoaded', '丝车预装丝锭', true, 'geometry'),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-external-inspection',
		name: '化纤外检机',
		resourceType: 'smart-model',
		componentType: 'external-inspection',
		generator: 'external-inspection-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['化纤', '丝饼', '外检', '视觉检测', '360°检测', '工艺设备', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'process-station', 'plc-binding', 'vision-inspection'],
		bindingSlots: externalInspectionSlots,
		defaultProperties: { length: 4.5, width: 2.8, machineHeight: 3.0, conveyorHeight: 0.9, conveyorWidth: 1.6, chamberLength: 2.6, withRotaryInspection: true, cycleSeconds: 2, capacity: 1, transportUnitType: 'plastic-pallet' },
		propertySchema: [
			numberProperty('length', '设备总长度', 4.5, 'geometry', { min: 3.2, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('width', '检测舱宽度', 2.8, 'geometry', { min: 2, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('machineHeight', '检测舱高度', 3.0, 'geometry', { min: 2.2, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('conveyorWidth', '内置辊道宽度', 1.6, 'geometry', { min: 0.8, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('chamberLength', '暗室检测段长度', 2.6, 'geometry', { min: 1.6, max: 8, step: 0.1, unit: 'm' }),
			booleanProperty('withRotaryInspection', '顶部旋转检测夹具', true, 'geometry'),
			numberProperty('cycleSeconds', '单托检测节拍', 2, 'process', { min: 0.1, max: 300, step: 0.1, unit: 's' }),
			numberProperty('capacity', '检测位容量', 1, 'runtime', { min: 1, max: 10, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-external-inspection-dual',
		name: '双工位化纤外检机',
		resourceType: 'smart-model',
		componentType: 'external-inspection',
		generator: 'external-inspection-dual-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['化纤', '丝饼', '双工位', '外检', '视觉检测', '360°检测', '工艺设备', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'process-station', 'plc-binding', 'vision-inspection', 'dual-lane'],
		bindingSlots: externalInspectionSlots,
		defaultProperties: { length: 6.2, width: 2.8, machineHeight: 3.1, conveyorHeight: 0.9, conveyorWidth: 1.6, stationSpacing: 2.0, chamberLength: 5.0, withRotaryInspection: true, cycleSeconds: 2, capacity: 2, transportUnitType: 'plastic-pallet' },
		propertySchema: [
			numberProperty('length', '设备总长度', 6.2, 'geometry', { min: 4.8, max: 14, step: 0.1, unit: 'm' }),
			numberProperty('width', '检测舱宽度', 2.8, 'geometry', { min: 2, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('machineHeight', '检测舱高度', 3.1, 'geometry', { min: 2.2, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('conveyorWidth', '小辊道宽度', 1.6, 'geometry', { min: 0.8, max: 2.4, step: 0.05, unit: 'm' }),
			numberProperty('stationSpacing', '两个检测位中心距', 2.0, 'geometry', { min: 1.2, max: 4.5, step: 0.05, unit: 'm' }),
			numberProperty('chamberLength', '暗室检测段长度', 5.0, 'geometry', { min: 3.4, max: 10, step: 0.1, unit: 'm' }),
			booleanProperty('withRotaryInspection', '双顶部旋转检测夹具', true, 'geometry'),
			numberProperty('cycleSeconds', '双托并行检测节拍', 2, 'process', { min: 0.1, max: 300, step: 0.1, unit: 's' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},

	{
		resourceKey: 'builtin-bagging-machine',
		name: '化纤侧封膜机',
		resourceType: 'smart-model',
		componentType: 'bagging-machine',
		generator: 'bagging-machine-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['化纤', '丝饼', '侧封膜', '连续膜', '纵向侧封', '切膜', '工艺设备', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'process-station', 'plc-binding', 'continuous-film-feed', 'side-seal', 'film-cut'],
		bindingSlots: baggingSlots,
		defaultProperties: { length: 5.2, width: 2.8, machineHeight: 3.2, conveyorHeight: 0.9, conveyorWidth: 1.6, filmWrapWidth: 1.5, filmWrapDepth: 1.45, filmRollDiameter: 0.55, cycleSeconds: 3, capacity: 1, transportUnitType: 'plastic-pallet', showBagFilm: true },
		propertySchema: [
			numberProperty('length', '设备总长度', 5.2, 'geometry', { min: 3.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('width', '机架总宽度', 2.8, 'geometry', { min: 2.1, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('machineHeight', '设备高度', 3.2, 'geometry', { min: 2.4, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('conveyorWidth', '内置小辊道宽度', 1.6, 'geometry', { min: 0.8, max: 4, step: 0.05, unit: 'm' }),
			numberProperty('filmWrapWidth', '侧封膜包覆直径', 1.5, 'geometry', { min: 0.9, max: 2.8, step: 0.05, unit: 'm' }),
			numberProperty('filmWrapDepth', '连续膜包覆高度', 1.45, 'geometry', { min: 0.9, max: 3.0, step: 0.05, unit: 'm' }),
			numberProperty('filmRollDiameter', '膜卷直径', 0.55, 'geometry', { min: 0.25, max: 1.2, step: 0.05, unit: 'm' }),
			booleanProperty('showBagFilm', '显示包覆薄膜', true, 'geometry'),
			numberProperty('cycleSeconds', '侧封膜节拍', 3, 'process', { min: 0.1, max: 300, step: 0.1, unit: 's' }),
			numberProperty('capacity', '工位容量', 1, 'runtime', { min: 1, max: 10, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', [{ label: '小托盘', value: 'plastic-pallet' }]),
		],
	},
	{
		resourceKey: 'builtin-vacuum-film-tuck-station',
		name: '化纤真空吸膜工位',
		resourceType: 'smart-model',
		componentType: 'bagging-machine',
		generator: 'vacuum-film-tuck-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['化纤', '丝饼', '吸膜', '真空整形', '套膜后处理', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'process-station', 'plc-binding', 'vacuum-film-tuck'],
		bindingSlots: baggingSlots,
		defaultProperties: { length: 3.2, width: 2.4, machineHeight: 2.9, conveyorHeight: 0.9, conveyorWidth: 1.6, liftStroke: 0.95, coreDiameter: 0.22, cycleSeconds: 2, capacity: 1, transportUnitType: 'plastic-pallet' },
		propertySchema: [
			numberProperty('length', '工位总长度', 3.2, 'geometry', { min: 2.2, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('width', '工位总宽度', 2.4, 'geometry', { min: 1.8, max: 6, step: 0.1, unit: 'm' }),
			numberProperty('machineHeight', '工位高度', 2.9, 'geometry', { min: 2, max: 5.5, step: 0.1, unit: 'm' }),
			numberProperty('conveyorWidth', '小辊道宽度', 1.6, 'geometry', { min: 0.8, max: 3, step: 0.05, unit: 'm' }),
			numberProperty('liftStroke', '丝饼提升行程', 0.95, 'geometry', { min: 0.45, max: 1.8, step: 0.05, unit: 'm' }),
			numberProperty('coreDiameter', '纸管内孔夹持直径', 0.22, 'geometry', { min: 0.1, max: 0.5, step: 0.01, unit: 'm' }),
			numberProperty('cycleSeconds', '吸膜整形节拍', 2, 'process', { min: 0.1, max: 60, step: 0.1, unit: 's' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-industrial-robot',
		name: '六轴工业机器人',
		resourceType: 'smart-model',
		componentType: 'industrial-robot',
		generator: 'industrial-robot-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['机器人', '六轴机器人', '搬运', '码垛', 'PLC'],
		capabilities: ['plc-binding'],
		defaultProperties: { pedestalRadius: 0.72, upperArmLength: 1.65, forearmLength: 1.45, toolType: 'pallet-gripper', gripperSpan: 6.2, gripperRowSpacing: 1.15 },
		propertySchema: [
			numberProperty('pedestalRadius', '底座半径', 0.72, 'geometry', { min: 0.35, max: 1.5, step: 0.05, unit: 'm' }),
			numberProperty('upperArmLength', '大臂长度', 1.65, 'geometry', { min: 0.7, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('forearmLength', '小臂长度', 1.45, 'geometry', { min: 0.7, max: 3.5, step: 0.05, unit: 'm' }),
			selectProperty('toolType', '末端夹具', 'pallet-gripper', 'geometry', [
				{ label: '普通搬运夹具', value: 'pallet-gripper' },
				{ label: '纸箱夹具', value: 'carton-gripper' },
				{ label: '1×6 丝锭夹具', value: 'silk-row-1x6' },
				{ label: '2×6 丝锭夹具', value: 'silk-grid-2x6' },
			]),
			numberProperty('gripperSpan', '丝锭夹具横向跨度', 6.2, 'geometry', { min: 2.5, max: 9, step: 0.1, unit: 'm' }),
			numberProperty('gripperRowSpacing', '2×6夹具排距', 1.15, 'geometry', { min: 0.5, max: 2.5, step: 0.05, unit: 'm' }),
			numberProperty('cartonGripWidth', '纸箱夹持宽度', 1.6, 'geometry', { min: 0.5, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('cartonGripDepth', '纸箱夹具深度', 1.2, 'geometry', { min: 0.4, max: 3, step: 0.05, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-carton-palletizing-robot',
		name: '码垛纸箱机器人',
		resourceType: 'smart-model',
		componentType: 'industrial-robot',
		generator: 'industrial-robot-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['机器人', '码垛机器人', '纸箱', '纸箱夹具', 'PLC'],
		capabilities: ['plc-binding'],
		defaultProperties: { pedestalRadius: 0.72, upperArmLength: 1.8, forearmLength: 1.6, toolType: 'carton-gripper', cartonGripWidth: 1.6, cartonGripDepth: 1.2 },
		propertySchema: [
			numberProperty('pedestalRadius', '底座半径', 0.72, 'geometry', { min: 0.35, max: 1.5, step: 0.05, unit: 'm' }),
			numberProperty('upperArmLength', '大臂长度', 1.8, 'geometry', { min: 0.7, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('forearmLength', '小臂长度', 1.6, 'geometry', { min: 0.7, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('cartonGripWidth', '纸箱夹持宽度', 1.6, 'geometry', { min: 0.5, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('cartonGripDepth', '纸箱夹具深度', 1.2, 'geometry', { min: 0.4, max: 3, step: 0.05, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-silk-gantry',
		name: '丝锭桁架',
		resourceType: 'smart-model',
		componentType: 'silk-gantry',
		generator: 'silk-gantry-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['包装线设备', '丝锭桁架', '码垛桁架', '双轨双夹具', '隔板夹具'],
		capabilities: [],
		defaultProperties: { length: 8.2, width: 27.0, height: 8.4 },
		propertySchema: [
			numberProperty('length', 'X向桁架跨度', 8.2, 'geometry', { min: 4, max: 30, step: 0.1, unit: 'm' }),
			numberProperty('width', 'Z向轨道长度', 27.0, 'geometry', { min: 8, max: 36, step: 0.1, unit: 'm' }),
			numberProperty('height', '桁架高度', 8.4, 'geometry', { min: 3, max: 15, step: 0.1, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-top-cover-gantry',
		name: '天盖桁架',
		resourceType: 'smart-model',
		componentType: 'top-cover-gantry',
		generator: 'top-cover-gantry-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['包装线设备', '天盖桁架', 'Z向双轨桁架', '天盖夹具', '天盖暂存台'],
		capabilities: [],
		defaultProperties: { length: 7.05, width: 10.5, height: 6.0 },
		propertySchema: [
			numberProperty('length', 'X向桁架跨度', 7.05, 'geometry', { min: 3, max: 20, step: 0.1, unit: 'm' }),
			numberProperty('width', 'Z向轨道长度', 10.5, 'geometry', { min: 5.7, max: 20, step: 0.1, unit: 'm' }),
			numberProperty('height', '桁架高度', 6.0, 'geometry', { min: 2.5, max: 12, step: 0.1, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-wrapper-machine',
		name: '缠膜机',
		resourceType: 'smart-model',
		componentType: 'wrapper-machine',
		generator: 'wrapper-machine-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['包装线设备', '悬臂缠膜机', '旋臂缠膜机', '预拉伸膜架', '后包装'],
		capabilities: ['process-station'],
		defaultProperties: { height: 6.2, width: 6.8, armRadius: 3.0 },
		propertySchema: [
			numberProperty('height', '设备高度', 6.2, 'geometry', { min: 3.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('width', '固定门架跨度', 6.8, 'geometry', { min: 4.2, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('armRadius', '悬臂回转半径', 3.0, 'geometry', { min: 1.8, max: 5.5, step: 0.05, unit: 'm' }),
		],
	},
	{
		resourceKey: 'builtin-labeling-machine',
		name: '贴标机',
		resourceType: 'smart-model',
		componentType: 'labeling-machine',
		generator: 'labeling-machine-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['包装线设备', '贴标机', '标签', '后包装'],
		capabilities: ['process-station'],
		defaultProperties: { height: 2.4, sideOffset: 1.85, armReach: 0.6 },
		propertySchema: [
			numberProperty('height', '贴标中心高度', 2.4, 'geometry', { min: 1.4, max: 4.5, step: 0.05, unit: 'm' }),
			numberProperty('sideOffset', '机身距输送线中心', 1.85, 'geometry', { min: 1.2, max: 3.5, step: 0.05, unit: 'm' }),
			numberProperty('armReach', '三关节臂最大伸出', 0.6, 'geometry', { min: 0.35, max: 1.2, step: 0.05, unit: 'm' }),
		],
	},
];

export const getBuiltInComponentTemplate = (resourceKey: string) => builtInComponentTemplates.find((item) => item.resourceKey === resourceKey);
