import { booleanProperty, numberProperty, selectProperty, type TwinComponentTemplate } from './types';

const unitOptions = [
	{ label: '塑料托盘', value: 'plastic-pallet' },
	{ label: '木托盘', value: 'wooden-pallet' },
	{ label: '纸箱', value: 'carton' },
];

const smallUnitOptions = [
	{ label: '塑料托盘', value: 'plastic-pallet' },
	{ label: '纸箱', value: 'carton' },
];

const largeUnitOptions = [
	{ label: '木托盘', value: 'wooden-pallet' },
	{ label: '纸箱', value: 'carton' },
];

const occupancyOptions = [
	{ label: '计算', value: 'calculated' },
	{ label: '仿真', value: 'simulation' },
	{ label: '实时', value: 'live' },
];

const straightSchema = (sizeClass: 'small' | 'large') => [
	numberProperty('length', '长度', sizeClass === 'large' ? 4 : 3, 'geometry', { min: 0.5, max: 100, step: 0.1, unit: 'm' }),
	numberProperty('width', '宽度', sizeClass === 'large' ? 2.4 : 1.6, 'geometry', { min: 0.5, max: 8, step: 0.1, unit: 'm' }),
	numberProperty('height', '辊面高度', sizeClass === 'large' ? 0.82 : 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
	numberProperty('rollerDiameter', '滚筒直径', sizeClass === 'large' ? 0.18 : 0.14, 'geometry', { min: 0.05, max: 0.6, step: 0.01, unit: 'm' }),
	numberProperty('rollerPitch', '滚筒间距', sizeClass === 'large' ? 0.6 : 0.55, 'geometry', { min: 0.1, max: 2, step: 0.01, unit: 'm' }),
	numberProperty('supportSpacing', '支腿间距', 2, 'geometry', { min: 0.8, max: 8, step: 0.1, unit: 'm' }),
	numberProperty('capacity', '容量', sizeClass === 'large' ? 1 : 2, 'runtime', { min: 1, max: 999, step: 1 }),
	numberProperty('speedLimit', '速度上限', 1.2, 'runtime', { min: 0.01, max: 10, step: 0.05, unit: 'm/s' }),
	selectProperty('transportUnitType', '输送对象', sizeClass === 'large' ? 'wooden-pallet' : 'plastic-pallet', 'runtime', sizeClass === 'large' ? largeUnitOptions : smallUnitOptions),
	selectProperty('occupancyMode', '占用模式', 'simulation', 'runtime', occupancyOptions),
];

export const builtInComponentTemplates: TwinComponentTemplate[] = [
	{
		resourceKey: 'builtin-small-roller-conveyor',
		name: '标准小辊道',
		resourceType: 'procedural-component',
		componentType: 'roller-conveyor',
		generator: 'roller-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '小辊道', '塑料托盘', '纸箱'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: {
			length: 3,
			width: 1.6,
			height: 0.9,
			rollerDiameter: 0.14,
			rollerPitch: 0.55,
			frameHeight: 0.16,
			frameThickness: 0.1,
			supportSpacing: 2,
			conveyorSizeClass: 'small',
			transportUnitType: 'plastic-pallet',
			capacity: 2,
			speedLimit: 1.2,
			occupancyMode: 'simulation',
		},
		propertySchema: straightSchema('small'),
	},
	{
		resourceKey: 'builtin-large-roller-conveyor',
		name: '标准大辊道',
		resourceType: 'procedural-component',
		componentType: 'roller-conveyor',
		generator: 'roller-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '大辊道', '木托盘', '纸箱'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: {
			length: 4,
			width: 2.4,
			height: 0.82,
			rollerDiameter: 0.18,
			rollerPitch: 0.6,
			frameHeight: 0.18,
			frameThickness: 0.12,
			supportSpacing: 2.4,
			conveyorSizeClass: 'large',
			transportUnitType: 'wooden-pallet',
			capacity: 1,
			speedLimit: 0.8,
			occupancyMode: 'simulation',
		},
		propertySchema: straightSchema('large'),
	},
	{
		resourceKey: 'builtin-turn-conveyor-90',
		name: '90°转弯辊道',
		resourceType: 'procedural-component',
		componentType: 'turn-conveyor-90',
		generator: 'turn-conveyor-90-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '转弯', '90度'],
		capabilities: ['material-flow', 'capacity'],
		defaultProperties: { radius: 2.2, width: 1.6, height: 0.9, rollerDiameter: 0.14, rollerPitch: 0.45, turnDirection: 'left', transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('radius', '转弯半径', 2.2, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('width', '宽度', 1.6, 'geometry', { min: 0.5, max: 6, step: 0.1, unit: 'm' }),
			numberProperty('height', '辊面高度', 0.9, 'geometry', { min: 0.2, max: 3, step: 0.05, unit: 'm' }),
			selectProperty('turnDirection', '转弯方向', 'left', 'geometry', [{ label: '左转', value: 'left' }, { label: '右转', value: 'right' }]),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
		],
	},
	{
		resourceKey: 'builtin-diverter-conveyor',
		name: '分流辊道',
		resourceType: 'smart-model',
		componentType: 'diverter-conveyor',
		generator: 'diverter-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '分流', '岔口', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'junction', 'plc-binding'],
		defaultProperties: { width: 1.6, height: 0.9, inputLength: 2.2, outputLength: 2.5, branchAngle: 35, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('inputLength', '入口长度', 2.2, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('outputLength', '出口长度', 2.5, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('branchAngle', '分流角度', 35, 'geometry', { min: 10, max: 80, step: 1, unit: '°' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-merger-conveyor',
		name: '汇流辊道',
		resourceType: 'smart-model',
		componentType: 'merger-conveyor',
		generator: 'merger-conveyor-v1',
		generatorVersion: 1,
		category: 'conveyor',
		tags: ['辊道', '汇流'],
		capabilities: ['material-flow', 'capacity', 'merger'],
		defaultProperties: { width: 1.6, height: 0.9, inputLength: 2.5, outputLength: 2.2, branchAngle: 35, transportUnitType: 'plastic-pallet', capacity: 2 },
		propertySchema: [
			numberProperty('inputLength', '入口长度', 2.5, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('outputLength', '出口长度', 2.2, 'geometry', { min: 0.8, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('branchAngle', '汇流角度', 35, 'geometry', { min: 10, max: 80, step: 1, unit: '°' }),
			numberProperty('capacity', '容量', 2, 'runtime', { min: 1, max: 999, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-lift',
		name: '标准提升机',
		resourceType: 'smart-model',
		componentType: 'lift',
		generator: 'lift-v1',
		generatorVersion: 1,
		category: 'transfer',
		tags: ['提升机', '垂直输送', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'vertical-transfer', 'plc-binding'],
		defaultProperties: { platformLength: 2.2, width: 1.8, baseHeight: 0.9, liftHeight: 4, transportUnitType: 'plastic-pallet', capacity: 1 },
		propertySchema: [
			numberProperty('platformLength', '平台长度', 2.2, 'geometry', { min: 0.8, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('width', '平台宽度', 1.8, 'geometry', { min: 0.6, max: 6, step: 0.1, unit: 'm' }),
			numberProperty('liftHeight', '提升高度', 4, 'geometry', { min: 0.5, max: 30, step: 0.1, unit: 'm' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
			numberProperty('capacity', '容量', 1, 'runtime', { min: 1, max: 10, step: 1 }),
		],
	},
	{
		resourceKey: 'builtin-turntable',
		name: '标准旋转台',
		resourceType: 'smart-model',
		componentType: 'turntable',
		generator: 'turntable-v1',
		generatorVersion: 1,
		category: 'transfer',
		tags: ['旋转台', '转台', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'rotation', 'plc-binding'],
		defaultProperties: { deckLength: 2.4, width: 1.8, height: 0.9, baseRadius: 1.55, transportUnitType: 'plastic-pallet', capacity: 1, rotationDegrees: 180 },
		propertySchema: [
			numberProperty('deckLength', '辊道长度', 2.4, 'geometry', { min: 0.8, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('width', '辊道宽度', 1.8, 'geometry', { min: 0.6, max: 6, step: 0.1, unit: 'm' }),
			numberProperty('rotationDegrees', '旋转角度', 180, 'runtime', { min: 0, max: 360, step: 1, unit: '°' }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-external-inspection',
		name: '外检机',
		resourceType: 'smart-model',
		componentType: 'external-inspection',
		generator: 'external-inspection-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['外检', '视觉检测', '工艺设备', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'process-station', 'plc-binding'],
		defaultProperties: { length: 4, width: 3, machineHeight: 3.2, conveyorHeight: 0.9, conveyorWidth: 1.6, cycleSeconds: 2, capacity: 1, transportUnitType: 'plastic-pallet' },
		propertySchema: [
			numberProperty('length', '设备长度', 4, 'geometry', { min: 2, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('width', '设备宽度', 3, 'geometry', { min: 1.2, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('machineHeight', '设备高度', 3.2, 'geometry', { min: 1.5, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('cycleSeconds', '检测节拍', 2, 'process', { min: 0.1, max: 300, step: 0.1, unit: 's' }),
			numberProperty('capacity', '容量', 1, 'runtime', { min: 1, max: 10, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
		],
	},
	{
		resourceKey: 'builtin-bagging-machine',
		name: '套袋机',
		resourceType: 'smart-model',
		componentType: 'bagging-machine',
		generator: 'bagging-machine-v1',
		generatorVersion: 1,
		category: 'process',
		tags: ['套袋', '工艺设备', 'PLC'],
		capabilities: ['material-flow', 'capacity', 'process-station', 'plc-binding'],
		defaultProperties: { length: 4, width: 3, machineHeight: 3.4, conveyorHeight: 0.9, conveyorWidth: 1.6, cycleSeconds: 3, capacity: 1, transportUnitType: 'plastic-pallet', showBagFilm: true },
		propertySchema: [
			numberProperty('length', '设备长度', 4, 'geometry', { min: 2, max: 12, step: 0.1, unit: 'm' }),
			numberProperty('width', '设备宽度', 3, 'geometry', { min: 1.2, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('machineHeight', '设备高度', 3.4, 'geometry', { min: 1.5, max: 8, step: 0.1, unit: 'm' }),
			numberProperty('cycleSeconds', '套袋节拍', 3, 'process', { min: 0.1, max: 300, step: 0.1, unit: 's' }),
			numberProperty('capacity', '容量', 1, 'runtime', { min: 1, max: 10, step: 1 }),
			selectProperty('transportUnitType', '输送对象', 'plastic-pallet', 'runtime', unitOptions),
			booleanProperty('showBagFilm', '显示袋膜', true, 'geometry'),
		],
	},
];

export const getBuiltInComponentTemplate = (resourceKey: string) => builtInComponentTemplates.find((item) => item.resourceKey === resourceKey);
