import {
	createBlankTwinSceneManifest,
	type TwinRouteDefinition,
	type TwinRouteEdgeDefinition,
	type TwinRoutePointDefinition,
	type TwinSceneManifest,
} from '../contracts';
import type { TwinV7SceneObjectDefinition } from '../contracts/v7-components';
import { getBuiltInComponentTemplate } from '../components/BuiltInComponentCatalog';
import { areComponentPortsCompatible, resolveComponentPorts, upsertGeneratedComponentRoutes } from '../components/ComponentConnectionEngine';
import referencePackagingSceneV19 from './reference-packaging-v19.scene.json';

const SMALL_HEIGHT = 0.9;
const LARGE_HEIGHT = 0.82;
// 用户图纸的平面 Y 轴对应 Three.js 地面坐标 Z；大辊道固定在 X=-15.7 并沿 -Z 运行。
const LARGE_LINE_X = -19.0;
const LARGE_LINE_ROTATION_Y = Math.PI / 2;
export const REFERENCE_PACKAGING_LAYOUT_VERSION = 19;

const componentObject = (
	resourceKey: string,
	objectId: string,
	name: string,
	position: [number, number, number],
	rotationY = 0,
	properties: Record<string, unknown> = {},
	sectionId?: string,
): TwinV7SceneObjectDefinition => {
	const template = getBuiltInComponentTemplate(resourceKey);
	if (!template) throw new Error(`参考图产线缺少组件模板：${resourceKey}`);
	return {
		objectId,
		name,
		kind: 'component',
		transform: { position, rotation: [0, rotationY, 0], scale: [1, 1, 1] },
		component: {
			resourceKey: template.resourceKey,
			componentType: template.componentType,
			generator: template.generator,
			generatorVersion: template.generatorVersion,
			properties: {
				...structuredClone(template.defaultProperties),
				...properties,
				referenceDrawingLine: true,
				componentOwnedRoute: template.capabilities.includes('material-flow'),
			},
			sectionId,
		},
	};
};

/**
 * V11 参考产线只持久化真正空间相接的物料端口 Connection。
 * 普通输送 Route 由组件 internalFlows + Connection 自动派生，避免再次维护重复坐标路线。
 */
type ReferenceConnection = NonNullable<TwinSceneManifest['connections']>[number];

const connectionEndpointKey = (objectId: string, portId: string) => `${objectId}:${portId}`;

const buildReferenceTopologyConnections = (manifest: TwinSceneManifest, routes: TwinRouteDefinition[]) => {
	const objects = (manifest.objects as TwinV7SceneObjectDefinition[]).filter((item) => item.kind === 'component' && item.component);
	const byObjectId = new Map(objects.map((item) => [item.objectId, item]));
	const bySectionId = new Map(objects.filter((item) => item.component?.sectionId).map((item) => [item.component!.sectionId!, item]));
	const used = new Set<string>();
	const connections: ReferenceConnection[] = [];
	const pointComponent = (point?: TwinRoutePointDefinition) => point
		? (point.componentObjectId ? byObjectId.get(point.componentObjectId) : undefined) || bySectionId.get(point.pointId)
		: undefined;
	const edgeComponent = (edge: TwinRouteEdgeDefinition) => bySectionId.get(edge.edgeId)
		|| objects.find((item) => Array.isArray(item.component?.properties?.referenceEdgeIds)
			&& (item.component!.properties!.referenceEdgeIds as unknown[]).some((edgeId) => String(edgeId) === edge.edgeId));
	const endpointObject = (route: TwinRouteDefinition, edge: TwinRouteEdgeDefinition, pointId: string) => {
		const direct = edgeComponent(edge);
		if (direct) return direct;
		const oppositePointId = edge.fromPointId === pointId ? edge.toPointId : edge.fromPointId;
		return pointComponent(route.points.find((item) => item.pointId === oppositePointId));
	};
	const connectObjects = (fromObject?: TwinV7SceneObjectDefinition, toObject?: TwinV7SceneObjectDefinition) => {
		if (!fromObject || !toObject || fromObject.objectId === toObject.objectId) return;
		const fromPorts = resolveComponentPorts(fromObject).filter((port) => port.type === 'material-output' || port.type === 'material-bidirectional');
		const toPorts = resolveComponentPorts(toObject).filter((port) => port.type === 'material-input' || port.type === 'material-bidirectional');
		const candidates = fromPorts.flatMap((from) => toPorts
			.filter((to) => areComponentPortsCompatible(from, to))
			.map((to) => ({ from, to, distance: from.worldPosition.distanceTo(to.worldPosition) })))
			.filter((candidate) => !used.has(connectionEndpointKey(candidate.from.objectId, candidate.from.portId)) && !used.has(connectionEndpointKey(candidate.to.objectId, candidate.to.portId)))
			.sort((left, right) => left.distance - right.distance);
		const best = candidates[0];
		if (!best) return;
		const fromKey = connectionEndpointKey(best.from.objectId, best.from.portId);
		const toKey = connectionEndpointKey(best.to.objectId, best.to.portId);
		connections.push({
			connectionId: `reference-topology-${best.from.objectId}-${best.from.portId}-${best.to.objectId}-${best.to.portId}`,
			from: { objectId: best.from.objectId, portId: best.from.portId },
			to: { objectId: best.to.objectId, portId: best.to.portId },
			autoGenerated: true,
			metadata: { topologyBridge: true, source: 'reference-layout-scaffold' },
		});
		used.add(fromKey);
		used.add(toKey);
	};

	for (const route of routes) {
		for (const routePoint of route.points) {
			const center = pointComponent(routePoint);
			const centerOwnsMaterialFlow = center ? resolveComponentPorts(center).some((port) => port.type === 'material-input' || port.type === 'material-output' || port.type === 'material-bidirectional') : false;
			const incoming = route.edges.filter((edge) => edge.toPointId === routePoint.pointId).map((edge) => endpointObject(route, edge, routePoint.pointId)).filter(Boolean) as TwinV7SceneObjectDefinition[];
			const outgoing = route.edges.filter((edge) => edge.fromPointId === routePoint.pointId).map((edge) => endpointObject(route, edge, routePoint.pointId)).filter(Boolean) as TwinV7SceneObjectDefinition[];
			if (center && centerOwnsMaterialFlow) {
				for (const source of incoming) connectObjects(source, center);
				for (const target of outgoing) connectObjects(center, target);
				continue;
			}
			for (const source of incoming) for (const target of outgoing) connectObjects(source, target);
		}
	}
	return connections;
};

const buildReferenceTouchingConnections = (manifest: TwinSceneManifest, maxDistance = 0.18, reservedConnections: ReferenceConnection[] = []) => {
	const components = (manifest.objects as TwinV7SceneObjectDefinition[]).filter((item) => {
		if (item.kind !== 'component' || !item.component) return false;
		if (item.component.properties?.referenceDrawingLine !== true) return false;
		return getBuiltInComponentTemplate(item.component.resourceKey)?.capabilities.includes('material-flow') === true;
	});
	const ports = components.flatMap((object) => resolveComponentPorts(object));
	const candidates: Array<{ left: (typeof ports)[number]; right: (typeof ports)[number]; distance: number }> = [];
	for (let leftIndex = 0; leftIndex < ports.length; leftIndex += 1) {
		for (let rightIndex = leftIndex + 1; rightIndex < ports.length; rightIndex += 1) {
			const left = ports[leftIndex], right = ports[rightIndex];
			if (left.objectId === right.objectId || !areComponentPortsCompatible(left, right)) continue;
			if (left.worldDirection.dot(right.worldDirection) > -0.965) continue;
			const distance = left.worldPosition.distanceTo(right.worldPosition);
			if (distance <= maxDistance) candidates.push({ left, right, distance });
		}
	}
	candidates.sort((left, right) => left.distance - right.distance
		|| `${left.left.objectId}:${left.left.portId}`.localeCompare(`${right.left.objectId}:${right.left.portId}`));
	const used = new Set<string>();
	for (const connection of reservedConnections) {
		used.add(connectionEndpointKey(connection.from.objectId, connection.from.portId));
		used.add(connectionEndpointKey(connection.to.objectId, connection.to.portId));
	}
	const connections = [] as NonNullable<TwinSceneManifest['connections']>;
	for (const candidate of candidates) {
		const leftKey = `${candidate.left.objectId}:${candidate.left.portId}`;
		const rightKey = `${candidate.right.objectId}:${candidate.right.portId}`;
		if (used.has(leftKey) || used.has(rightKey)) continue;
		const leftIsOutput = candidate.left.type === 'material-output';
		const rightIsOutput = candidate.right.type === 'material-output';
		const from = leftIsOutput || (!rightIsOutput && leftKey < rightKey) ? candidate.left : candidate.right;
		const to = from === candidate.left ? candidate.right : candidate.left;
		connections.push({
			connectionId: `reference-connection-${from.objectId}-${from.portId}-${to.objectId}-${to.portId}`,
			from: { objectId: from.objectId, portId: from.portId },
			to: { objectId: to.objectId, portId: to.portId },
			autoGenerated: true,
		});
		used.add(leftKey);
		used.add(rightKey);
	}
	return connections;
};

const point = (pointId: string, name: string, x: number, z: number, kind: TwinRoutePointDefinition['kind'] = 'waypoint'): TwinRoutePointDefinition => ({
	pointId,
	name,
	position: [x, SMALL_HEIGHT, z],
	kind,
});

const edge = (
	edgeId: string,
	fromPointId: string,
	toPointId: string,
	name: string,
	options: Partial<TwinRouteEdgeDefinition> = {},
): TwinRouteEdgeDefinition => {
	const conveyorSizeClass = options.conveyorSizeClass || 'small';
	const transportUnitType = options.transportUnitType || 'plastic-pallet';
	const transportUnitResourceKey = options.transportUnitResourceKey
		|| (transportUnitType === 'carton'
			? 'builtin-carton'
			: transportUnitType === 'wooden-pallet'
				? 'builtin-wooden-pallet'
				: conveyorSizeClass === 'small' ? 'builtin-small-pallet' : 'builtin-plastic-pallet');
	return {
		edgeId,
		fromPointId,
		toPointId,
		name,
		bidirectional: false,
		enabled: true,
		priority: 0,
		capacity: 4,
		occupancyMode: 'simulation',
		reservationTimeoutSeconds: 30,
		conveyorSizeClass,
		transportUnitType,
		transportUnitResourceKey,
		...options,
	};
};

const straightComponentForEdge = (
	route: TwinRouteDefinition,
	routeEdge: TwinRouteEdgeDefinition,
): TwinV7SceneObjectDefinition | undefined => {
	const from = route.points.find((candidate) => candidate.pointId === routeEdge.fromPointId);
	const to = route.points.find((candidate) => candidate.pointId === routeEdge.toPointId);
	if (!from || !to) return undefined;
	const dx = to.position[0] - from.position[0];
	const dz = to.position[2] - from.position[2];
	const length = Math.hypot(dx, dz);
	if (length < 0.5) return undefined;
	const large = routeEdge.conveyorSizeClass === 'large';
	return componentObject(
		large ? 'builtin-large-roller-conveyor' : 'builtin-small-roller-conveyor',
		`reference-conveyor-${routeEdge.edgeId}`,
		`${large ? '大辊道' : '小辊道'} · ${routeEdge.name}`,
		[(from.position[0] + to.position[0]) / 2, 0, (from.position[2] + to.position[2]) / 2],
		-Math.atan2(dz, dx),
		{
			length,
			width: large ? 2.4 : 1.55,
			height: large ? LARGE_HEIGHT : SMALL_HEIGHT,
			capacity: routeEdge.capacity ?? (large ? 1 : 4),
			conveyorSizeClass: large ? 'large' : 'small',
			transportUnitType: large ? (routeEdge.transportUnitType || 'carton') : 'plastic-pallet',
			occupancyMode: 'simulation',
		},
		routeEdge.edgeId,
	);
};

/**
 * V7 将外检后的前行线与空托回流彻底拆开：
 * - 前行：机器人上料 -> 外检 -> 独立输送到双套袋；
 * - 回流：套袋汇流后从另一条物理路线回机器人，只在套袋末端/机器人上料区做工艺交接。
 * 外检出口到套袋之间与回流线不共享点、不交叉、不汇流。
 */
const createSmallMainRoute = (): TwinRouteDefinition => ({
	routeId: 'reference-small-pallet-main',
	name: '参考图小托盘完整工艺闭环（机器人→外检→套袋→桁架取丝→空托回流）',
	type: 'conveyor',
	curveKind: 'line',
	defaultSpeed: 1.0,
	loop: true,
	orientToPath: true,
	points: [
		point('ref-robot-out', '底部机器人上料位', 0, 13.3, 'station'),
		point('ref-robot-east', '机器人前行线右端', 13, 13.3, 'buffer'),
		point('ref-inspection-east-turn', '外检回路右下转角', 13, 6.8, 'buffer'),
		point('ref-inspection-right', '外检机右侧入口', 8, 6.8, 'buffer'),
		{ ...point('ref-inspection', '外检机内部检测位', 4.6, 6.8, 'processStation'), componentObjectId: 'reference-external-inspection', process: { type: 'external-inspection', cycleSeconds: 2 } },
		point('ref-inspection-left', '外检机左侧出口', 1.2, 6.8, 'buffer'),
		point('ref-empty-return-diverter', '外检后空托/有料一级分流位', -5.2, 6.8, 'diverter'),
		point('ref-inspection-diverter', '外检后一分二分流点', -10.8, 6.8, 'diverter'),
		// 外检后的空托从这里进入独立回流支路。该支路不经过套袋/有料双排线，
		// 直到桁架抓取完成后的公共空托回流段才汇合。
		{ ...point('ref-empty-return-merger-b', '外检后空托独立回流汇入口', -12.13798061746948, 6.365879555832675, 'buffer'), componentObjectId: 'reference-gantry-merger' },

		point('ref-a-left-entry', 'A 路内侧上行入口', -8.9, 6.8, 'buffer'),
		point('ref-a-middle-west', 'A 路内侧上行接驳', -8.9, -0.8, 'buffer'),
		point('ref-a-middle-east', 'A 路上层横线东端', 6.8, -0.8, 'buffer'),
		point('ref-a-bag-left', '套袋 A 左侧入口', 6.8, -12.9, 'buffer'),
		{ ...point('ref-bag-a', '套袋机 A 内部工位', 15, -12.9, 'processStation'), componentObjectId: 'reference-bagging-a', process: { type: 'bagging', cycleSeconds: 3 } },
		point('ref-bag-a-right', '套袋 A 右侧出口', 20, -12.9, 'buffer'),
		point('ref-bag-a-merge-turn', '套袋 A 汇流转接', 21.5, -12.9, 'buffer'),

		point('ref-b-left-entry', 'B 路左侧双排入口', -10.8, 6.8, 'buffer'),
		point('ref-b-middle-west', '外检后下排去套袋接驳', -10.8, 3, 'buffer'),
		point('ref-b-middle-east', '外检后下排去套袋东端', 6.8, 3, 'buffer'),
		point('ref-b-bag-left', '套袋 B 左侧入口', 6.8, -5.5, 'buffer'),
		{ ...point('ref-bag-b', '套袋机 B 内部工位', 14.5, -5.5, 'processStation'), componentObjectId: 'reference-bagging-b', process: { type: 'bagging', cycleSeconds: 3 } },
		point('ref-bag-b-right', '套袋 B 右侧出口', 20, -5.5, 'buffer'),

		point('ref-post-bag-merge', '双套袋后二合一汇流点', 21.5, -5.5, 'merger'),
		point('ref-post-bag-east', '套袋后右侧纵向转接', 21.5, -0.8, 'buffer'),
		point('ref-post-bag-up', '套袋后进入上排左向回流线', 21.5, 1.1, 'buffer'),
		point('ref-loaded-middle-tap', '上排左向回流接驳', 6.8, 1.1, 'buffer'),
		point('ref-loaded-upper-right-in', '有料托盘右上双排入口', 6.8, -5.3, 'buffer'),
		point('ref-loaded-upper-right-out', '有料托盘右上双排出口', 6.8, -17.7, 'buffer'),
		point('ref-gantry-pick', '桁架抓取丝锭工位', -12.7, -17.7, 'station'),
		point('ref-gantry-out', '桁架抓取后空托出口', -13.6, -17.7, 'buffer'),
		point('ref-return-outer-top', '空托外侧回流上端', -14.6, -17.7, 'buffer'),
		{ ...point('ref-gantry-merger', '桁架后空托主路汇流入口', -14.6, 4.3, 'buffer'), componentObjectId: 'reference-gantry-merger' },
		{ ...point('ref-gantry-merger-out', '外检/桁架空托汇流后公共回流出口', -14.6, 9.0, 'merger'), componentObjectId: 'reference-gantry-merger' },
		point('ref-return-outer-bottom', '空托外侧回流下端', -14.6, 15.2, 'buffer'),
		point('ref-return-bottom-in', '底部双排 B 回流入口', -10.8, 15.2, 'buffer'),
		point('ref-return-bottom-tap', '底部双排 B 机器人接驳', 0, 15.2, 'buffer'),
	],
	edges: [
		edge('ref-edge-robot-east', 'ref-robot-out', 'ref-robot-east', '机器人上料后前行', { capacity: 8 }),
		edge('ref-edge-inspection-right-rise', 'ref-robot-east', 'ref-inspection-east-turn', '外检右侧进料纵段', { capacity: 5 }),
		edge('ref-edge-inspection-right-in', 'ref-inspection-east-turn', 'ref-inspection-right', '外检右侧入口横段', { capacity: 3 }),
		edge('ref-edge-inspection-in', 'ref-inspection-right', 'ref-inspection', '外检右进', { capacity: 3 }),
		edge('ref-edge-inspection-out', 'ref-inspection', 'ref-inspection-left', '外检左出', { capacity: 3 }),
		edge('ref-edge-inspection-to-diverter', 'ref-inspection-left', 'ref-empty-return-diverter', '外检左出至空托一级分流', { capacity: 5 }),
		edge('ref-empty-return-loaded', 'ref-empty-return-diverter', 'ref-inspection-diverter', '有料托继续进入套袋 A/B 分流', { priority: 10, capacity: 5 }),
		edge('ref-empty-return-down', 'ref-empty-return-diverter', 'ref-empty-return-merger-b', '外检后空托独立直回流', { priority: 20, capacity: 8 }),

		edge('ref-edge-diverter-a', 'ref-inspection-diverter', 'ref-a-left-entry', '一分二 A 路', { priority: 10, capacity: 2 }),
		edge('ref-edge-a-left-up', 'ref-a-left-entry', 'ref-a-middle-west', 'A 路内侧独立上行段', { priority: 10, capacity: 8 }),
		edge('ref-edge-a-middle-east', 'ref-a-middle-west', 'ref-a-middle-east', 'A 路套袋前横段', { priority: 10, capacity: 8 }),
		edge('ref-edge-a-bag-up', 'ref-a-middle-east', 'ref-a-bag-left', 'A 路套袋入口纵段', { priority: 10, capacity: 5 }),
		edge('ref-edge-bag-a', 'ref-a-bag-left', 'ref-bag-a', '套袋 A 入口', { priority: 10, capacity: 1 }),
		edge('ref-edge-bag-a-out', 'ref-bag-a', 'ref-bag-a-right', '套袋 A 出口', { priority: 10, capacity: 1 }),
		edge('ref-edge-bag-a-merge-x', 'ref-bag-a-right', 'ref-bag-a-merge-turn', '套袋 A 汇流横段', { priority: 10, capacity: 2 }),
		edge('ref-edge-bag-a-merge-z', 'ref-bag-a-merge-turn', 'ref-post-bag-merge', '套袋 A 汇流纵段', { priority: 10, capacity: 3 }),

		edge('ref-edge-diverter-b', 'ref-inspection-diverter', 'ref-b-left-entry', '一分二 B 路', { capacity: 5 }),
		edge('ref-edge-b-left-down', 'ref-b-left-entry', 'ref-b-middle-west', 'B 路内侧独立上行段', { capacity: 5 }),
		edge('ref-edge-b-middle-east', 'ref-b-middle-west', 'ref-b-middle-east', 'B 路中部双排前行段', { capacity: 8 }),
		edge('ref-edge-b-bag-up', 'ref-b-middle-east', 'ref-b-bag-left', 'B 路套袋入口纵段', { capacity: 5 }),
		edge('ref-edge-bag-b', 'ref-b-bag-left', 'ref-bag-b', '套袋 B 入口', { capacity: 1 }),
		edge('ref-edge-bag-b-out', 'ref-bag-b', 'ref-bag-b-right', '套袋 B 出口', { capacity: 1 }),
		edge('ref-edge-bag-b-merge', 'ref-bag-b-right', 'ref-post-bag-merge', '套袋 B 汇流横段', { capacity: 2 }),

		edge('ref-edge-post-bag-east', 'ref-post-bag-merge', 'ref-post-bag-east', '双套袋汇流后横段', { capacity: 4 }),
		edge('ref-edge-post-bag-up', 'ref-post-bag-east', 'ref-post-bag-up', '套袋后上行至桁架输送', { capacity: 8 }),
		edge('ref-edge-loaded-middle-return', 'ref-post-bag-up', 'ref-loaded-middle-tap', '有料托盘沿中部 B 排反向送往桁架', { capacity: 8 }),
		edge('ref-edge-loaded-upper-right-in', 'ref-loaded-middle-tap', 'ref-loaded-upper-right-in', '有料托盘进入右上双排', { capacity: 5 }),
		edge('ref-edge-loaded-upper-right', 'ref-loaded-upper-right-in', 'ref-loaded-upper-right-out', '有料托盘右上双排上行', { capacity: 8 }),
		edge('ref-edge-loaded-upper-north', 'ref-loaded-upper-right-out', 'ref-gantry-pick', '有料托盘送至桁架抓取位', { capacity: 8 }),
		edge('ref-gantry-edge-a-merge', 'ref-gantry-pick', 'ref-gantry-out', '桁架抓取后空托向外侧回流', { capacity: 2 }),
		edge('ref-gantry-edge-out', 'ref-gantry-out', 'ref-return-outer-top', '桁架后空托接入外侧回流', { capacity: 4 }),
		edge('ref-return-edge-outer-top', 'ref-return-outer-top', 'ref-gantry-merger', '桁架后空托沿独立主路到汇流入口', { capacity: 12 }),
		edge('ref-return-edge-outer-down', 'ref-gantry-merger-out', 'ref-return-outer-bottom', '外检/桁架空托汇流后公共回流', { capacity: 18 }),
		edge('ref-return-edge-bottom-in', 'ref-return-outer-bottom', 'ref-return-bottom-in', '空托进入底部双排 B', { capacity: 5 }),
		edge('ref-return-edge-bottom-b', 'ref-return-bottom-in', 'ref-return-bottom-tap', '底部双排 B 空托回机器人', { capacity: 8 }),
		edge('ref-return-edge-robot-cross', 'ref-return-bottom-tap', 'ref-robot-out', '空托交回机器人上料位', { capacity: 2 }),
	],
	startPointId: 'ref-robot-out',
	junctionDecisions: { 'ref-empty-return-diverter': 'ref-empty-return-loaded', 'ref-inspection-diverter': 'ref-edge-diverter-a' },
	routingMode: 'automatic',
	decisionRules: [{
		ruleId: 'ref-rule-bag-b',
		name: 'B 类产品进入套袋机 B',
		junctionPointId: 'ref-inspection-diverter',
		edgeId: 'ref-edge-diverter-b',
		source: 'payload',
		payloadKey: 'routeCode',
		operator: 'equals',
		matchValue: 'B',
		priority: 100,
		enabled: true,
	}],
});

/**
 * V9 物理布局基线。
 * 仅用于生成参考包装线的辊道/设备几何；后续版本的遥测、动作编排和运行能力
 * 继续由当前 Manifest/Runtime 承载，不随布局回退。
 */
const createV9SmallMainLayoutRoute = (): TwinRouteDefinition => ({
	routeId: 'reference-small-pallet-main-v9-layout',
	name: 'V9 小托盘前行布局（机器人→外检右进左出→一分二→双套袋→上行）',
	type: 'conveyor',
	curveKind: 'line',
	defaultSpeed: 1.0,
	loop: false,
	orientToPath: true,
	points: [
		{ ...point('ref-robot-out', '底部机器人上料位', 0, 12.8, 'processStation'), componentObjectId: 'reference-loading-robot', process: { type: 'robot-loading', cycleSeconds: 2 } },
		point('ref-robot-east', '机器人前行线右端', 13, 12.8, 'buffer'),
		point('ref-inspection-east-turn', '外检回路右下转角', 13, 6.8, 'buffer'),
		point('ref-inspection-right', '外检机右侧入口', 8, 6.8, 'buffer'),
		{ ...point('ref-inspection', '外检机内部检测位', 4.6, 6.8, 'processStation'), componentObjectId: 'reference-external-inspection', process: { type: 'external-inspection', cycleSeconds: 2 } },
		point('ref-inspection-left', '外检机左侧出口', 1.2, 6.8, 'buffer'),
		point('ref-inspection-diverter', '外检后一分二分流点', -10.8, 6.8, 'diverter'),

		point('ref-a-left-entry', 'A 路左侧双排入口', -12.7, 6.8, 'buffer'),
		point('ref-a-middle-west', 'A 路上层横线西端', -12.7, -0.8, 'buffer'),
		point('ref-a-middle-east', 'A 路上层横线东端', 6.8, -0.8, 'buffer'),
		point('ref-a-bag-left', '套袋 A 左侧入口', 6.8, -12.9, 'buffer'),
		{ ...point('ref-bag-a', '套袋机 A 内部工位', 15, -12.9, 'processStation'), componentObjectId: 'reference-bagging-a', process: { type: 'bagging', cycleSeconds: 3 } },
		point('ref-bag-a-right', '套袋 A 右侧出口', 20, -12.9, 'buffer'),
		point('ref-bag-a-merge-turn', '套袋 A 汇流转接', 21.5, -12.9, 'buffer'),

		point('ref-b-middle-west', 'B 路中部双排西端', -10.8, 1.1, 'buffer'),
		point('ref-b-middle-east', 'B 路中部双排东端', 6.8, 1.1, 'buffer'),
		point('ref-b-bag-left', '套袋 B 左侧入口', 6.8, -5.5, 'buffer'),
		{ ...point('ref-bag-b', '套袋机 B 内部工位', 14.5, -5.5, 'processStation'), componentObjectId: 'reference-bagging-b', process: { type: 'bagging', cycleSeconds: 3 } },
		point('ref-bag-b-right', '套袋 B 右侧出口', 20, -5.5, 'buffer'),

		point('ref-post-bag-merge', '双套袋后二合一汇流点', 21.5, -5.5, 'merger'),
		point('ref-post-bag-east', '套袋后右侧纵向转接', 21.5, -0.8, 'buffer'),
		point('ref-post-bag-up', '套袋后中部回流交接位', 21.5, 3, 'station'),
	],
	edges: [
		edge('ref-edge-robot-east', 'ref-robot-out', 'ref-robot-east', '机器人至外检前行横段', { capacity: 8 }),
		edge('ref-edge-inspection-right-rise', 'ref-robot-east', 'ref-inspection-east-turn', '外检右侧进料纵段', { capacity: 5 }),
		edge('ref-edge-inspection-right-in', 'ref-inspection-east-turn', 'ref-inspection-right', '外检右侧入口横段', { capacity: 3 }),
		edge('ref-edge-inspection-in', 'ref-inspection-right', 'ref-inspection', '外检右进', { capacity: 3 }),
		edge('ref-edge-inspection-out', 'ref-inspection', 'ref-inspection-left', '外检左出', { capacity: 3 }),
		edge('ref-edge-inspection-to-diverter', 'ref-inspection-left', 'ref-inspection-diverter', '外检左出至一分二', { capacity: 5 }),

		edge('ref-edge-diverter-a', 'ref-inspection-diverter', 'ref-a-left-entry', '一分二 A 路', { priority: 10, capacity: 2 }),
		edge('ref-edge-a-left-up', 'ref-a-left-entry', 'ref-a-middle-west', 'A 路左侧双排段', { priority: 10, capacity: 8 }),
		edge('ref-edge-a-middle-east', 'ref-a-middle-west', 'ref-a-middle-east', 'A 路中部双排段', { priority: 10, capacity: 12 }),
		edge('ref-edge-a-bag-up', 'ref-a-middle-east', 'ref-a-bag-left', 'A 路套袋入口上行段', { priority: 10, capacity: 5 }),
		edge('ref-edge-bag-a', 'ref-a-bag-left', 'ref-bag-a', '套袋 A 入口', { priority: 10, capacity: 1 }),
		edge('ref-edge-bag-a-out', 'ref-bag-a', 'ref-bag-a-right', '套袋 A 出口', { priority: 10, capacity: 1 }),
		edge('ref-edge-bag-a-merge-x', 'ref-bag-a-right', 'ref-bag-a-merge-turn', '套袋 A 汇流横段', { priority: 10, capacity: 2 }),
		edge('ref-edge-bag-a-merge-z', 'ref-bag-a-merge-turn', 'ref-post-bag-merge', '套袋 A 汇流纵段', { priority: 10, capacity: 3 }),

		edge('ref-edge-diverter-b', 'ref-inspection-diverter', 'ref-b-middle-west', '一分二 B 路', { capacity: 8 }),
		edge('ref-edge-b-middle-east', 'ref-b-middle-west', 'ref-b-middle-east', 'B 路中部双排段', { capacity: 12 }),
		edge('ref-edge-b-bag-up', 'ref-b-middle-east', 'ref-b-bag-left', 'B 路套袋入口上行段', { capacity: 5 }),
		edge('ref-edge-bag-b', 'ref-b-bag-left', 'ref-bag-b', '套袋 B 入口', { capacity: 1 }),
		edge('ref-edge-bag-b-out', 'ref-bag-b', 'ref-bag-b-right', '套袋 B 出口', { capacity: 1 }),
		edge('ref-edge-bag-b-merge', 'ref-bag-b-right', 'ref-post-bag-merge', '套袋 B 汇流横段', { capacity: 2 }),

		edge('ref-edge-post-bag-east', 'ref-post-bag-merge', 'ref-post-bag-east', '双套袋汇流后横段', { capacity: 4 }),
		edge('ref-edge-post-bag-up', 'ref-post-bag-east', 'ref-post-bag-up', '套袋后向上小辊道', { capacity: 8 }),
	],
	startPointId: 'ref-robot-out',
	junctionDecisions: { 'ref-inspection-diverter': 'ref-edge-diverter-a' },
	routingMode: 'automatic',
	decisionRules: [{
		ruleId: 'ref-rule-bag-b', name: 'B 类产品进入套袋机 B', junctionPointId: 'ref-inspection-diverter', edgeId: 'ref-edge-diverter-b',
		source: 'payload', payloadKey: 'routeCode', operator: 'equals', matchValue: 'B', priority: 100, enabled: true,
	}],
});

/**
 * V19 现场路线以用户最终标注图为唯一方向基准。
 * 组件端口 Connection 负责物理拼装，但不能直接作为编辑器路线：端口桥接会产生
 * 斜线和重复线段，也会让控制点变成只读。这里把同一物理拓扑整理成正交、可编辑、
 * 可直接运行的主路线，并明确画出底部双排、外检、双套袋、桁架和空托回流。
 */
const createEditableSmallMainRouteV19Draft = (generatedRoute?: TwinRouteDefinition): TwinRouteDefinition => {
	const route = createSmallMainRoute();
	route.routeId = 'component-route-d045206d';
	route.name = 'V19 现场手绘小托盘闭环（双排→外检→双套袋→桁架→空托回流）';

	// 外检后的空托先向图纸下方让开旋转台，再水平并入桁架空托回流。
	route.points = route.points
		.filter((item) => item.pointId !== 'ref-empty-return-merger-b')
		.map((item) => {
			if (item.pointId === 'ref-return-bottom-tap') return { ...item, pointId: 'ref-robot-return', name: '底部 B 排机器人上料位', position: [0, SMALL_HEIGHT, 15.2], kind: 'processStation' };
			if (item.pointId === 'ref-a-left-entry') return { ...item, position: [-10.8, SMALL_HEIGHT, 5.3] };
			if (item.pointId === 'ref-a-middle-west') return { ...item, position: [-10.8, SMALL_HEIGHT, -0.8] };
			if (item.pointId === 'ref-b-left-entry') return { ...item, position: [-12.7, SMALL_HEIGHT, 6.8] };
			if (item.pointId === 'ref-b-middle-west') return { ...item, position: [-12.7, SMALL_HEIGHT, 3] };
			return item;
		});
	route.points.push(
		point('ref-empty-return-turn-b', '外检空托回流下转角', -5.2, 9.0, 'buffer'),
		point('ref-return-bottom-a-in', '底部 A 排左侧入口', -10.8, 13.3, 'buffer'),
		point('ref-robot-east-b', '底部 B 排右端', 13, 15.2, 'buffer'),
	);
	const pointById = (pointId: string) => route.points.find((item) => item.pointId === pointId);
	const loadingLayout = { rows: 1, columns: 6, rowSpacingMeters: 0, columnSpacingMeters: 1.55, rowAxis: 'z' as const, columnAxis: 'x' as const };
	for (const [pointId, physicalLane, releaseEdgeId] of [
		['ref-robot-out', 'A', 'ref-edge-robot-east'],
		['ref-robot-return', 'B', 'ref-edge-robot-east-b'],
	] as const) {
		const loadingPoint = pointById(pointId);
		if (!loadingPoint) continue;
		loadingPoint.kind = 'processStation';
		loadingPoint.componentObjectId = 'reference-loading-robot';
		loadingPoint.process = {
			type: 'robot-loading', cycleSeconds: 2, batchSize: 12, batchLayout: loadingLayout,
			simulationEntry: true, physicalLane, releaseEdgeId,
			behaviorCompletionGroups: ['load'], behaviorCompletionRequirements: { load: 1 },
		};
	}
	const gantryPoint = pointById('ref-gantry-pick');
	if (gantryPoint) {
		gantryPoint.kind = 'processStation';
		gantryPoint.componentObjectId = 'reference-stacking-gantry';
		gantryPoint.process = {
			type: 'gantry-stacking', cycleSeconds: 3, batchSize: 6,
			batchLayout: { rows: 1, columns: 6, rowSpacingMeters: 0, columnSpacingMeters: 1.55, rowAxis: 'z', columnAxis: 'x' },
			behaviorCompletionGroups: ['yarn', 'separator'], behaviorCompletionRequirements: { yarn: 1, separator: 1 },
		};
	}
	const outerBottom = pointById('ref-return-outer-bottom');
	if (outerBottom) { outerBottom.kind = 'diverter'; outerBottom.decisionMode = 'simulation'; }

	const replacedEdgeIds = new Set([
		'ref-empty-return-down', 'ref-return-edge-outer-down', 'ref-return-edge-bottom-in',
		'ref-return-edge-bottom-b', 'ref-return-edge-robot-cross',
	]);
	route.edges = route.edges.filter((item) => !replacedEdgeIds.has(item.edgeId));
	route.edges.push(
		edge('ref-empty-return-down', 'ref-empty-return-diverter', 'ref-empty-return-turn-b', '外检后空托下行回流', { priority: 20, capacity: 8 }),
		edge('ref-empty-return-merge', 'ref-empty-return-turn-b', 'ref-gantry-merger-out', '外检空托水平并入桁架回流', { priority: 20, capacity: 8 }),
		edge('ref-gantry-merger-through', 'ref-gantry-merger', 'ref-gantry-merger-out', '桁架空托通过汇流位', { capacity: 18 }),
		edge('ref-return-edge-outer-down', 'ref-gantry-merger-out', 'ref-return-outer-bottom', '汇流后空托下行至底部双排', { capacity: 18 }),
		edge('ref-return-edge-bottom-in-a', 'ref-return-outer-bottom', 'ref-return-bottom-a-in', '空托进入底部 A 排', { priority: 10, capacity: 5 }),
		edge('ref-return-edge-bottom-a', 'ref-return-bottom-a-in', 'ref-robot-out', '底部 A 排回到机器人', { capacity: 8 }),
		edge('ref-return-edge-bottom-in-b', 'ref-return-outer-bottom', 'ref-return-bottom-in', '空托进入底部 B 排', { priority: 20, capacity: 5 }),
		edge('ref-return-edge-bottom-b', 'ref-return-bottom-in', 'ref-robot-return', '底部 B 排回到机器人', { capacity: 8 }),
		edge('ref-edge-robot-east-b', 'ref-robot-return', 'ref-robot-east-b', '机器人上料后沿 B 排前行', { capacity: 8 }),
		edge('ref-edge-bottom-b-merge', 'ref-robot-east-b', 'ref-robot-east', '底部 B 排在右端并入 A 排', { capacity: 2 }),
	);

	const edgeById = (edgeId: string) => route.edges.find((item) => item.edgeId === edgeId);
	const attachLiveGate = (edgeId: string, lane: 'a' | 'b') => {
		const target = edgeById(edgeId);
		if (!target) return;
		const prefix = `reference-robot-cross-${lane}`;
		target.releasePermitBindingId = `${prefix}-release-permit`;
		target.readyBindingId = `${prefix}-ready`;
		target.blockedBindingId = `${prefix}-blocked`;
		target.fullBindingId = `${prefix}-full`;
		target.componentObjectId = 'reference-double-small-bottom';
		target.sectionId = edgeId;
	};
	attachLiveGate('ref-return-edge-bottom-in-a', 'a');
	attachLiveGate('ref-return-edge-bottom-in-b', 'b');
	for (const edgeId of ['ref-return-edge-bottom-a', 'ref-edge-robot-east', 'ref-return-edge-bottom-b', 'ref-edge-robot-east-b']) {
		const target = edgeById(edgeId);
		if (target) { target.componentObjectId = 'reference-double-small-bottom'; target.sectionId = edgeId; }
	}

	// 能从组件路线一一对应的区段继续携带 section/component 元数据，供占用率和状态高亮使用。
	for (const target of route.edges) {
		const source = generatedRoute?.edges.find((item) => item.sectionId === target.edgeId || item.edgeId === target.edgeId);
		if (!source) continue;
		target.componentObjectId ||= source.componentObjectId;
		target.sectionId ||= source.sectionId;
		target.conveyorSizeClass ||= source.conveyorSizeClass;
		target.transportUnitType ||= source.transportUnitType;
	}

	// Phase 5：把两条现场空托支路固化成稳定语义 Section。汇流点之后仍是公共回流段，
	// 不覆盖其原 sectionId，避免把共享运行状态误归到任一来源支路。
	route.sections ||= [];
	const ensureSemanticSection = (sectionId: string, name: string) => {
		if (!route.sections!.some((item) => item.sectionId === sectionId)) route.sections!.push({ sectionId, name, enabled: true });
	};
	ensureSemanticSection('EmptyReturnAfterInspection', '外检后空托独立回流');
	ensureSemanticSection('GantryEmptyReturn', '桁架抓取后空托回流');
	for (const edgeId of ['ref-empty-return-down', 'ref-empty-return-merge']) {
		const target = edgeById(edgeId);
		if (!target) continue;
		target.sectionId = 'EmptyReturnAfterInspection';
		target.authoring = { ...target.authoring, mode: 'manual', generatedKey: target.authoring?.generatedKey || edgeId, locked: false, convertedFromGenerated: true };
	}
	for (const edgeId of ['ref-gantry-edge-a-merge', 'ref-gantry-edge-out', 'ref-return-edge-outer-top', 'ref-gantry-merger-through']) {
		const target = edgeById(edgeId);
		if (target) target.sectionId = 'GantryEmptyReturn';
	}

	route.startPointId = 'ref-robot-out';
	route.junctionDecisions['ref-return-outer-bottom'] = 'ref-return-edge-bottom-in-a';
	route.decisionRules = route.decisionRules.filter((item) => !['reference-bottom-lane-a-return-cross', 'reference-bottom-lane-b-forward', 'reference-empty-return-rule'].includes(item.ruleId));
	route.decisionRules.push(
		{ ruleId: 'reference-empty-return-rule', name: '外检后空托直回流', junctionPointId: 'ref-empty-return-diverter', edgeId: 'ref-empty-return-down', source: 'payload', payloadKey: 'materialCount', operator: 'equals', matchValue: 0, priority: 200, enabled: true },
		{ ruleId: 'reference-bottom-lane-a-return-cross', name: '底部 A 排分流权重', junctionPointId: 'ref-return-outer-bottom', edgeId: 'ref-return-edge-bottom-in-a', source: 'payload', payloadKey: 'palletId', operator: 'truthy', weight: 1, priority: 100, enabled: true },
		{ ruleId: 'reference-bottom-lane-b-forward', name: '底部 B 排分流权重', junctionPointId: 'ref-return-outer-bottom', edgeId: 'ref-return-edge-bottom-in-b', source: 'payload', payloadKey: 'palletId', operator: 'truthy', weight: 1, priority: 100, enabled: true },
	);
	return route;
};

/**
 * V9 视觉布局继续使用旧图纸坐标，但运行时仍需要当前版本的完整闭环语义。
 * 不能再从“最长 generated small route”猜主路线：V9 的中央马蹄缓存也属于 small/plastic，
 * 一旦被误选，Simulation 托盘会从中央缓存初始化，而不是从机器人下方双排辊道开始。
 *
 * 这里复用当前完整闭环定义，只把机器人下方 A/B 两排入口精确对齐到 V9 双排辊道中心线：
 * A = Z 12.8，B = Z 14.7；12 个仿真托盘因此按现有 1×6 batchLayout 分成两排各 6 个。
 */
const createV9RuntimeSmallPalletRoute = (): TwinRouteDefinition => {
	const route = createEditableSmallMainRouteV19Draft();
	route.name = 'V9 小托盘运行闭环（机器人下双排→外检→双套袋→桁架→空托回流）';
	const pointById = new Map(route.points.map((item) => [item.pointId, item]));
	const setPoint = (pointId: string, x: number, z: number) => {
		const target = pointById.get(pointId);
		if (target) target.position = [x, SMALL_HEIGHT, z];
	};

	// V9 底部双排实体：center Z=13.75，laneSpacing=1.9，因此 A/B 中心线分别为 12.8/14.7。
	setPoint('ref-robot-out', 0, 12.8);
	setPoint('ref-robot-east', 13, 12.8);
	setPoint('ref-return-bottom-a-in', -10.8, 12.8);
	setPoint('ref-robot-return', 0, 14.7);
	setPoint('ref-robot-east-b', 13, 14.7);
	setPoint('ref-return-bottom-in', -10.8, 14.7);

	const loadingLayout = { rows: 1, columns: 6, rowSpacingMeters: 0, columnSpacingMeters: 1.55, rowAxis: 'z' as const, columnAxis: 'x' as const };
	for (const [pointId, physicalLane, releaseEdgeId] of [
		['ref-robot-out', 'A', 'ref-edge-robot-east'],
		['ref-robot-return', 'B', 'ref-edge-robot-east-b'],
	] as const) {
		const target = pointById.get(pointId);
		if (!target) continue;
		target.kind = 'processStation';
		target.componentObjectId = 'reference-loading-robot';
		target.process = {
			type: 'robot-loading', cycleSeconds: 2, batchSize: 12, batchLayout: loadingLayout,
			simulationEntry: true, physicalLane, releaseEdgeId,
			behaviorCompletionGroups: ['load'], behaviorCompletionRequirements: { load: 1 },
		};
	}
	route.startPointId = 'ref-robot-out';
	return route;
};

/**
 * V19 最终现场路线。
 *
 * 这张路线直接按用户最终标注图组织，不再从旧组件 Connection 猜测坐标：
 * - 底部两排都从机器人向右进入外检；
 * - 外检后沿中部下排向右进入两台套袋机，两台套袋机均由右向左；
 * - 外检上方双排的上排专供空托反向回机器人；套袋后直接经右上双排送到桁架；
 * - 桁架下两排空托都向下回机器人；
 * - 外检后空托进入独立单排回流，并在桁架空托公共回流处汇合。
 */
const createEditableSmallMainRoute = (generatedRoute?: TwinRouteDefinition): TwinRouteDefinition => {
	const route = createEditableSmallMainRouteV19Draft(generatedRoute);
	route.name = 'V19 现场定稿小托盘闭环（按最终标注图逐段重绘）';

	const robotLayout = {
		rows: 1,
		columns: 6,
		rowSpacingMeters: 0,
		columnSpacingMeters: 1.55,
		rowAxis: 'z' as const,
		columnAxis: 'x' as const,
	};
	const robotStation = (pointId: string, name: string, x: number, z: number, lane: 'A' | 'B', releaseEdgeId: string): TwinRoutePointDefinition => ({
		...point(pointId, name, x, z, 'processStation'),
		componentObjectId: 'reference-loading-robot',
		process: {
			type: 'robot-loading',
			cycleSeconds: 2,
			batchSize: 12,
			batchLayout: robotLayout,
			simulationEntry: true,
			physicalLane: lane,
			releaseEdgeId,
			behaviorCompletionGroups: ['load'],
			behaviorCompletionRequirements: { load: 1 },
		},
	});

	route.points = [
		robotStation('ref-robot-out', '底部 A 排机器人上料位', 0, 13.3, 'A', 'ref-edge-robot-east'),
		point('ref-robot-east', '底部 A 排右端', 10.8, 13.3, 'buffer'),
		robotStation('ref-robot-return', '底部 B 排机器人上料位', 0, 15.2, 'B', 'ref-edge-robot-east-b'),
		point('ref-robot-east-b', '底部 B 排右端', 10.8, 15.2, 'buffer'),
		point('ref-bottom-merge-b-turn', '底部 B 排二合一转角', 13, 15.2, 'buffer'),
		{ ...point('ref-bottom-merge', '底部双排进入外检二合一', 13, 13.3, 'merger'), componentObjectId: 'reference-bottom-b-to-inspection-merge' },
		point('ref-inspection-east-turn', '外检前单线转角', 13, 6.8, 'buffer'),
		point('ref-inspection-right', '外检机右侧入口', 8, 6.8, 'buffer'),
		{ ...point('ref-inspection', '外检机内部检测位', 4.6, 6.8, 'processStation'), componentObjectId: 'reference-external-inspection', process: { type: 'external-inspection', cycleSeconds: 2 } },
		point('ref-inspection-left', '外检机左侧出口', 1.2, 6.8, 'buffer'),
		{ ...point('ref-empty-return-diverter', '外检后空托/有料分流位', -1.5, 6.8, 'diverter'), componentObjectId: 'reference-empty-return-diverter', decisionMode: 'simulation' },
		{ ...point('ref-inspection-diverter', '外检后双排 A/B 分流位', -5.2, 6.8, 'diverter'), componentObjectId: 'reference-inspection-diverter', decisionMode: 'simulation' },
		point('ref-a-middle-west', '外检上方双排 A 排西端', -5.2, 3, 'buffer'),
		point('ref-a-middle-east', '外检上方双排 A 排东端', 21.5, 3, 'buffer'),
		point('ref-a-bag-east-turn', 'A 排套袋外绕转角', 23.5, 3, 'buffer'),
		point('ref-b-middle-west-turn', '外检后 B 排转接横段', -7.1, 6.8, 'buffer'),
		point('ref-b-middle-west', '外检上方双排 B 排西端', -7.1, 4.9, 'buffer'),
		point('ref-b-middle-east', '外检上方双排 B 排东端', 21.5, 4.9, 'buffer'),

		point('ref-bag-a-right-turn', '套袋 A 右侧转角', 23.5, -12.9, 'buffer'),
		point('ref-bag-a-right', '套袋 A 右侧入口', 20, -12.9, 'buffer'),
		{ ...point('ref-bag-a', '套袋机 A 内部工位', 15, -12.9, 'processStation'), componentObjectId: 'reference-bagging-a', process: { type: 'bagging', cycleSeconds: 3 } },
		point('ref-a-bag-left', '套袋 A 左侧出口', 6.8, -12.9, 'buffer'),
		point('ref-bag-b-right-turn', '套袋 B 右侧转角', 21.5, -5.5, 'buffer'),
		point('ref-bag-b-right', '套袋 B 右侧入口', 20, -5.5, 'buffer'),
		{ ...point('ref-bag-b', '套袋机 B 内部工位', 14.5, -5.5, 'processStation'), componentObjectId: 'reference-bagging-b', process: { type: 'bagging', cycleSeconds: 3 } },
		point('ref-b-bag-left', '套袋 B 左侧出口', 6.8, -5.5, 'buffer'),
		{ ...point('ref-post-bag-merge', '双套袋左侧二合一', 6.8, -5.3, 'merger'), componentObjectId: 'reference-bag-merger' },
		point('ref-post-bag-up', '套袋后接入右上双排', 5.8, -5.3, 'buffer'),
		point('ref-loaded-upper-right-in', '右上双排上行入口', 4.9, -5.3, 'buffer'),
		point('ref-loaded-upper-right-out', '右上双排上行出口', 4.9, -17.7, 'buffer'),
		{
			...point('ref-gantry-pick', '桁架抓取丝锭工位', -12.7, -17.7, 'processStation'),
			componentObjectId: 'reference-stacking-gantry',
			process: {
				type: 'gantry-stacking',
				cycleSeconds: 3,
				batchSize: 6,
				batchLayout: robotLayout,
				behaviorCompletionGroups: ['yarn', 'separator'],
				behaviorCompletionRequirements: { yarn: 1, separator: 1 },
			},
		},
		{ ...point('ref-gantry-return-split', '桁架下双排空托分流位', -12.7, -16.5, 'diverter'), componentObjectId: 'reference-gantry-return-diverter', decisionMode: 'simulation' },
		point('ref-return-inner-bottom', '桁架下内排回流末端', -12.7, 9, 'buffer'),
		point('ref-return-outer-top', '桁架下外排回流起点', -14.6, -16.5, 'buffer'),
		{ ...point('ref-gantry-merger', '桁架双排/空托捷径公共汇流', -14.6, 9, 'merger'), componentObjectId: 'reference-gantry-merger' },
		{ ...point('ref-return-outer-bottom', '底部双排回机器人分流位', -14.6, 15.2, 'diverter'), componentObjectId: 'reference-bottom-return-diverter', decisionMode: 'simulation' },
		point('ref-return-bottom-a-turn', '底部 A 排回流转角', -14.6, 13.3, 'buffer'),
		point('ref-return-bottom-a-in', '底部 A 排左侧入口', -10.8, 13.3, 'buffer'),
		point('ref-return-bottom-in', '底部 B 排左侧入口', -10.8, 15.2, 'buffer'),
		point('ref-empty-return-upper-entry', '外检后单排空回流接入口', -1.5, 1.1, 'buffer'),
		point('ref-loaded-middle-tap', '单排空回流西端', -10.8, 1.1, 'buffer'),
		point('ref-empty-return-turn-b', '上排空托回流西侧下转角', -10.8, 9, 'buffer'),
	];

	const bottomLane = (options: Partial<TwinRouteEdgeDefinition> = {}) => ({ componentObjectId: 'reference-double-small-bottom', ...options });
	const middleLane = (options: Partial<TwinRouteEdgeDefinition> = {}) => ({ componentObjectId: 'reference-double-small-middle', ...options });
	const upperRightLane = (options: Partial<TwinRouteEdgeDefinition> = {}) => ({ componentObjectId: 'reference-double-small-upper-right', ...options });
	const upperLeftLane = (options: Partial<TwinRouteEdgeDefinition> = {}) => ({ componentObjectId: 'reference-double-small-upper-left', ...options });

	route.edges = [
		edge('ref-edge-robot-east', 'ref-robot-out', 'ref-robot-east', '底部 A 排：机器人向右', bottomLane({ capacity: 8, sectionId: 'ref-edge-robot-east' })),
		edge('ref-edge-robot-east-b', 'ref-robot-return', 'ref-robot-east-b', '底部 B 排：机器人向右', bottomLane({ capacity: 8, sectionId: 'ref-edge-robot-east-b' })),
		edge('ref-edge-bottom-a-merge', 'ref-robot-east', 'ref-bottom-merge', '底部 A 排进入二合一', { capacity: 2 }),
		edge('ref-edge-bottom-b-merge-x', 'ref-robot-east-b', 'ref-bottom-merge-b-turn', '底部 B 排进入二合一横段', { capacity: 2 }),
		edge('ref-edge-bottom-b-merge', 'ref-bottom-merge-b-turn', 'ref-bottom-merge', '底部 B 排进入二合一纵段', { capacity: 2 }),
		edge('ref-edge-inspection-right-rise', 'ref-bottom-merge', 'ref-inspection-east-turn', '双排合流后单线进入外检', { capacity: 5 }),
		edge('ref-edge-inspection-right-in', 'ref-inspection-east-turn', 'ref-inspection-right', '外检前单线进入外检', { capacity: 5 }),
		edge('ref-edge-inspection-in', 'ref-inspection-right', 'ref-inspection', '外检右进', { capacity: 3 }),
		edge('ref-edge-inspection-out', 'ref-inspection', 'ref-inspection-left', '外检左出', { capacity: 3 }),
		edge('ref-edge-inspection-to-diverter', 'ref-inspection-left', 'ref-empty-return-diverter', '外检后进入空托/有料分流', { capacity: 5 }),
		edge('ref-empty-return-loaded', 'ref-empty-return-diverter', 'ref-inspection-diverter', '有料托进入外检上方双排 A/B 分流', { priority: 10, capacity: 5 }),
		edge('ref-edge-diverter-a', 'ref-inspection-diverter', 'ref-a-middle-west', '外检后分入 A 排', { priority: 10, capacity: 4 }),
		edge('ref-edge-a-middle-east', 'ref-a-middle-west', 'ref-a-middle-east', '外检上方双排 A 排向右去套袋', middleLane({ priority: 10, capacity: 12, sectionId: 'ref-edge-a-middle-east' })),
		edge('ref-edge-a-bag-east', 'ref-a-middle-east', 'ref-a-bag-east-turn', 'A 排向外侧错位接入套袋', { priority: 10, capacity: 4 }),
		edge('ref-edge-a-bag-up', 'ref-a-bag-east-turn', 'ref-bag-a-right-turn', 'A 排上行至套袋 A', { priority: 10, capacity: 5 }),
		edge('ref-edge-bag-a-right-in', 'ref-bag-a-right-turn', 'ref-bag-a-right', '套袋 A 右侧接入', { priority: 10, capacity: 2 }),
		edge('ref-edge-bag-a', 'ref-bag-a-right', 'ref-bag-a', '套袋 A 由右进入', { priority: 10, capacity: 1 }),
		edge('ref-edge-bag-a-out', 'ref-bag-a', 'ref-a-bag-left', '套袋 A 向左输出', { priority: 10, capacity: 1 }),
		edge('ref-edge-bag-a-lane-down', 'ref-a-bag-left', 'ref-post-bag-merge', '套袋 A 沿右上双排下行汇流', upperRightLane({ priority: 10, capacity: 8, sectionId: 'ref-edge-bag-a-lane-down' })),
		edge('ref-edge-diverter-b', 'ref-inspection-diverter', 'ref-b-middle-west-turn', '外检后分入 B 排', { priority: 20, capacity: 4 }),
		edge('ref-edge-b-left-down', 'ref-b-middle-west-turn', 'ref-b-middle-west', 'B 排西侧转接', { priority: 20, capacity: 4 }),
		edge('ref-edge-b-middle-east', 'ref-b-middle-west', 'ref-b-middle-east', '外检上方双排 B 排向右去套袋', middleLane({ priority: 20, capacity: 12, sectionId: 'ref-edge-b-middle-east' })),
		edge('ref-edge-b-bag-up', 'ref-b-middle-east', 'ref-bag-b-right-turn', 'B 排上行至套袋 B', { priority: 20, capacity: 5 }),
		edge('ref-edge-bag-b-right-in', 'ref-bag-b-right-turn', 'ref-bag-b-right', '套袋 B 右侧接入', { priority: 20, capacity: 2 }),
		edge('ref-edge-bag-b', 'ref-bag-b-right', 'ref-bag-b', '套袋 B 由右进入', { priority: 20, capacity: 1 }),
		edge('ref-edge-bag-b-out', 'ref-bag-b', 'ref-b-bag-left', '套袋 B 向左输出', { priority: 20, capacity: 1 }),
		edge('ref-edge-bag-b-merge', 'ref-b-bag-left', 'ref-post-bag-merge', '套袋 B 接入左侧汇流', { priority: 20, capacity: 2 }),

		edge('ref-edge-post-bag-up', 'ref-post-bag-merge', 'ref-post-bag-up', '套袋汇流后向左接入右上双排', { capacity: 8 }),
		edge('ref-edge-loaded-upper-right-in', 'ref-post-bag-up', 'ref-loaded-upper-right-in', '套袋后直接进入右上双排', { capacity: 8 }),
		edge('ref-edge-loaded-upper-right', 'ref-loaded-upper-right-in', 'ref-loaded-upper-right-out', '右上双排内排向上', upperRightLane({ capacity: 8, sectionId: 'ref-edge-loaded-upper-right' })),
		edge('ref-edge-loaded-upper-north', 'ref-loaded-upper-right-out', 'ref-gantry-pick', '顶部向左送至桁架', { capacity: 12 }),

		edge('ref-gantry-edge-a-merge', 'ref-gantry-pick', 'ref-gantry-return-split', '桁架抓取后进入双排空托回流', { capacity: 2, sectionId: 'GantryEmptyReturn' }),
		edge('ref-gantry-inner-down', 'ref-gantry-return-split', 'ref-return-inner-bottom', '桁架下内排向机器人回流', upperLeftLane({ priority: 10, capacity: 12, sectionId: 'GantryEmptyReturn' })),
		edge('ref-gantry-merger-through', 'ref-return-inner-bottom', 'ref-gantry-merger', '桁架下内排接入公共汇流', { priority: 10, capacity: 4, sectionId: 'GantryEmptyReturn' }),
		edge('ref-gantry-edge-out', 'ref-gantry-return-split', 'ref-return-outer-top', '桁架空托切入外排', { priority: 20, capacity: 4, sectionId: 'GantryEmptyReturn' }),
		edge('ref-return-edge-outer-top', 'ref-return-outer-top', 'ref-gantry-merger', '桁架下外排向机器人回流', upperLeftLane({ priority: 20, capacity: 12, sectionId: 'GantryEmptyReturn' })),

		edge('ref-empty-return-down', 'ref-empty-return-diverter', 'ref-empty-return-upper-entry', '外检后空托进入独立单排回流', { priority: 20, capacity: 8, sectionId: 'EmptyReturnAfterInspection' }),
		edge('ref-empty-return-upper-west', 'ref-empty-return-upper-entry', 'ref-loaded-middle-tap', '外检上方独立单排空托向左回流', { priority: 20, capacity: 12, sectionId: 'EmptyReturnAfterInspection' }),
		edge('ref-empty-return-west-down', 'ref-loaded-middle-tap', 'ref-empty-return-turn-b', '上排空托沿西侧下行', { priority: 20, capacity: 8, sectionId: 'EmptyReturnAfterInspection' }),
		edge('ref-empty-return-merge', 'ref-empty-return-turn-b', 'ref-gantry-merger', '上排空托接入公共回机器人汇流', { priority: 20, capacity: 12, sectionId: 'EmptyReturnAfterInspection' }),
		edge('ref-return-edge-outer-down', 'ref-gantry-merger', 'ref-return-outer-bottom', '公共空托回流下行', { capacity: 18 }),
		edge('ref-return-edge-bottom-in-a', 'ref-return-outer-bottom', 'ref-return-bottom-a-turn', '空托分入底部 A 排', {
			priority: 10,
			capacity: 4,
			releasePermitBindingId: 'reference-robot-cross-a-release-permit',
			readyBindingId: 'reference-robot-cross-a-ready',
			blockedBindingId: 'reference-robot-cross-a-blocked',
			fullBindingId: 'reference-robot-cross-a-full',
		}),
		edge('ref-return-edge-bottom-a-turn', 'ref-return-bottom-a-turn', 'ref-return-bottom-a-in', '空托接入底部 A 排', { priority: 10, capacity: 4 }),
		edge('ref-return-edge-bottom-a', 'ref-return-bottom-a-in', 'ref-robot-out', '底部 A 排回机器人', bottomLane({ capacity: 8, sectionId: 'ref-return-edge-bottom-a' })),
		edge('ref-return-edge-bottom-in-b', 'ref-return-outer-bottom', 'ref-return-bottom-in', '空托分入底部 B 排', {
			priority: 20,
			capacity: 4,
			releasePermitBindingId: 'reference-robot-cross-b-release-permit',
			readyBindingId: 'reference-robot-cross-b-ready',
			blockedBindingId: 'reference-robot-cross-b-blocked',
			fullBindingId: 'reference-robot-cross-b-full',
		}),
		edge('ref-return-edge-bottom-b', 'ref-return-bottom-in', 'ref-robot-return', '底部 B 排回机器人', bottomLane({ capacity: 8, sectionId: 'ref-return-edge-bottom-b' })),
	];

	route.startPointId = 'ref-robot-out';
	route.loop = true;
	route.routingMode = 'automatic';
	route.junctionDecisions = {
		'ref-empty-return-diverter': 'ref-empty-return-loaded',
		'ref-inspection-diverter': 'ref-edge-diverter-a',
		'ref-gantry-return-split': 'ref-gantry-inner-down',
		'ref-return-outer-bottom': 'ref-return-edge-bottom-in-a',
	};
	route.decisionRules = [
		{ ruleId: 'reference-empty-return-rule', name: '外检后空托进入独立单排回流', junctionPointId: 'ref-empty-return-diverter', edgeId: 'ref-empty-return-down', source: 'payload', payloadKey: 'materialCount', operator: 'equals', matchValue: 0, priority: 200, enabled: true },
		{ ruleId: 'ref-rule-bag-b', name: 'B 类产品进入套袋机 B', junctionPointId: 'ref-inspection-diverter', edgeId: 'ref-edge-diverter-b', source: 'payload', payloadKey: 'routeCode', operator: 'equals', matchValue: 'B', priority: 100, enabled: true },
		{ ruleId: 'reference-gantry-return-inner', name: '桁架内排回流权重', junctionPointId: 'ref-gantry-return-split', edgeId: 'ref-gantry-inner-down', source: 'payload', payloadKey: 'palletId', operator: 'truthy', weight: 1, priority: 100, enabled: true },
		{ ruleId: 'reference-gantry-return-outer', name: '桁架外排回流权重', junctionPointId: 'ref-gantry-return-split', edgeId: 'ref-gantry-edge-out', source: 'payload', payloadKey: 'palletId', operator: 'truthy', weight: 1, priority: 100, enabled: true },
		{ ruleId: 'reference-bottom-lane-a-return-cross', name: '底部 A 排分流权重', junctionPointId: 'ref-return-outer-bottom', edgeId: 'ref-return-edge-bottom-in-a', source: 'payload', payloadKey: 'palletId', operator: 'truthy', weight: 1, priority: 100, enabled: true },
		{ ruleId: 'reference-bottom-lane-b-forward', name: '底部 B 排分流权重', junctionPointId: 'ref-return-outer-bottom', edgeId: 'ref-return-edge-bottom-in-b', source: 'payload', payloadKey: 'palletId', operator: 'truthy', weight: 1, priority: 100, enabled: true },
	];
	route.sections = [
		{ sectionId: 'EmptyReturnAfterInspection', name: '外检上方独立单排空托回流', enabled: true },
		{ sectionId: 'GantryEmptyReturn', name: '桁架抓取后双排空托回流', enabled: true },
	];
	for (const routePoint of route.points) {
		routePoint.authoring = { mode: 'manual', generatedKey: routePoint.pointId, locked: false, convertedFromGenerated: true };
	}
	for (const routeEdge of route.edges) {
		routeEdge.authoring = { mode: 'manual', generatedKey: routeEdge.edgeId, locked: false, convertedFromGenerated: true };
	}
	// 运行时的挡停器和到位传感器按 edge.componentObjectId 定位实体组件。
	// 手绘路线必须显式回指同一段辊道，否则托盘虽然沿线移动，实体挡停器不会动作。
	const embeddedEdgeObjects = new Map<string, string>([
		['ref-edge-inspection-in', 'reference-external-inspection'],
		['ref-edge-inspection-out', 'reference-external-inspection'],
		['ref-edge-bag-a', 'reference-bagging-a'],
		['ref-edge-bag-a-out', 'reference-bagging-a'],
		['ref-edge-bag-b', 'reference-bagging-b'],
		['ref-edge-bag-b-out', 'reference-bagging-b'],
		['ref-edge-bottom-a-merge', 'reference-bottom-b-to-inspection-merge'],
		['ref-edge-bottom-b-merge-x', 'reference-bottom-b-to-inspection-merge'],
		['ref-edge-bottom-b-merge', 'reference-bottom-b-to-inspection-merge'],
	]);
	const pointMap = new Map(route.points.map((item) => [item.pointId, item]));
	for (const routeEdge of route.edges) {
		if (routeEdge.componentObjectId) continue;
		const embeddedObjectId = embeddedEdgeObjects.get(routeEdge.edgeId);
		if (embeddedObjectId) {
			routeEdge.componentObjectId = embeddedObjectId;
			continue;
		}
		const from = pointMap.get(routeEdge.fromPointId);
		const to = pointMap.get(routeEdge.toPointId);
		if (from && to && Math.hypot(to.position[0] - from.position[0], to.position[2] - from.position[2]) >= 0.5) {
			routeEdge.componentObjectId = `reference-conveyor-${routeEdge.edgeId}`;
		}
	}
	for (const [pointId, componentPortId] of [
		['ref-robot-east', 'a-output'],
		['ref-robot-east-b', 'b-output'],
		['ref-b-middle-east', 'b-output'],
		['ref-loaded-middle-tap', 'a-output'],
		['ref-post-bag-merge', 'b-output'],
		['ref-loaded-upper-right-out', 'a-output'],
		['ref-return-inner-bottom', 'a-output'],
	] as const) {
		const target = pointMap.get(pointId);
		if (target) target.componentPortId = componentPortId;
	}
	return route;
};

const createSmallReturnRoute = (): TwinRouteDefinition => ({
	routeId: 'reference-small-pallet-return',
	name: '参考图单独单回流小辊道',
	type: 'conveyor',
	curveKind: 'line',
	defaultSpeed: 1.0,
	loop: false,
	orientToPath: true,
	points: [
		point('ref-return-start', '套袋后单回流接入口', 21.5, 3, 'station'),
		point('ref-return-east-top', '中部回流东端', 20, 3, 'buffer'),
		point('ref-return-east-bottom', '中部回流西端', -8.9, 3, 'buffer'),
		point('ref-return-west-bottom', '左侧单回流下端', -8.9, 14.7, 'buffer'),
		point('ref-return-robot', '机器人回流接收位', 0, 14.7, 'station'),
	],
	edges: [
		edge('ref-return-edge-top-east', 'ref-return-start', 'ref-return-east-top', '套袋后进入中部回流', { capacity: 4 }),
		edge('ref-return-edge-east-down', 'ref-return-east-top', 'ref-return-east-bottom', '中部双排回流线', { capacity: 14 }),
		edge('ref-return-edge-bottom-west', 'ref-return-east-bottom', 'ref-return-west-bottom', '左侧单回流纵段', { capacity: 14 }),
		edge('ref-return-edge-robot', 'ref-return-west-bottom', 'ref-return-robot', '底部双排回到机器人', { capacity: 8 }),
	],
	startPointId: 'ref-return-start',
	junctionDecisions: {},
	routingMode: 'manual',
	decisionRules: [],
});

const createGantryMergeRoute = (): TwinRouteDefinition => ({
	routeId: 'reference-gantry-merge-feed',
	name: '桁架后二合一小辊道',
	type: 'conveyor',
	curveKind: 'line',
	defaultSpeed: 0.8,
	loop: false,
	orientToPath: true,
	points: [
		point('ref-gantry-in-a', '桁架来料 A', -12.7, -18.8, 'station'),
		point('ref-gantry-a-turn', '桁架 A 转接', -12.7, -17.7, 'buffer'),
		point('ref-gantry-in-b', '桁架来料 B', -10.8, -18.8, 'station'),
		point('ref-gantry-merger', '桁架后二合一汇流位', -10.8, -17.7, 'merger'),
		point('ref-gantry-merged-out', '桁架汇流后单线', -8, -17.7, 'station'),
	],
	edges: [
		edge('ref-gantry-edge-a-down', 'ref-gantry-in-a', 'ref-gantry-a-turn', '桁架 A 路接入', { capacity: 3 }),
		edge('ref-gantry-edge-a-merge', 'ref-gantry-a-turn', 'ref-gantry-merger', '桁架 A 路汇流', { capacity: 2 }),
		edge('ref-gantry-edge-b-merge', 'ref-gantry-in-b', 'ref-gantry-merger', '桁架 B 路汇流', { capacity: 3 }),
		edge('ref-gantry-edge-out', 'ref-gantry-merger', 'ref-gantry-merged-out', '桁架二合一后单线', { capacity: 4 }),
	],
	startPointId: 'ref-gantry-in-a',
	junctionDecisions: {},
	routingMode: 'manual',
	decisionRules: [],
});

const createLargeRoute = (): TwinRouteDefinition => ({
	routeId: 'reference-large-pallet-line',
	name: '木托后包装大辊道',
	type: 'conveyor', curveKind: 'line', defaultSpeed: 0.65, loop: false, orientToPath: true,
	points: [
		{ ...point('ref-large-in', '空木托进入', LARGE_LINE_X, -4.2, 'station'), position: [LARGE_LINE_X, LARGE_HEIGHT, -4.2] },
		{ ...point('ref-large-stack', '2×3×8 码垛完成位', LARGE_LINE_X, -11, 'processStation'), position: [LARGE_LINE_X, LARGE_HEIGHT, -11], componentObjectId: 'reference-stacking-pallet', process: { type: 'wood-stack-ready', cycleSeconds: 1 } },
		{ ...point('ref-large-cover', '天盖桁架工位', LARGE_LINE_X, -23.2, 'processStation'), position: [LARGE_LINE_X, LARGE_HEIGHT, -23.2], componentObjectId: 'reference-top-cover-gantry', process: { type: 'top-cover', cycleSeconds: 3 } },
		{ ...point('ref-large-wrap', '缠膜工位', LARGE_LINE_X, -35.7, 'processStation'), position: [LARGE_LINE_X, LARGE_HEIGHT, -35.7], componentObjectId: 'reference-wrapper', process: { type: 'wrapping', cycleSeconds: 8 } },
		{ ...point('ref-large-label', '贴标工位', LARGE_LINE_X, -47.2, 'processStation'), position: [LARGE_LINE_X, LARGE_HEIGHT, -47.2], componentObjectId: 'reference-labeling', process: { type: 'labeling', cycleSeconds: 2 } },
		{ ...point('ref-large-out', '成品出库', LARGE_LINE_X, -58.7, 'station'), position: [LARGE_LINE_X, LARGE_HEIGHT, -58.7] },
	],
	edges: [
		edge('ref-large-edge-in', 'ref-large-in', 'ref-large-stack', '空木托到码垛位', { capacity: 2, conveyorSizeClass: 'large', transportUnitType: 'wooden-pallet' }),
		edge('ref-large-edge-cover', 'ref-large-stack', 'ref-large-cover', '满托到天盖', { capacity: 2, conveyorSizeClass: 'large', transportUnitType: 'wooden-pallet' }),
		edge('ref-large-edge-wrap', 'ref-large-cover', 'ref-large-wrap', '天盖后到缠膜', { capacity: 2, conveyorSizeClass: 'large', transportUnitType: 'wooden-pallet' }),
		edge('ref-large-edge-label', 'ref-large-wrap', 'ref-large-label', '缠膜后到贴标', { capacity: 2, conveyorSizeClass: 'large', transportUnitType: 'wooden-pallet' }),
		edge('ref-large-edge-out', 'ref-large-label', 'ref-large-out', '贴标后成品出库', { capacity: 2, conveyorSizeClass: 'large', transportUnitType: 'wooden-pallet' }),
	],
	startPointId: 'ref-large-in', junctionDecisions: {}, routingMode: 'manual', decisionRules: [],
});

/**
 * 图纸中上部的内环不是 360° 圆环，而是底部开口的约 270° 马蹄形缓存。
 * 保留旧 routeId reference-central-ring，确保 V1 发布版本可无损迁移。
 */
const createCentralBufferRoute = (): TwinRouteDefinition => {
	const centerX = -4, centerZ = -10, radius = 4.2;
	const angles = [135, 180, 225, 270, 315, 360, 405].map((degrees) => degrees * Math.PI / 180);
	const points = angles.map((angle, index) => point(
		`ref-ring-${index + 1}`,
		`中央马蹄形缓存 ${index + 1}`,
		centerX + Math.cos(angle) * radius,
		centerZ + Math.sin(angle) * radius,
		index === 0 || index === angles.length - 1 ? 'station' : 'buffer',
	));
	return {
		routeId: 'reference-central-ring', name: '中央马蹄形缓存辊道', type: 'conveyor', curveKind: 'catmullRom', defaultSpeed: 0.8, loop: false, orientToPath: true,
		points,
		edges: points.slice(0, -1).map((item, index) => edge(`ref-ring-edge-${index + 1}`, item.pointId, points[index + 1].pointId, `马蹄形缓存 ${index + 1}`, { capacity: 2 })),
		startPointId: points[0].pointId, junctionDecisions: {}, routingMode: 'manual', decisionRules: [],
	};
};

/** 中央马蹄形缓存外侧的矩形辊道框，与图纸上方矩形框对应。 */
const createUpperFrameRoute = (): TwinRouteDefinition => ({
	routeId: 'reference-upper-frame',
	name: '中央缓存外层矩形辊道框（按图校准）',
	type: 'conveyor', curveKind: 'line', defaultSpeed: 0.8, loop: true, orientToPath: true,
	points: [
		point('ref-upper-frame-nw', '外框左上', -12.7, -17.7, 'buffer'),
		point('ref-upper-frame-ne', '外框右上', 6.8, -17.7, 'buffer'),
		point('ref-upper-frame-se', '外框右下', 6.8, -5.3, 'buffer'),
		point('ref-upper-frame-se-inner', '外框右下内收', 4.9, -5.3, 'buffer'),
		point('ref-upper-frame-sw', '外框左下内端', -8.9, -5.3, 'buffer'),
		point('ref-upper-frame-sw-outer', '外框左下外端', -12.7, -5.3, 'buffer'),
	],
	edges: [
		edge('ref-upper-frame-north', 'ref-upper-frame-nw', 'ref-upper-frame-ne', '外框上横段', { capacity: 10 }),
		edge('ref-upper-frame-east', 'ref-upper-frame-ne', 'ref-upper-frame-se', '外框右竖段', { capacity: 10 }),
		edge('ref-upper-frame-south-east', 'ref-upper-frame-se', 'ref-upper-frame-se-inner', '外框右下短接段', { capacity: 2 }),
		edge('ref-upper-frame-south', 'ref-upper-frame-se-inner', 'ref-upper-frame-sw', '外框下横段', { capacity: 10 }),
		edge('ref-upper-frame-south-west', 'ref-upper-frame-sw', 'ref-upper-frame-sw-outer', '外框左下短接段', { capacity: 3 }),
		edge('ref-upper-frame-west', 'ref-upper-frame-sw-outer', 'ref-upper-frame-nw', '外框左竖段', { capacity: 10 }),
	],
	startPointId: 'ref-upper-frame-nw', junctionDecisions: {}, routingMode: 'manual', decisionRules: [],
});

/**
 * 依据用户提供的最新标注图创建独立的组件化 3D 产线 V11。
 * 以中央机器人 (-4,-10) 为标定原点，按约 0.06m/像素校准主要设备和辊道锚点。
 */
export const buildReferencePackagingLineTwinSceneManifest = (): TwinSceneManifest => {
	const manifest = createBlankTwinSceneManifest();
	manifest.name = `参考图双套袋环形包装产线 V${REFERENCE_PACKAGING_LAYOUT_VERSION}`;
	manifest.description = '标准引擎完整闭环：机器人/桁架跨设备动作全部来自场景编排；机器人下直角交叉口 Simulation 仅按 weight 分流，Live 仅按 ReleasePermit/Ready/Blocked/Full 互锁放行。';
	manifest.world.background = '#08111f';
	// 物理布局退回 V9 基线。后续遥测、动作编排、Live/Simulation 等运行能力继续保留；
	// 这里只恢复当时的设备/辊道几何脚手架，不做功能版本回退。
	const smallRoute = createV9SmallMainLayoutRoute();
	const returnRoute = createSmallReturnRoute();
	const gantryMergeRoute = createGantryMergeRoute();
	const largeRoute = createLargeRoute();
	const ringRoute = createCentralBufferRoute();
	const upperFrameRoute = createUpperFrameRoute();
	const layoutScaffoldRoutes = [smallRoute, returnRoute, gantryMergeRoute, largeRoute, ringRoute, upperFrameRoute];

	const objects: TwinV7SceneObjectDefinition[] = [];
	const doubleVisualEdges = new Set([
		// V9：这些 Route 已由双排小辊道实体承载，禁止再叠加单辊道。
		'ref-edge-robot-east',
		'ref-edge-a-left-up',
		'ref-edge-diverter-b',
		'ref-edge-b-middle-east',
		'ref-return-edge-east-down',
		'ref-return-edge-robot',
		'ref-gantry-edge-a-down',
		'ref-gantry-edge-b-merge',
		'ref-upper-frame-west',
		'ref-upper-frame-east',
	]);
	const processEmbeddedEdges = new Set([
		// 外检和套袋组件内部已经包含真实辊道，再自动生成会产生重叠和闪烁。
		'ref-edge-inspection-in',
		'ref-edge-inspection-out',
		'ref-edge-bag-a',
		'ref-edge-bag-a-out',
		'ref-edge-bag-b',
		'ref-edge-bag-b-out',
	]);
	for (const route of layoutScaffoldRoutes.filter((item) => item.routeId !== ringRoute.routeId)) {
		for (const routeEdge of route.edges) {
			if (doubleVisualEdges.has(routeEdge.edgeId) || processEmbeddedEdges.has(routeEdge.edgeId)) continue;
			const conveyor = straightComponentForEdge(route, routeEdge);
			if (conveyor) objects.push(conveyor);
		}
	}
	// V9 的四组双排小辊道原始几何。
	objects.push(
		componentObject('builtin-double-small-roller-conveyor', 'reference-double-small-upper-left', '左上竖向双排小辊道', [-11.75, 0, -5.45], Math.PI / 2, {
			length: 24.5, laneWidth: 1.55, laneSpacing: 1.9, height: SMALL_HEIGHT, capacityPerLane: 8,
			laneAReverse: true, laneBReverse: true,
		}, 'ref-double-upper-left'),
		componentObject('builtin-double-small-roller-conveyor', 'reference-double-small-upper-right', '右上竖向双排小辊道', [5.85, 0, -11.5], Math.PI / 2, {
			length: 12.4, laneWidth: 1.55, laneSpacing: 1.9, height: SMALL_HEIGHT, capacityPerLane: 8,
		}, 'ref-double-upper-right'),
		componentObject('builtin-double-small-roller-conveyor', 'reference-double-small-middle', '中部横向双排小辊道', [6.3, 0, 2.05], 0, {
			length: 30.4, laneWidth: 1.55, laneSpacing: 1.9, height: SMALL_HEIGHT, capacityPerLane: 12,
			laneAReverse: true, laneBReverse: false,
		}, 'ref-double-middle'),
		componentObject('builtin-double-small-roller-conveyor', 'reference-double-small-bottom', '底部横向双排小辊道', [1.1, 0, 13.75], 0, {
			length: 23.8, laneWidth: 1.55, laneSpacing: 1.9, height: SMALL_HEIGHT, capacityPerLane: 12,
		}, 'ref-double-bottom'),
	);

	// 内侧马蹄形只使用三个 90° 转弯辊道：135° -> 405°，在世界 +Z（图纸下方）留下 90° 开口。
	const horseshoeQuarterRotations = [3 * Math.PI / 4, Math.PI / 4, -Math.PI / 4];
	for (let quadrant = 0; quadrant < horseshoeQuarterRotations.length; quadrant += 1) {
		objects.push(componentObject(
			'builtin-turn-conveyor-90',
			`reference-ring-quarter-${quadrant + 1}`,
			`中央马蹄形缓存 ${quadrant + 1}/3`,
			[-4, 0, -10],
			horseshoeQuarterRotations[quadrant],
			{ radius: 4.2, width: 1.55, height: SMALL_HEIGHT, turnDirection: 'left', capacity: 2, transportUnitType: 'plastic-pallet' },
			`ref-ring-quarter-${quadrant + 1}`,
		));
	}

	objects.push(
		componentObject('builtin-industrial-robot', 'reference-center-robot', '中央马蹄形缓存机器人', [-4, 0, -10], 0, {}, 'ref-center-robot'),
		componentObject('builtin-bagging-machine', 'reference-bagging-a', '套袋机 A', [15, 0, -12.9], 0, { length: 6.4, cycleSeconds: 3 }, 'ref-bag-a'),
		componentObject('builtin-bagging-machine', 'reference-bagging-b', '套袋机 B', [14.5, 0, -5.5], 0, { length: 6.4, cycleSeconds: 3 }, 'ref-bag-b'),
		componentObject('builtin-external-inspection', 'reference-external-inspection', '外检机', [4.6, 0, 6.8], Math.PI, { length: 6.8, cycleSeconds: 2 }, 'ref-inspection'),
		componentObject('builtin-diverter-conveyor', 'reference-inspection-diverter', '外检后一分二辊道', [-10.8, 0, 6.8], Math.PI / 2, { capacity: 2 }, 'ref-inspection-diverter'),
		componentObject('builtin-merger-conveyor', 'reference-bag-merger', '双套袋后二合一辊道', [21.5, 0, -5.5], 0, { capacity: 2 }, 'ref-post-bag-merge'),
		componentObject('builtin-merger-conveyor', 'reference-gantry-merger', '桁架后二合一辊道', [-10.8, 0, -17.7], 0, { capacity: 2 }, 'ref-gantry-merger'),
		// 丝锭桁架内部的暂存台位于本地 Z-；Y+90° 后它落到世界 X-，即大辊道左侧，符合图纸。
		componentObject('builtin-silk-gantry', 'reference-stacking-gantry', '码垛桁架和暂存台', [LARGE_LINE_X, 0, -11], Math.PI / 2, { length: 7.2, width: 17.5, height: 7.2 }, 'ref-large-stack'),
		// 固定对象只作为码垛语义锚点；初始化不画木托，真实/仿真木托由 RouteSlot runtime 进入。
		componentObject('builtin-wooden-pallet', 'reference-stacking-pallet', '码垛位木托工位', [LARGE_LINE_X, LARGE_HEIGHT, -11], Math.PI / 2, { length: 4.5, width: 2.1, height: 0.18, semanticOnly: true }, 'ref-large-stack-pallet'),
		componentObject('builtin-top-cover-gantry', 'reference-top-cover-gantry', '天盖桁架', [LARGE_LINE_X, 0, -23.2], LARGE_LINE_ROTATION_Y, { length: 7.05, width: 10.5, height: 6.0 }, 'ref-large-cover'),
		componentObject('builtin-wrapper-machine', 'reference-wrapper', '缠膜机', [LARGE_LINE_X, 0, -35.7], LARGE_LINE_ROTATION_Y, { height: 6.2, armRadius: 3.0, width: 6.8 }, 'ref-large-wrap'),
		componentObject('builtin-labeling-machine', 'reference-labeling', '贴标机', [LARGE_LINE_X, 0, -47.2], LARGE_LINE_ROTATION_Y, { height: 2.4, sideOffset: 1.85, armReach: 0.6 }, 'ref-large-label'),
		componentObject('builtin-industrial-robot', 'reference-loading-robot', '底部六轴机器人+2×6丝锭夹具', [0.4, 0, 19.8], 0, { toolType: 'silk-grid-2x6', gripperSpan: 6.6, gripperRowSpacing: 1.15, upperArmLength: 2.4, forearmLength: 2.2, axis1HomeYaw: 0, axis2HomePitch: -0.48, axis3HomePitch: Math.PI / 2 + 0.48 }, 'ref-robot'),
		componentObject('builtin-turntable', 'reference-turntable-west', '西侧旋转台+双面丝车', [-5.2, 0, 19.8], Math.PI / 2, { withSilkCart: true, silkCartLoaded: true, deckLength: 7.2, width: 2.8, height: SMALL_HEIGHT, baseRadius: 2.45 }, 'ref-turntable-west'),
		componentObject('builtin-turntable', 'reference-turntable-east', '东侧旋转台+双面丝车', [6, 0, 19.8], Math.PI / 2, { withSilkCart: true, silkCartLoaded: true, deckLength: 7.2, width: 2.8, height: SMALL_HEIGHT, baseRadius: 2.45 }, 'ref-turntable-east'),
	);
	manifest.objects = objects as TwinSceneManifest['objects'];
	manifest.bindings = [];
	for (const lane of ['a', 'b'] as const) {
		for (const signal of ['release-permit', 'ready', 'blocked', 'full'] as const) {
			const signalKey = signal === 'release-permit' ? 'ReleasePermit' : `${signal[0].toUpperCase()}${signal.slice(1)}`;
			manifest.bindings.push({
				bindingId: `reference-robot-cross-${lane}-${signal}`,
				objectId: 'reference-double-small-bottom',
				// 参考场景不硬编码租户设备。现场绑定设备后再把 source 切换为 telemetry 并启用。
				source: { kind: 'simulation', key: `RobotCross.${lane.toUpperCase()}.${signalKey}` },
				target: { kind: 'customProperty', property: `routeInterlock.${signalKey}` },
				transform: { kind: 'routeEvent' },
				staleAfterMs: 5000,
				enabled: false,
			});
		}
	}
	manifest.routes = [];
	const topologyConnections = buildReferenceTopologyConnections(manifest, layoutScaffoldRoutes);
	const reservedConnections = [...topologyConnections];
	manifest.connections = [...reservedConnections, ...buildReferenceTouchingConnections(manifest, 0.18, reservedConnections)];
	upsertGeneratedComponentRoutes(manifest);
	const smallProcessRoute = createV9RuntimeSmallPalletRoute();
	// V9 的物理组件网络仍全部保留；主运行路线单独放在第一位，避免中央马蹄缓存
	// 因 edge 数量更大而被误判为 primarySmallPalletRouteId。
	manifest.routes = manifest.routes.filter((route) => route.routeId !== smallProcessRoute.routeId);
	manifest.routes.unshift(smallProcessRoute);
	const woodenProcessRoute = manifest.routes
		.filter((route) => route.edges.some((edge) => edge.conveyorSizeClass === 'large' && edge.transportUnitType === 'wooden-pallet'))
		.sort((left, right) => right.edges.length - left.edges.length)[0];
	if (woodenProcessRoute) {
		const nearestPoint = (x: number, z: number) => [...woodenProcessRoute.points].sort((left, right) => Math.hypot(left.position[0] - x, left.position[2] - z) - Math.hypot(right.position[0] - x, right.position[2] - z))[0];
		for (const station of [
			{ x: LARGE_LINE_X, z: -11, objectId: 'reference-stacking-pallet', type: 'wood-stack-ready', cycleSeconds: 1 },
			{ x: LARGE_LINE_X, z: -23.2, objectId: 'reference-top-cover-gantry', type: 'top-cover', cycleSeconds: 3 },
			{ x: LARGE_LINE_X, z: -35.7, objectId: 'reference-wrapper', type: 'wrapping', cycleSeconds: 8 },
			{ x: LARGE_LINE_X, z: -47.2, objectId: 'reference-labeling', type: 'labeling', cycleSeconds: 2 },
		]) {
			const processPoint = nearestPoint(station.x, station.z);
			if (!processPoint) continue;
			processPoint.kind = 'processStation';
			processPoint.componentObjectId = station.objectId;
			processPoint.process = { type: station.type, cycleSeconds: station.cycleSeconds, batchSize: 1 };
		}
		woodenProcessRoute.name = '木托后包装完整工艺（码垛→天盖→缠膜→贴标→出库）';
		woodenProcessRoute.loop = false;
	}
	manifest.runtime = {
		dataMode: 'simulation', maxPixelRatio: 2, showGrid: true,
		referencePackagingLayoutVersion: REFERENCE_PACKAGING_LAYOUT_VERSION,
		primarySmallPalletRouteId: smallProcessRoute?.routeId,
		primaryWoodenPalletRouteId: woodenProcessRoute?.routeId,
	};
	return manifest;
};

/**
 * 参考线本身就是 3D 场景设计器导出的普通 TwinSceneManifest 数据资产。
 * 新建场景只实例化该资产并生成新的 sceneId；动作编排不再由 Builder/Runtime 注入。
 */
export const createReferencePackagingLineTwinSceneManifest = (): TwinSceneManifest => {
	const manifest = structuredClone(referencePackagingSceneV19) as TwinSceneManifest;
	manifest.sceneId = createBlankTwinSceneManifest().sceneId;
	return manifest;
};

const referenceRouteIds = new Set([
	'component-route-d045206d',
	'component-route-68147065',
	'reference-small-pallet-main',
	'reference-small-pallet-return',
	'reference-gantry-merge-feed',
	'reference-bottom-lane-b',
	'reference-large-pallet-line',
	'reference-central-ring',
	'reference-upper-frame',
	// V3 曾把双排第二排拆成独立 Route；V4 迁移必须主动清掉这些历史孤立路线。
	'reference-double-upper-left-lane-b',
	'reference-double-middle-lane-b',
	'reference-double-bottom-lane-b',
]);
const stableReferenceObjectIds = [
	'reference-loading-robot',
	'reference-bagging-a',
	'reference-bagging-b',
	'reference-stacking-gantry',
];
const edgeBindingFields = ['releasePermitBindingId', 'readyBindingId', 'occupancyBindingId', 'fullBindingId', 'blockedBindingId', 'conveyorObjectId'] as const;

const mergeRouteForUpgrade = (canonical: TwinRouteDefinition, previous?: TwinRouteDefinition): TwinRouteDefinition => {
	if (!previous) return structuredClone(canonical);
	const previousPoints = new Map(previous.points.map((item) => [item.pointId, item]));
	const previousEdges = new Map(previous.edges.map((item) => [item.edgeId, item]));
	const route = structuredClone(canonical);
	for (const routePoint of route.points) {
		const old = previousPoints.get(routePoint.pointId);
		if (!old) continue;
		if (old.actuatorBindingId) routePoint.actuatorBindingId = old.actuatorBindingId;
		if (old.sensorBindingId) routePoint.sensorBindingId = old.sensorBindingId;
		if (routePoint.process && old.process) {
			for (const field of ['readyBindingId', 'busyBindingId', 'completeBindingId', 'resultBindingId', 'faultBindingId'] as const) {
				if (old.process[field]) routePoint.process[field] = old.process[field];
			}
		}
	}
	for (const routeEdge of route.edges) {
		const old = previousEdges.get(routeEdge.edgeId);
		if (!old) continue;
		for (const field of edgeBindingFields) if (old[field] !== undefined) (routeEdge as any)[field] = old[field];
	}
	return route;
};

const mergeReferenceObject = (
	canonical: TwinV7SceneObjectDefinition,
	previousObjects: TwinV7SceneObjectDefinition[],
	claimedPreviousIds: Set<string>,
): TwinV7SceneObjectDefinition => {
	let previous = previousObjects.find((item) => item.objectId === canonical.objectId && !claimedPreviousIds.has(item.objectId));
	if (!previous && canonical.kind === 'component') {
		previous = previousObjects.find((item) => item.kind === 'component'
			&& !claimedPreviousIds.has(item.objectId)
			&& item.component?.sectionId === canonical.component?.sectionId
			&& item.component?.properties?.referenceDrawingLine === true);
	}
	const merged = structuredClone(canonical);
	if (!previous) return merged;
	claimedPreviousIds.add(previous.objectId);
	// 旧 V1 的 numeric conveyor objectId 可能已经被 Binding 引用；匹配到同一 section 时继续沿用旧 ID。
	merged.objectId = previous.objectId;
	if (previous.assetId) merged.assetId = previous.assetId;
	if (previous.resourceId && (!(merged.kind === 'component' && previous.kind === 'component') || previous.component?.resourceKey === merged.component?.resourceKey)) merged.resourceId = previous.resourceId;
	if (merged.kind === 'component' && previous.kind === 'component' && merged.component && previous.component) {
		merged.component.properties = {
			...structuredClone(previous.component.properties || {}),
			...structuredClone(merged.component.properties || {}),
		};
		delete (merged.component.properties as any).routeManagedExternally;
		if (previous.component.bindings) merged.component.bindings = structuredClone(previous.component.bindings);
	}
	return merged;
};

/**
 * 将旧参考图草稿或不可变发布 Manifest 在内存中升级为当前布局版本。
 * 只替换参考图自带 routes / referenceDrawingLine objects；用户额外放入的对象、资源和 Binding 保留。
 */
export const upgradeReferencePackagingLineLayout = (manifest: TwinSceneManifest): boolean => {
	const currentLayoutVersion = Number(manifest.runtime?.referencePackagingLayoutVersion || 0);
	const canonicalForHealthCheck = currentLayoutVersion >= REFERENCE_PACKAGING_LAYOUT_VERSION
		? createReferencePackagingLineTwinSceneManifest()
		: undefined;
	const canonicalSmallRouteId = canonicalForHealthCheck?.runtime.primarySmallPalletRouteId;
	const canonicalWoodRouteId = canonicalForHealthCheck?.runtime.primaryWoodenPalletRouteId;
	const currentInitializers = manifest.runtime?.routePalletInitializers || [];
	const currentBehaviorIds = new Set((manifest.behaviors || []).map((item) => item.behaviorId));
	const currentMaterialSlotIds = new Set((manifest.materialSlots || []).map((item) => item.slotId));
	const currentInterlockIds = new Set((manifest.interlocks || []).map((item) => item.interlockId));
	const currentBindingIds = new Set((manifest.bindings || []).map((item) => item.bindingId));
	const hasContactSafeRobotPlacement = ['reference-v12-robot-pick-west', 'reference-v12-robot-pick-east'].every((behaviorId) => {
		const behavior = (manifest.behaviors || []).find((item) => item.behaviorId === behaviorId);
		const placeAction = behavior?.actions.find((action) => action.actionId.endsWith('-detach'));
		const safeTransferAction = behavior?.actions.find((action) => action.actionId.endsWith('-safe-transfer'));
		return placeAction?.kind === 'place' && Array.isArray(placeAction.approachOffset)
			&& safeTransferAction?.kind === 'moveTo'
			&& safeTransferAction.workPointId === placeAction.workPointId
			&& Array.isArray(safeTransferAction.approachOffset)
			&& Number(safeTransferAction.approachOffset[1] || 0) >= 1.5
			&& behavior!.actions.indexOf(safeTransferAction) < behavior!.actions.indexOf(placeAction);
	});
	const currentLargeOut = ((manifest.objects || []) as TwinV7SceneObjectDefinition[]).find((item) => item.objectId === 'reference-conveyor-ref-large-edge-out');
	const canonicalLargeOut = ((canonicalForHealthCheck?.objects || []) as TwinV7SceneObjectDefinition[]).find((item) => item.objectId === 'reference-conveyor-ref-large-edge-out');
	const hasCanonicalLargeAxis = Boolean(currentLargeOut && canonicalLargeOut
		&& Math.abs(currentLargeOut.transform.position[0] - canonicalLargeOut.transform.position[0]) < 0.001
		&& Math.abs(currentLargeOut.transform.position[2] - canonicalLargeOut.transform.position[2]) < 0.001
		&& Math.abs(currentLargeOut.transform.rotation[1] - canonicalLargeOut.transform.rotation[1]) < 0.001);
	const isReferenceSmallConveyor = (item: TwinV7SceneObjectDefinition) => item.kind === 'component'
		&& item.component?.properties?.referenceDrawingLine === true
		&& (item.component.properties.conveyorSizeClass === 'small'
			|| ['double-small-roller-conveyor', 'turn-conveyor-90', 'diverter-conveyor', 'merger-conveyor'].includes(String(item.component.componentType || '')));
	const currentSmallObjects = ((manifest.objects || []) as TwinV7SceneObjectDefinition[]).filter(isReferenceSmallConveyor);
	const canonicalSmallObjects = ((canonicalForHealthCheck?.objects || []) as TwinV7SceneObjectDefinition[]).filter(isReferenceSmallConveyor);
	const currentSmallById = new Map(currentSmallObjects.map((item) => [item.objectId, item]));
	const canonicalSmallPropertyKeys = ['length', 'laneSpacing', 'laneAReverse', 'laneBReverse'] as const;
	const hasCanonicalSmallPlane = canonicalSmallObjects.length > 0 && canonicalSmallObjects.every((canonicalObject) => {
		const currentObject = currentSmallById.get(canonicalObject.objectId);
		if (!currentObject) return false;
		const canonicalHeight = Number(canonicalObject.component?.properties?.height ?? SMALL_HEIGHT);
		const currentHeight = Number(currentObject.component?.properties?.height ?? SMALL_HEIGHT);
		const sameTransform = currentObject.transform.position.every((value, index) => Math.abs(value - canonicalObject.transform.position[index]) < 0.001)
			&& currentObject.transform.rotation.every((value, index) => Math.abs(value - canonicalObject.transform.rotation[index]) < 0.001);
		const sameRoutingProperties = canonicalSmallPropertyKeys.every((key) => {
			const canonicalValue = canonicalObject.component?.properties?.[key];
			const currentValue = currentObject.component?.properties?.[key];
			if (typeof canonicalValue === 'number' || typeof currentValue === 'number') return Math.abs(Number(currentValue || 0) - Number(canonicalValue || 0)) < 0.001;
			return Boolean(currentValue) === Boolean(canonicalValue);
		});
		return sameTransform
			&& sameRoutingProperties
			&& Math.abs(currentHeight - canonicalHeight) < 0.001;
	});
	const currentWoodRoute = canonicalWoodRouteId ? (manifest.routes || []).find((item) => item.routeId === canonicalWoodRouteId) : undefined;
	const currentWoodProcessTypes = currentWoodRoute?.points.filter((item) => item.kind === 'processStation' && item.process).map((item) => item.process!.type) || [];
	const currentSmallRoute = canonicalSmallRouteId ? (manifest.routes || []).find((item) => item.routeId === canonicalSmallRouteId) : undefined;
	const loadingPoints = currentSmallRoute?.points.filter((item) => item.componentObjectId === 'reference-loading-robot' && item.kind === 'processStation' && item.process) || [];
	const canonicalLoadingPoints = canonicalForHealthCheck?.routes.find((item) => item.routeId === canonicalSmallRouteId)?.points.filter((item) => item.componentObjectId === 'reference-loading-robot' && item.kind === 'processStation' && item.process) || [];
	const hasCanonicalLoadingLanes = loadingPoints.length === 2 && ['A', 'B'].every((lane) => {
		const current = loadingPoints.find((point) => point.process?.physicalLane === lane);
		const canonical = canonicalLoadingPoints.find((point) => point.process?.physicalLane === lane);
		return Boolean(current && canonical
			&& current.process?.simulationEntry === true
			&& current.process?.releaseEdgeId === canonical.process?.releaseEdgeId
			&& current.process?.batchLayout?.rows === 1
			&& current.process?.batchLayout?.columns === 6
			&& Math.abs(Number(current.process?.batchLayout?.columnSpacingMeters || 0) - 1.55) < 0.001
			&& Math.hypot(current.position[0] - canonical.position[0], current.position[2] - canonical.position[2]) < 0.001);
	});
	const hasCanonicalSmallRouteTopology = Boolean(currentSmallRoute
		&& hasCanonicalLoadingLanes
		&& currentSmallRoute.generatedBy !== 'component-connections'
		&& currentSmallRoute.edges.some((edge) => edge.edgeId === 'ref-edge-robot-east-b')
		&& currentSmallRoute.edges.some((edge) => edge.edgeId === 'ref-edge-bottom-b-merge')
		&& currentSmallRoute.edges.some((edge) => edge.edgeId === 'ref-empty-return-down')
		&& currentSmallRoute.edges.some((edge) => edge.edgeId === 'ref-empty-return-merge')
		&& currentSmallRoute.edges.some((edge) => edge.edgeId === 'ref-gantry-merger-through')
		&& currentSmallRoute.decisionRules.some((rule) => rule.ruleId === 'reference-empty-return-rule' && rule.payloadKey === 'materialCount' && rule.matchValue === 0));
	const canonicalSmallRoute = canonicalForHealthCheck?.routes.find((item) => item.routeId === canonicalSmallRouteId);
	const canonicalCrossRuleIds = ['reference-bottom-lane-b-forward', 'reference-bottom-lane-a-return-cross'];
	const hasCanonicalRobotCrossRouting = Boolean(currentSmallRoute && canonicalSmallRoute
		&& canonicalCrossRuleIds.every((ruleId) => {
			const currentRule = currentSmallRoute.decisionRules.find((item) => item.ruleId === ruleId);
			const canonicalRule = canonicalSmallRoute.decisionRules.find((item) => item.ruleId === ruleId);
			if (!currentRule || !canonicalRule || currentRule.payloadKey !== 'palletId' || currentRule.operator !== 'truthy' || !(Number(currentRule.weight) > 0)) return false;
			const edge = currentSmallRoute.edges.find((item) => item.edgeId === currentRule.edgeId);
			return Boolean(edge?.releasePermitBindingId && edge.readyBindingId && edge.blockedBindingId && edge.fullBindingId);
		}));
	const currentStackingPallet = ((manifest.objects || []) as TwinV7SceneObjectDefinition[]).find((item) => item.objectId === 'reference-stacking-pallet');
	const canonicalStackingPallet = ((canonicalForHealthCheck?.objects || []) as TwinV7SceneObjectDefinition[]).find((item) => item.objectId === 'reference-stacking-pallet');
	const hasCanonicalWoodPalletSize = Boolean(currentStackingPallet && canonicalStackingPallet
		&& Math.abs(Number(currentStackingPallet.component?.properties?.length || 0) - Number(canonicalStackingPallet.component?.properties?.length || 0)) < 0.001
		&& Math.abs(Number(currentStackingPallet.component?.properties?.width || 0) - Number(canonicalStackingPallet.component?.properties?.width || 0)) < 0.001);
	const hasCurrentLayoutStructure = Boolean(canonicalForHealthCheck
		&& canonicalSmallRouteId
		&& canonicalWoodRouteId
		&& manifest.runtime.primarySmallPalletRouteId === canonicalSmallRouteId
		&& manifest.runtime.primaryWoodenPalletRouteId === canonicalWoodRouteId
		&& currentInitializers.some((item) => item.routeId === canonicalSmallRouteId && item.simulationDefaultCount === 12)
		&& currentInitializers.some((item) => item.routeId === canonicalWoodRouteId && item.simulationDefaultCount === 0 && item.simulationAutoFeed === true)
		&& hasCanonicalLargeAxis
		&& hasCanonicalSmallPlane
		&& hasCanonicalSmallRouteTopology
		&& hasCanonicalRobotCrossRouting
		&& hasCanonicalWoodPalletSize
		&& hasContactSafeRobotPlacement
		&& ['wood-stack-ready', 'top-cover', 'wrapping', 'labeling'].every((type) => currentWoodProcessTypes.includes(type))
		&& (canonicalForHealthCheck.behaviors || []).every((item) => currentBehaviorIds.has(item.behaviorId))
		&& (canonicalForHealthCheck.materialSlots || []).every((item) => currentMaterialSlotIds.has(item.slotId))
		&& (canonicalForHealthCheck.bindings || []).every((item) => currentBindingIds.has(item.bindingId))
		&& (canonicalForHealthCheck.interlocks || []).every((item) => currentInterlockIds.has(item.interlockId)));
	if (currentLayoutVersion >= REFERENCE_PACKAGING_LAYOUT_VERSION && hasCurrentLayoutStructure) {
		const canonicalName = `参考图双套袋环形包装产线 V${REFERENCE_PACKAGING_LAYOUT_VERSION}`;
		if (/^参考图双套袋环形包装产线\s*V\d+$/i.test(manifest.name || '') && manifest.name !== canonicalName) {
			manifest.name = canonicalName;
			return true;
		}
		return false;
	}
	const existingRouteIds = new Set((manifest.routes || []).map((item) => item.routeId));
	const objects = (manifest.objects || []) as TwinV7SceneObjectDefinition[];
	const hasStableReferenceObjects = stableReferenceObjectIds.every((id) => objects.some((item) => item.objectId === id));
	const hasLegacyReferenceRoutes = ['reference-small-pallet-main', 'reference-large-pallet-line', 'reference-central-ring'].every((id) => existingRouteIds.has(id));
	// V11 起普通辊道路线已经由组件 internalFlows + Connection 派生，不再持久化旧 reference-* Route。
	// 因此 V11 -> V12 必须能仅凭版本标记 + 稳定参考对象 + referenceDrawingLine 身份再次迁移，
	// 否则后续修正的辊面高度等 canonical 属性无法刷新到已经保存过一次的 V11 场景。
	const hasComponentizedReferenceLayout = Number(manifest.runtime?.referencePackagingLayoutVersion || 0) >= 11
		&& objects.some((item) => item.kind === 'component' && item.component?.properties?.referenceDrawingLine === true);
	const looksLikeReferenceLayout = hasStableReferenceObjects && (hasLegacyReferenceRoutes || hasComponentizedReferenceLayout);
	if (!looksLikeReferenceLayout) return false;

	const canonical = createReferencePackagingLineTwinSceneManifest();
	const previousRoutes = [...(manifest.routes || [])];
	const previousRouteMap = new Map(previousRoutes.map((item) => [item.routeId, item]));
	const previousReferenceRoutes = previousRoutes.filter((item) => referenceRouteIds.has(item.routeId));
	// Generated component routes are always rebuilt; only user-authored non-reference routes survive directly.
	manifest.routes = previousRoutes.filter((item) => !referenceRouteIds.has(item.routeId) && item.generatedBy !== 'component-connections');

	const previousReferenceObjects = objects.filter((item) => item.objectId === 'moving-package'
		|| (item.kind === 'component' && item.component?.properties?.referenceDrawingLine === true));
	const customObjects = objects.filter((item) => !previousReferenceObjects.includes(item));
	const claimedPreviousIds = new Set<string>();
	const upgradedReferenceObjects = (canonical.objects as TwinV7SceneObjectDefinition[])
		.map((item) => mergeReferenceObject(item, previousReferenceObjects, claimedPreviousIds));
	manifest.objects = [...customObjects, ...upgradedReferenceObjects] as TwinSceneManifest['objects'];

	const existingObjectIds = new Set(manifest.objects.map((item) => item.objectId));
	const retainedConnections = (manifest.connections || []).filter((connection) =>
		existingObjectIds.has(connection.from.objectId) && existingObjectIds.has(connection.to.objectId));
	const upgradeScaffoldRoutes = [createSmallMainRoute(), createSmallReturnRoute(), createGantryMergeRoute(), createLargeRoute(), createCentralBufferRoute(), createUpperFrameRoute()];
	const topologyConnections = buildReferenceTopologyConnections(manifest, upgradeScaffoldRoutes);
	// 必须与 canonical 新建场景保持同一组 B 排物理桥接；否则旧 V10 迁移后生成的组件 Route
	// 仍是旧拓扑 routeId，runtime/initializer 却会指向新 canonical routeId，最终 Simulation 0 托盘。
	const bottomLaneBConnections: ReferenceConnection[] = [
		{
			connectionId: 'reference-physical-bottom-b-output-to-merge',
			from: { objectId: 'reference-double-small-bottom', portId: 'b-output' },
			to: { objectId: 'reference-bottom-b-to-inspection-merge', portId: 'input' },
			autoGenerated: true,
			metadata: { topologyBridge: true, source: 'reference-physical-lane' },
		},
		{
			connectionId: 'reference-physical-bottom-b-merge-to-inspection',
			from: { objectId: 'reference-bottom-b-to-inspection-merge', portId: 'output' },
			to: { objectId: 'reference-conveyor-ref-edge-inspection-right-rise', portId: 'input' },
			autoGenerated: true,
			metadata: { topologyBridge: true, source: 'reference-physical-lane' },
		},
	];
	const reservedReferenceConnections = [...topologyConnections, ...bottomLaneBConnections];
	const rebuiltReferenceConnections = [...reservedReferenceConnections, ...buildReferenceTouchingConnections(manifest, 0.18, reservedReferenceConnections)];
	const connectionKeys = new Set<string>();
	manifest.connections = [...retainedConnections, ...rebuiltReferenceConnections].filter((connection) => {
		const key = `${connection.from.objectId}:${connection.from.portId}->${connection.to.objectId}:${connection.to.portId}`;
		const reverse = `${connection.to.objectId}:${connection.to.portId}->${connection.from.objectId}:${connection.from.portId}`;
		if (connectionKeys.has(key) || connectionKeys.has(reverse)) return false;
		connectionKeys.add(key);
		return true;
	});
	upsertGeneratedComponentRoutes(manifest);
	const canonicalEditableSmallRoute = canonical.routes.find((item) => item.routeId === canonical.runtime.primarySmallPalletRouteId);
	if (canonicalEditableSmallRoute) {
		const generatedSmallRoute = manifest.routes
			.filter((route) => route.generatedBy === 'component-connections'
				&& route.edges.some((edge) => edge.conveyorSizeClass === 'small' && edge.transportUnitType === 'plastic-pallet'))
			.sort((left, right) => right.edges.length - left.edges.length)[0];
		if (generatedSmallRoute) manifest.routes.splice(manifest.routes.indexOf(generatedSmallRoute), 1);
		manifest.routes = manifest.routes.filter((item) => item.routeId !== canonicalEditableSmallRoute.routeId);
		manifest.routes.unshift(mergeRouteForUpgrade(canonicalEditableSmallRoute, previousRouteMap.get(canonicalEditableSmallRoute.routeId)));
	}
	// 组件网络 Hash 会随辊道重布置变化，但主路线 ID 已被遥测键、发布场景和初始化器引用。
	// 迁移时按组件重合度找到同一物理网络，再恢复 canonical 稳定 ID。
	for (const canonicalRouteId of [canonical.runtime.primarySmallPalletRouteId, canonical.runtime.primaryWoodenPalletRouteId].filter(Boolean) as string[]) {
		if (manifest.routes.some((item) => item.routeId === canonicalRouteId)) continue;
		const canonicalRoute = canonical.routes.find((item) => item.routeId === canonicalRouteId);
		if (!canonicalRoute) continue;
		const canonicalComponentIds = new Set(canonicalRoute.edges.map((item) => item.componentObjectId).filter(Boolean));
		const candidate = manifest.routes
			.filter((item) => item.generatedBy === 'component-connections')
			.map((route) => ({ route, score: route.edges.filter((edge) => edge.componentObjectId && canonicalComponentIds.has(edge.componentObjectId)).length }))
			.sort((left, right) => right.score - left.score)[0];
		if (candidate && candidate.score > 0) candidate.route.routeId = canonicalRouteId;
	}

	// V11+ 保存场景已经只剩 generated component routes。重建以后需要把当前 V18
	// 主工艺路线上的 processStation 语义重新覆盖回来，否则物理拓扑虽然连通，
	// 机器人/桁架/天盖/缠膜/贴标工位会退化成普通输送点。
	for (const routeId of [canonical.runtime.primarySmallPalletRouteId, canonical.runtime.primaryWoodenPalletRouteId].filter(Boolean) as string[]) {
		const canonicalRoute = canonical.routes.find((item) => item.routeId === routeId);
		const migratedRoute = manifest.routes.find((item) => item.routeId === routeId);
		if (!canonicalRoute || !migratedRoute) continue;
		migratedRoute.name = canonicalRoute.name;
		migratedRoute.loop = canonicalRoute.loop;
		migratedRoute.startPointId = canonicalRoute.startPointId;
		migratedRoute.routingMode = canonicalRoute.routingMode;
		migratedRoute.junctionDecisions = structuredClone(canonicalRoute.junctionDecisions || {});
		migratedRoute.decisionRules = structuredClone(canonicalRoute.decisionRules || []);
		const previousRoute = previousRouteMap.get(routeId);
		for (const canonicalEdge of canonicalRoute.edges) {
			const migratedEdge = migratedRoute.edges.find((item) => item.edgeId === canonicalEdge.edgeId);
			if (!migratedEdge) continue;
			const previousEdge = previousRoute?.edges.find((item) => item.edgeId === canonicalEdge.edgeId);
			for (const field of edgeBindingFields) {
				if (previousEdge?.[field] !== undefined) (migratedEdge as any)[field] = previousEdge[field];
				else if (canonicalEdge[field] !== undefined) (migratedEdge as any)[field] = canonicalEdge[field];
			}
		}
		for (const canonicalPoint of canonicalRoute.points) {
			const migratedPoint = migratedRoute.points.find((item) => item.pointId === canonicalPoint.pointId);
			if (!migratedPoint || canonicalPoint.kind !== 'processStation' || !canonicalPoint.process) continue;
			const previousPoint = previousRoute?.points.find((item) => item.pointId === canonicalPoint.pointId);
			migratedPoint.kind = canonicalPoint.kind;
			migratedPoint.componentObjectId = canonicalPoint.componentObjectId;
			migratedPoint.componentPortId = canonicalPoint.componentPortId;
			migratedPoint.process = structuredClone(canonicalPoint.process);
			if (previousPoint?.actuatorBindingId) migratedPoint.actuatorBindingId = previousPoint.actuatorBindingId;
			if (previousPoint?.sensorBindingId) migratedPoint.sensorBindingId = previousPoint.sensorBindingId;
			if (previousPoint?.process) {
				for (const field of ['readyBindingId', 'busyBindingId', 'completeBindingId', 'resultBindingId', 'faultBindingId'] as const) {
					if (previousPoint.process[field]) migratedPoint.process[field] = previousPoint.process[field];
				}
			}
		}
	}

	// V11+ 的 generated route 本身也可能已经绑定 PLC/占用信号；按稳定 routeId/edgeId 继承。
	for (const generatedRoute of manifest.routes.filter((item) => item.generatedBy === 'component-connections')) {
		const previousRoute = previousRouteMap.get(generatedRoute.routeId);
		if (!previousRoute) continue;
		for (const generatedEdge of generatedRoute.edges) {
			const previousEdge = previousRoute.edges.find((item) => item.edgeId === generatedEdge.edgeId);
			if (!previousEdge) continue;
			for (const field of edgeBindingFields) if (previousEdge[field] !== undefined) (generatedEdge as any)[field] = previousEdge[field];
		}
	}

	// Preserve route-side PLC/occupancy bindings from V1-V11 by matching legacy edgeId to component sectionId.
	const generatedEdges = manifest.routes.filter((item) => item.generatedBy === 'component-connections').flatMap((item) => item.edges);
	for (const legacyRoute of previousReferenceRoutes) {
		for (const legacyEdge of legacyRoute.edges) {
			const generatedEdge = generatedEdges.find((item) => item.sectionId === legacyEdge.edgeId);
			if (!generatedEdge) continue;
			for (const field of edgeBindingFields) if (legacyEdge[field] !== undefined) (generatedEdge as any)[field] = legacyEdge[field];
		}
		for (const legacyPoint of legacyRoute.points) {
			const referenceObject = (manifest.objects as TwinV7SceneObjectDefinition[]).find((item) => item.kind === 'component'
				&& (item.objectId === legacyPoint.componentObjectId || item.component?.sectionId === legacyPoint.pointId));
			if (!referenceObject) continue;
			const generatedPoint = manifest.routes.filter((item) => item.generatedBy === 'component-connections').flatMap((item) => item.points)
				.find((item) => item.componentObjectId === referenceObject.objectId
					&& (item.kind === legacyPoint.kind || (legacyPoint.kind === 'processStation' && item.kind === 'processStation')));
			if (!generatedPoint) continue;
			if (legacyPoint.actuatorBindingId) generatedPoint.actuatorBindingId = legacyPoint.actuatorBindingId;
			if (legacyPoint.sensorBindingId) generatedPoint.sensorBindingId = legacyPoint.sensorBindingId;
			if (generatedPoint.process && legacyPoint.process) {
				for (const field of ['readyBindingId', 'busyBindingId', 'completeBindingId', 'resultBindingId', 'faultBindingId'] as const) {
					if (legacyPoint.process[field]) generatedPoint.process[field] = legacyPoint.process[field];
				}
			}
		}
	}
	const mergeCanonicalDefinitions = <T>(previous: T[] | undefined, canonicalItems: T[], idOf: (item: T) => string) => {
		const canonicalIds = new Set(canonicalItems.map(idOf));
		const customItems = (previous || []).filter((item) => !canonicalIds.has(idOf(item)));
		return [...customItems.map((item) => structuredClone(item)), ...canonicalItems.map((item) => structuredClone(item))];
	};
	manifest.bindings = mergeCanonicalDefinitions(manifest.bindings, canonical.bindings || [], (item) => item.bindingId);
	manifest.workPoints = mergeCanonicalDefinitions(manifest.workPoints, canonical.workPoints || [], (item) => item.workPointId);
	manifest.materialSlots = mergeCanonicalDefinitions(manifest.materialSlots, canonical.materialSlots || [], (item) => item.slotId);
	manifest.toolFrames = mergeCanonicalDefinitions(manifest.toolFrames, canonical.toolFrames || [], (item) => item.toolFrameId);
	manifest.actuators = mergeCanonicalDefinitions(manifest.actuators, canonical.actuators || [], (item) => item.actuatorId);
	const previousPoseMap = new Map((manifest.poses || []).map((pose) => [pose.poseId, pose]));
	const canonicalPoseIds = new Set((canonical.poses || []).map((pose) => pose.poseId));
	const customPoses = (manifest.poses || []).filter((pose) => !canonicalPoseIds.has(pose.poseId)).map((pose) => structuredClone(pose));
	manifest.poses = [...customPoses, ...(canonical.poses || []).map((pose) => {
		const previousPose = previousPoseMap.get(pose.poseId);
		return previousPose ? { ...structuredClone(pose), targets: structuredClone(previousPose.targets) } : structuredClone(pose);
	})];
	const previousBehaviorMap = new Map((manifest.behaviors || []).map((behavior) => [behavior.behaviorId, behavior]));
	const canonicalBehaviorIds = new Set((canonical.behaviors || []).map((behavior) => behavior.behaviorId));
	const customBehaviors = (manifest.behaviors || []).filter((behavior) => !canonicalBehaviorIds.has(behavior.behaviorId)).map((behavior) => structuredClone(behavior));
	manifest.behaviors = [...customBehaviors, ...(canonical.behaviors || []).map((behavior) => {
		const previousBehavior = previousBehaviorMap.get(behavior.behaviorId);
		return previousBehavior
			? { ...structuredClone(behavior), selectionWeight: previousBehavior.selectionWeight ?? behavior.selectionWeight }
			: structuredClone(behavior);
	})];
	manifest.interlocks = mergeCanonicalDefinitions(manifest.interlocks, canonical.interlocks || [], (item) => item.interlockId);
	manifest.runtime.primarySmallPalletRouteId = canonical.runtime.primarySmallPalletRouteId;
	manifest.runtime.primaryWoodenPalletRouteId = canonical.runtime.primaryWoodenPalletRouteId;
	manifest.runtime.routePalletInitializers = structuredClone(canonical.runtime.routePalletInitializers || []);
	manifest.runtime.referencePackagingLayoutVersion = REFERENCE_PACKAGING_LAYOUT_VERSION;
	if (/参考图双套袋环形包装产线\s*V\d+/i.test(manifest.name || '')) manifest.name = canonical.name;
	if ((manifest.description || '').includes('参考图') || (manifest.description || '').includes('中央环形缓存') || (manifest.description || '').includes('马蹄形缓存')) manifest.description = canonical.description;
	return true;
};
