<template>
	<div class="viewer" v-loading="loading">
		<header>
			<div><small>IOTSHARP TWIN 2D · PUBLISHED VIEWER</small><h2>{{ title }}</h2><p>v{{ versionNo || '-' }} · 只读生产运行态 · Telemetry Snapshot 1s</p></div>
			<div class="metrics"><el-tag type="success">Good {{ counts.good }}</el-tag><el-tag type="warning">Stale {{ counts.stale }}</el-tag><el-tag type="danger">Bad {{ counts.bad }}</el-tag><el-tag>Blocked {{ counts.blocked }}</el-tag></div>
			<div class="grow"/><el-button @click="router.push({path:'/iot/digital-twin/2d-scene',query:{sceneId}})">返回 2D 设计器</el-button><el-button @click="router.push({path:'/iot/digital-twin/scenes'})">场景中心</el-button><el-button @click="resetViewport">复位</el-button>
		</header>
		<main v-if="manifest">
			<svg ref="canvas" class="canvas" :viewBox="`${viewport.x} ${viewport.y} ${viewport.w} ${viewport.h}`" :style="{background:view.canvas.background}" @wheel.prevent="onWheel" @mousedown="onDown" @mousemove="onMove" @mouseup="onUp" @mouseleave="onUp">
				<defs><pattern id="viewer-grid" :width="view.canvas.gridSize" :height="view.canvas.gridSize" patternUnits="userSpaceOnUse"><path :d="`M ${view.canvas.gridSize} 0 L 0 0 0 ${view.canvas.gridSize}`" fill="none" stroke="rgba(148,163,184,.12)" stroke-width="1" /></pattern></defs>
				<rect x="0" y="0" :width="view.canvas.width" :height="view.canvas.height" :fill="view.canvas.showGrid?'url(#viewer-grid)':view.canvas.background" />
				<template v-for="r in manifest.routes || []" :key="r.routeId"><line v-for="e in r.edges" :key="e.edgeId" v-bind="edgeLine(e)" class="route" :class="edgeClass(e)"/></template>
				<template v-for="r in manifest.routes || []" :key="`${r.routeId}:points`"><g v-for="p in r.points" :key="p.pointId"><circle :cx="routePoint(p.pointId).x" :cy="routePoint(p.pointId).y" r="5" class="point"/><text :x="routePoint(p.pointId).x+8" :y="routePoint(p.pointId).y-8" class="point-label">{{ p.name }}</text></g></template>
				<g v-for="o in visibleObjects" :key="o.id" v-show="state(o).visible" class="object" :transform="transform(o)" :opacity="o.opacity ?? 1" @dblclick.stop="showRuntime(o)"><Twin2DSymbol :item="o" :runtime="state(o)"/></g>
			</svg>
			<div v-if="view.showMinimap" class="minimap"><svg :viewBox="`0 0 ${view.canvas.width} ${view.canvas.height}`" preserveAspectRatio="none"><rect width="100%" height="100%" fill="#07111f"/><rect v-for="o in visibleObjects" :key="o.id" :x="o.x" :y="o.y" :width="o.width" :height="o.height" fill="#38bdf8" opacity=".6"/><rect :x="viewport.x" :y="viewport.y" :width="viewport.w" :height="viewport.h" fill="none" stroke="#facc15" stroke-width="12"/></svg></div>
		</main>
		<el-result v-else-if="!loading" icon="warning" title="无法加载 2D 发布版本" :sub-title="errorText"/>
		<footer><span>Objects {{ view.objects.length }}</span><span>Bindings {{ manifest?.bindings?.length || 0 }}</span><span>Routes {{ manifest?.routes?.length || 0 }}</span><span>{{ polling?'Telemetry polling':'Telemetry paused' }}</span><span>Zoom {{ zoomPercent }}%</span></footer>
		<el-dialog v-model="runtimeVisible" :title="runtimeObject?.name || '运行态'" width="620px"><el-descriptions v-if="runtimeObject" :column="2" border><el-descriptions-item label="状态">{{ state(runtimeObject).statusText }}</el-descriptions-item><el-descriptions-item label="Quality">{{ state(runtimeObject).quality }}</el-descriptions-item><el-descriptions-item label="业务对象">{{ runtimeObject.businessObjectId || '-' }}</el-descriptions-item><el-descriptions-item label="最后更新">{{ state(runtimeObject).lastUpdated || '-' }}</el-descriptions-item><el-descriptions-item label="Occupancy">{{ state(runtimeObject).occupancy ?? '-' }} / {{ state(runtimeObject).capacity ?? '-' }}</el-descriptions-item><el-descriptions-item label="Reserved">{{ state(runtimeObject).reserved ?? '-' }}</el-descriptions-item></el-descriptions><pre v-if="runtimeObject">{{ JSON.stringify(state(runtimeObject).values,null,2) }}</pre></el-dialog>
	</div>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { useRoute, useRouter } from 'vue-router';
import { digitalTwinApi, type DigitalTwinSceneDetail, type TwinDataUpdate, type TwinRuntimeSnapshot } from '/@/api/digital-twin';
import type { TwinSceneManifest } from '/@/digital-twin/contracts';
import { ensureTwin2DView, type Twin2DObjectView, type Twin2DViewDefinition, type TwinSceneManifestWith2D } from '/@/digital-twin-2d/types';
import { interpolateTwin2DRoute, resolveTwin2DRouteRuntimeStates, resolveTwin2DRuntimeStates, type Twin2DObjectRuntimeState } from '/@/digital-twin-2d/runtime';
import Twin2DSymbol from '/@/digital-twin-2d/components/Twin2DSymbol.vue';
const route=useRoute(),router=useRouter(),apiData=<T,>(r:any):T=>r.data as T;
const loading=ref(true),polling=ref(false),errorText=ref(''),title=ref('2D 发布运行态'),versionNo=ref(0),runtimeUpdates=ref<TwinDataUpdate[]>([]),manifest=ref<TwinSceneManifest>(),view=ref<Twin2DViewDefinition>({version:1,canvas:{width:4800,height:3000,background:'#07111f',gridSize:20,showGrid:true,snapToGrid:true},objects:[],routePoints:{},layers:[],showMinimap:true});
const sceneId=String(route.query.sceneId||''),requestedVersion=Number(route.query.version||0);const viewport=reactive({x:0,y:0,w:2400,h:1500}),zoomPercent=computed(()=>Math.round(4800/viewport.w*100));const canvas=ref<SVGSVGElement>(),runtimeVisible=ref(false),runtimeObject=ref<Twin2DObjectView>();let pan:{x:number,y:number,vx:number,vy:number}|undefined,pollTimer:number|undefined,lastSig='';
const layerMap=computed(()=>new Map((view.value.layers||[]).map(l=>[l.id,l])));const visibleObjects=computed(()=>[...view.value.objects].filter(o=>!o.hidden&&layerMap.value.get(o.layerId||'production')?.visible!==false).sort((a,b)=>a.zIndex-b.zIndex));const states=computed(()=>manifest.value?resolveTwin2DRuntimeStates(view.value.objects,manifest.value,runtimeUpdates.value):{});const routeStates=computed(()=>manifest.value?resolveTwin2DRouteRuntimeStates(manifest.value,runtimeUpdates.value):{});const counts=computed(()=>Object.values(states.value).reduce((a,s)=>{if(s.quality==='stale')a.stale++;else if(['bad','missing'].includes(s.quality))a.bad++;else a.good++;if(s.blocked)a.blocked++;return a},{good:0,stale:0,bad:0,blocked:0}));
const state=(o:Twin2DObjectView):Twin2DObjectRuntimeState=>states.value[o.id]||{quality:'good',running:false,fault:false,visible:true,blocked:false,waiting:false,statusText:'UNBOUND',values:{}};const routePoint=(id:string)=>view.value.routePoints[id]||{x:0,y:0};const edgeLine=(e:any)=>{const a=routePoint(e.fromPointId),b=routePoint(e.toPointId);return{x1:a.x,y1:a.y,x2:b.x,y2:b.y}};const edgeClass=(e:any)=>({blocked:routeStates.value[e.edgeId]?.blocked,stale:routeStates.value[e.edgeId]?.stale});const transform=(o:Twin2DObjectView)=>{const s=state(o),moving=['pallet','carton','agv'].includes(o.symbolKey)&&s.routeProgress!==undefined&&manifest.value?interpolateTwin2DRoute(manifest.value,view.value.routePoints,s.routeProgress):undefined;const x=moving?moving.x-o.width/2:o.x,y=moving?moving.y-o.height/2:o.y;return `translate(${x} ${y}) rotate(${o.rotation} ${o.width/2} ${o.height/2})`};
const resetViewport=()=>Object.assign(viewport,{x:0,y:0,w:2400,h:1500});const zoom=(f:number)=>{const cx=viewport.x+viewport.w/2,cy=viewport.y+viewport.h/2;viewport.w=Math.max(300,Math.min(view.value.canvas.width*1.2,viewport.w*f));viewport.h=viewport.w*(1500/2400);viewport.x=cx-viewport.w/2;viewport.y=cy-viewport.h/2};const onWheel=(e:WheelEvent)=>zoom(e.deltaY<0?.9:1.1);const onDown=(e:MouseEvent)=>{if(e.button!==0&&e.button!==1)return;pan={x:e.clientX,y:e.clientY,vx:viewport.x,vy:viewport.y}};const onMove=(e:MouseEvent)=>{if(!pan)return;const scale=viewport.w/(canvas.value?.clientWidth||1);viewport.x=pan.vx-(e.clientX-pan.x)*scale;viewport.y=pan.vy-(e.clientY-pan.y)*scale};const onUp=()=>pan=undefined;
const poll=async()=>{if(!sceneId||!versionNo.value)return;try{const s=apiData<TwinRuntimeSnapshot>(await digitalTwinApi.snapshot(sceneId,versionNo.value));const next=s?.updates||[];const sig=JSON.stringify(next.map((x:any)=>[x.bindingId,x.value,x.quality,x.stale]));if(sig!==lastSig){runtimeUpdates.value=next;lastSig=sig}}catch(e:any){ElMessage.warning(e?.msg||e?.message||'Telemetry Snapshot 获取失败');stopPolling()}};const startPolling=()=>{stopPolling();polling.value=true;poll();pollTimer=window.setInterval(poll,1000)};const stopPolling=()=>{polling.value=false;if(pollTimer)window.clearInterval(pollTimer);pollTimer=undefined};
const load=async()=>{loading.value=true;try{if(!sceneId)throw new Error('缺少 sceneId');const scene=apiData<DigitalTwinSceneDetail>(await digitalTwinApi.getScene(sceneId));title.value=scene.name;const v=requestedVersion||scene.publishedVersion||0;if(!v)throw new Error('该场景尚未发布');versionNo.value=v;const version:any=apiData(await digitalTwinApi.getVersion(sceneId,v));const m=(version.manifest||version.manifestSnapshot||version.payload) as TwinSceneManifest;if(!m)throw new Error(`发布版本 v${v} 缺少 Manifest 快照`);manifest.value=structuredClone(m);view.value=ensureTwin2DView(manifest.value as TwinSceneManifestWith2D);startPolling()}catch(e:any){errorText.value=e?.msg||e?.message||'加载失败';manifest.value=undefined}finally{loading.value=false}};const showRuntime=(o:Twin2DObjectView)=>{runtimeObject.value=o;runtimeVisible.value=true};onMounted(load);onBeforeUnmount(stopPolling);
</script>
<style scoped lang="scss">
.viewer{height:calc(100vh - 132px);min-height:720px;margin:-15px;display:flex;flex-direction:column;background:#07111f;color:#dbeafe}.viewer>header{height:72px;display:flex;align-items:center;gap:12px;padding:8px 16px;background:#0a1626;border-bottom:1px solid rgba(148,163,184,.18)}header small{font-size:9px;color:#38bdf8;letter-spacing:.12em}header h2,header p{margin:2px 0}header h2{font-size:16px}header p{font-size:10px;color:#8ea6bf}.metrics{display:flex;gap:6px;margin-left:20px}.grow{flex:1}main{position:relative;flex:1;min-height:0}.canvas{width:100%;height:100%;display:block}.route{stroke:#38bdf8;stroke-width:4;opacity:.75}.route.blocked{stroke:#f97316}.route.stale{stroke:#8b5cf6;stroke-dasharray:12 8}.point{fill:#0ea5e9;stroke:#bae6fd;stroke-width:2}.point-label{fill:#94a3b8;font-size:10px}.object{cursor:pointer}.minimap{position:absolute;right:14px;bottom:14px;width:240px;height:145px;border:1px solid #365b7c;background:#07111f}.minimap svg{width:100%;height:100%}.viewer>footer{height:27px;display:flex;align-items:center;gap:18px;padding:0 12px;background:#07111f;border-top:1px solid rgba(148,163,184,.15);font-size:10px;color:#8ea6bf}pre{max-height:300px;overflow:auto;background:#050c16;color:#86efac;padding:10px;font-size:10px}
</style>
