import type {
	TwinRouteDefinition,
	TwinRouteEdgeDefinition,
	TwinRoutePointDefinition,
	TwinSceneManifest,
	TwinSceneObjectDefinition,
} from './index';

/** V7 参数化/智能组件实例；保持 SceneV1 顶层 schemaVersion 不变，作为向后兼容扩展。 */
export interface TwinSceneComponentDefinition {
	resourceKey: string;
	componentType: string;
	generator: string;
	generatorVersion: number;
	properties: Record<string, unknown>;
	/** Smart Model 标准 Slot 到 Manifest BindingId 的实例级映射。 */
	bindings?: Record<string, string>;
	sectionId?: string;
	/** 运输单元在 3D 场景设计器中吸附到的运行路线。 */
	routeId?: string;
	routeEdgeId?: string;
	/** 运输单元在所属 RouteEdge 上的归一化位置（0..1）。 */
	routeProgress?: number;
	/** 从路线起点累计到当前吸附点的设计距离；分支路线仅用于编辑器定位/诊断。 */
	routeDistanceMeters?: number;
}

export interface TwinComponentConnectionEndpoint {
	objectId: string;
	portId: string;
}

export interface TwinComponentConnectionDefinition {
	connectionId: string;
	from: TwinComponentConnectionEndpoint;
	to: TwinComponentConnectionEndpoint;
	autoGenerated?: boolean;
	metadata?: Record<string, unknown>;
}

export type TwinV7SceneObjectDefinition = Omit<TwinSceneObjectDefinition, 'kind'> & {
	kind: TwinSceneObjectDefinition['kind'] | 'component';
	component?: TwinSceneComponentDefinition;
};

export type TwinV7SceneManifest = Omit<TwinSceneManifest, 'objects'> & {
	objects: TwinV7SceneObjectDefinition[];
	connections?: TwinComponentConnectionDefinition[];
};

/**
 * 只增加可选字段，不改变 V1 已有字段含义。
 * JSON 仍能被旧版本读取；旧客户端会自然忽略这些扩展字段。
 */
declare module './index' {
	interface TwinSceneManifest {
		connections?: TwinComponentConnectionDefinition[];
	}

	interface TwinRouteDefinition {
		/** V7 自动路线的生成来源。 */
		generatedBy?: 'component-connections';
		/** 由排序后的 Component ObjectId 稳定计算，网络成员不变时保持不变。 */
		componentNetworkId?: string;
	}

	interface TwinRoutePointDefinition {
		componentObjectId?: string;
		componentPortId?: string;
	}

	interface TwinRouteEdgeDefinition {
		componentObjectId?: string;
		sectionId?: string;
	}
}

export type TwinV7RouteDefinition = TwinRouteDefinition;
export type TwinV7RoutePointDefinition = TwinRoutePointDefinition;
export type TwinV7RouteEdgeDefinition = TwinRouteEdgeDefinition;
