name: Temporary V7 .NET Component Build

on:
  push:
    branches: [Develop]
    paths:
      - '.github/workflows/tmp-v7-dotnet-component-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: Develop
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Restore IoTSharp web project
        run: dotnet restore ./IoTSharp/IoTSharp.csproj
      - name: Build IoTSharp web project
        run: dotnet build ./IoTSharp/IoTSharp.csproj --configuration Release --no-restore
